### ISSUE TITLE
Tic Tac Toe tutorial: Explain why to use renderSquare() instead of component syntax

### ISSUE THREAD

**Issue by lukewlms** [reactjs/react.dev#1033]
It's not clear in the [Tic Tac Toe tutorial](https://reactjs.org/tutorial/tutorial.html) why to create a function that renders, rather than create a component (which for this purpose does the same thing).

```
renderSquare(i) {
    return <Square value={i} />;
  }
```

vs this which is essentially the same thing:

`const TicTacToeSquare = (props) => <Square value={props.index} />`

This looks more like idiomatic React to me than the example with renderSquare() calls, so I'm missing something:

    <div className="board-row">
      <TicTacToeSquare index={1} />
      <TicTacToeSquare index={2} />
      <TicTacToeSquare index={3} />
    </div>

Can an explanation be added as to when it's appropriate to use function call syntax rather than a component?

It seems like we could use function call syntax everywhere but that doesn't seem like React (`renderComponent()` instead of just `<Component />`).

(I understand tutorial is more "what" than "why"/"how" but as-is I think it's a bit confusing on what code to use to render things in React.)

**Comment by ColsonXu** [comment]
Because later in the tutorial, you need to change this `renderSquare` function to read from an array in the `Board`'s state.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/19886740/168137809-219a8aae-d487-4a14-8429-b1c63be9303b.png">

**Comment by gaearon** [comment]
I don't think we'd do it quite the same way in the new tutorial.

**Comment by rickhanlonii** [comment]
Update: we don't, so this isn't relevant any more https://react.dev/learn/tutorial-tic-tac-toe
