### ISSUE TITLE
Inconsistent use of render, update and reconcile in docs

### ISSUE THREAD

**Issue by wederer** [reactjs/react.dev#1097]
In https://reactjs.org/docs/optimizing-performance.html#avoid-reconciliation the words "render", "re-render" and "update" are used multiple times without giving a clear definition.

To make matters worse https://reactjs.org/docs/optimizing-performance.html#shouldcomponentupdate-in-action even uses a different definition of the "render" and "re-render". 

### In Avoid Reconciliation:
"Note that when we’re entering a second todo, the first todo also flashes on the screen on every keystroke. This means it is being **re-rendered** by React together with the input. This is sometimes called a “wasted” **render**. We know it is unnecessary because the first todo content has not changed, but React doesn’t know this. Even though React only **updates** the changed DOM nodes, **re-rendering** still takes some time."
or
"If you know that in some situations your component doesn’t need to **update**,..."

### In shouldComponentUpdate In Action

"Here’s a subtree of components. For each one, SCU indicates what shouldComponentUpdate returned, and vDOMEq indicates whether the **rendered** React elements were equivalent. Finally, the circle’s color indicates whether the component had to be **reconciled** or not."

---

So even after reading the paragraphs multiple times and rereading https://reactjs.org/docs/reconciliation.html I still do not fully understand what all those terms mean.

This is related to the part about the **Highlight Updates** function in the React developer tool. No clear explanation is given which "updates" are being shown.

**Comment by ryoqun** [comment]
@wederer Hi, just to inform you, I've recently submitted a pull request for the reference doc about shouldComponentUpdate(  https://github.com/reactjs/reactjs.org/pull/1500 ). I didn't noticed React guide had a section regarding tha method... If my pull request get merged, I may work on this.

**Comment by BartoszKlonowski** [comment]
Hello @wederer, thanks for reporting!
I checked if the sentences you refer to appear in the latest of react.dev, and I wasn't able to find them any longer, so I'm sure this issue can be closed.
Let me know in case of more questions or create a new issue if you see something being unclear or incorrect in the docs.
