### ISSUE TITLE
Document how to update nested state properties

### ISSUE THREAD

**Issue by dandv** [reactjs/react.dev#1101]
In [setState](https://reactjs.org/docs/react-component.html#setstate), what should one return from the updater function in order to update a nested property of the state? This isn't documented, and it trips a **lot** of people:

https://stackoverflow.com/questions/18933985/this-setstate-isnt-merging-states-as-i-would-expect
https://stackoverflow.com/questions/43040721/how-to-update-a-nested-state-in-react
https://stackoverflow.com/questions/34071160/how-to-update-object-in-react-js
etc.

**Comment by zacharymorel** [comment]
I second this, I would love to read some detailed docs from y'all.

**Comment by cbdeveloper** [comment]
I investigated on this subject a little bit:
[https://stackoverflow.com/questions/54445040/whats-the-best-alternative-to-update-nested-react-state-property-with-setstate](https://stackoverflow.com/questions/54445040/whats-the-best-alternative-to-update-nested-react-state-property-with-setstate)

**Comment by yvesgurcan** [comment]
Hey guys! I opened a PR to document how to handle nested state properties. First contribution to the React project :)

**Comment by laozhizi** [comment]
@yvesgurcan where is the PR for handle nested state properties?

**Comment by bk973** [comment]
It's better to write your updater function to return new state based on old state. If  you do this, then updating state for nested data is pretty straightforward.

**Comment by silver-snoopy** [comment]
Has this issue been abandoned? I can pick it up and write the documentation based on the previous PR.

**Comment by yvesgurcan** [comment]
Hey @silver-snoopy, you're welcome to work based on the previous PR!

**Comment by Kanha-13** [comment]
Hey I wanted to contribute to this. As I have worked on nested state update. Can anyone help me how to contribute to this I am new to the opensource. Thank you

**Comment by tbroadley** [comment]
https://github.com/reactjs/reactjs.org/pull/4257#issuecomment-1025374675

> This has been addressed in the newer version of docmentation site.
>
> link: https://beta.reactjs.org/learn/updating-objects-in-state#updating-a-nested-object.

I'd suggest closing this issue and marking it as one that won't be completed.

**Comment by Leddfoot** [comment]
> [#4257 (comment)](https://github.com/reactjs/reactjs.org/pull/4257#issuecomment-1025374675)
> 
> > This has been addressed in the newer version of docmentation site.
> > link: https://beta.reactjs.org/learn/updating-objects-in-state#updating-a-nested-object.
> 
> I'd suggest closing this issue and marking it as one that won't be completed.

I agree with @tbroadley . No need to do this twice.

**Comment by spiritanand** [comment]
Is this issue open? Can you assign it to me if it is?

**Comment by BartoszKlonowski** [comment]
Dears,
yes, in the latest of react.dev this has been significantly updated, hence closing this issue.
However, if finding space for improvements feel free to create new issue.
Thank you!
