### ISSUE TITLE
Code sections show scrollbar and capture scroll when the last line is "code-highlighted"

### ISSUE THREAD

**Issue by firatoezcan** [reactjs/react.dev#1107]
Looks like this at https://reactjs.org/docs/lists-and-keys.html
![image](https://user-images.githubusercontent.com/25407276/43675619-4e93c962-97e3-11e8-93a2-5ec01f9afa1b.png)  

It happens when the last line of the code section is highlighted. I dont know if that is a Gatsby problem or from self-written CSS. The fix to resolve this case is just adding this rule since the sections dont rely on overflows anyways.
```
.gatsby-highlight {
overflow: hidden;
}
```

Main reason why I dont make a PR for this is that setting up and following the guidelines has too much overhead as opposed to someone who already has it down and adds that small fix in a few minutes.

Thanks for the great docs though, really appreciate it.

**Comment by firatoezcan** [comment]
Further looking led to the finding that this rule is as narrowly scoped as possible due to the fact that the overflow happened because of the negative bottom margin on the last element.
```
.gatsby-highlight-code-line:last-child {
    margin-bottom: 0;
}
```
This should only target exactly the root of the problem.

**Comment by TUNISIA-user** [comment]
Additional Tips:
Inspect Elements: Use browser developer tools to inspect the affected elements and verify how CSS rules are applied and how they impact layout.
Check for Conflicts: Ensure there are no conflicting CSS rules that might override or interfere with the overflow: hidden rule.
Test Across Devices: Make sure to test the changes on different devices and screen sizes to confirm that the fix works consistently.
