### ISSUE TITLE
Add Typescript as a compiler option for "Creating a Toolchain from Scratch"

### ISSUE THREAD

**Issue by senocular** [reactjs/react.dev#1185]
https://reactjs.org/docs/create-a-new-react-app.html#creating-a-toolchain-from-scratch

This lists multiple options for package manager (Yarn or npm) and bundler (webpack or Parcel) but only one option for compiler (Babel).  Typescript should also be listed as an alternate to Babel in the compiler recommendations.  Configuration of TypeScript as a compiler is covered in: https://reactjs.org/docs/static-type-checking.html#configuring-the-typescript-compiler as precedence.

**Comment by BartoszKlonowski** [comment]
Closing as per comments in the PR.
