### ISSUE TITLE
Fragment example code throws "Warning: validateDOMNesting(...)"

### ISSUE THREAD

**Issue by dance2die** [reactjs/react.dev#1373]
# What?
The sample Component code for `Table` in [Fragments/Motivation](https://reactjs.org/docs/fragments.html#motivation) throws follow warning.

```javascript
class Table extends React.Component {
  render() {
    return (
      <table>
        <tr>
          <Columns />
        </tr>
      </table>
    );
  }
}

```

`Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody> to your code to match the DOM tree generated by the browser.`

# How to reproduce the warning

You can either try it out on CodeSandbox or  
[![Edit 8n1lprk959](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8n1lprk959)

Use following code to test

```javascript
import React from "react";
import ReactDOM from "react-dom";

import "./styles.css";

class Columns extends React.Component {
  render() {
    return (
      <>
        <td>Hello</td>
        <td>World</td>
      </>
    );
  }
}

class Table extends React.Component {
  render() {
    return (
      <table>
        <tr>
          <Columns />
        </tr>
      </table>
    );
  }
}

function App() {
  return <Table />;
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

# How to fix the warning

One needs to wrap `<tr>` with `<tbody>` as shown below.

```diff
class Table extends React.Component {
  render() {
    return (
      <table>
+        <tbody>
          <tr>
            <Columns />
          </tr>
+        </tbody>
      </table>
    );
  }
}
```

**Comment by BartoszKlonowski** [comment]
Hello @dance2die, thank you for reporting and sorry for the delay!
From what I can see the latest of docs has this warning code gone, so I will close this issue as outdated.
