### ISSUE TITLE
[Documentation]Update the animations add-on page to react-transition-group

### ISSUE THREAD

**Issue by davidgtu** [reactjs/react.dev#1731]
While the note on top of the [Animation Add-ons](https://reactjs.org/docs/animation.html#low-level-api-reacttransitiongroup) is helpful, since `react-addons-css-transition-group` is deprecated, would it make sense to just change everything to `react-transition-group` rather than keeping it how it is currently with references to `react-addons-css-transition-group`?

Please correct me if I'm mistaken!

**Comment by tesseralis** [comment]
Hmm... it doesn't seem that you can reach that page from anywhere on the site. I think the page is just here just in case there are links to it and not meant to be updated.

**Comment by davidgtu** [comment]
Understood. I feel that the page should at the very least have an up-to-date guide on how to achieve animations (that I'm totally willing to write up!). However, if it's agreed upon that it's not meant to be updated then I'll close this.
