### ISSUE TITLE
Provide full signature for `useState`

### ISSUE THREAD

**Issue by alexanderkjeldaas** [reactjs/react.dev#2232]
The website says very little about `useState`.  At a minimum, the function signature for `setState` in this example should be provided.  Does it return undefined, or a Promise maybe?  Who knows?

<img width="945" alt="Skärmavbild 2019-08-12 kl  12 05 28" src="https://user-images.githubusercontent.com/339369/62858093-ab665600-bcf9-11e9-84d9-49f29ff1a41b.png">

**Comment by BartoszKlonowski** [comment]
The page describing `useState` got refactored and enhanced a lot with new react.dev docs.
I consider this issue no longer valid, as I find the new page sufficient, so I will close this issue.
Still, if there's any way we can still improve it feel invited to let me know.
Thank you for taking the time to report!
