### ISSUE TITLE
Top navbar is behind search input 

### ISSUE THREAD

**Issue by jcserracampos** [reactjs/react.dev#2324]
<img width="1280" alt="Screen Shot 2019-09-04 at 23 01 47" src="https://user-images.githubusercontent.com/7038498/64306169-27a23100-cf68-11e9-991e-6b3ad6239d27.png">

Safari on macOS.

**Comment by jcserracampos** [comment]
Apparently the problem is with box-sizing

**Comment by nikhilgupta30** [comment]
Here is the pr for the fix of search bar overlapping problem.
[](https://github.com/reactjs/reactjs.org/pull/2347)

**Comment by BartoszKlonowski** [comment]
Hello @jcserracampos!
Looking at the react.dev docs and how those layout are rendered, I don't see this issue you reported.
I will close this issue as outdated, thank you!
