### ISSUE TITLE
Direct link translated versions

### ISSUE THREAD

**Issue by jcserracampos** [reactjs/react.dev#2327]
It would be great if pages and blogpost lists translated versions of it.

When we search something, the first result is English documentation (What is good), when the user clicks on Languages it could list available translations and redirect to them.

**Comment by BartoszKlonowski** [comment]
Hello @jcserracampos!
With the latest of docs under react.dev, the translations are now handled as separate repos and are under the dedicated page listing them in general.
Considering this, I don't see this issue any longer valid.
Let me close it as outdated, but thank you for taking the time to report!
