### ISSUE TITLE
Syntax error in example on context documentation page

### ISSUE THREAD

**Issue by akanshgulati** [reactjs/react.dev#2425]
In the current [Dynamic Context](https://reactjs.org/docs/context.html#dynamic-context) example, there are following issues

1. The `<Page>` and `<Section>` component definition is not provided in example code. It causes syntax issues and needs to be removed manually. 
2. The `<ThemedButton>` component has background color style but no style for text color. 
3. The default text of the `ThemedButton` component is not present due to which the default case on `app.js` file does not appear properly. 

### Current state
<img width="299" alt="Screenshot 2019-10-12 at 02 18 17" src="https://user-images.githubusercontent.com/5287100/66684303-629a3180-ec97-11e9-98d3-98be4e67c3f2.png">

### After fix 
<img width="297" alt="Screenshot 2019-10-12 at 02 17 52" src="https://user-images.githubusercontent.com/5287100/66684302-629a3180-ec97-11e9-97c4-1d2dafdd2775.png">

**Comment by alexkrolick** [comment]
These examples were originally meant to be presented as example app code, not necessarily runnable examples. I guess we can change that if the examples represent realistic use cases and not oversimplified ones.

**Comment by akanshgulati** [comment]
@alexreardon I understand but generally with example, we expect to use it to try and learn from it(which I did to understand context and it didn't work due to these error). We have used both `foreground` and `background` colors and not using it. I felt that this was not checked at first and opened the issue as well as PR for the fix.

**Comment by alexreardon** [comment]
I think I was mentioned by mistake

**Comment by akanshgulati** [comment]
Sorry, @alexreardon. Was mentioning @alexkrolick

**Comment by BartoszKlonowski** [comment]
Hello @akanshgulati!
Unfortunately the legacy docs pages are no longer maintained, making this issue outdated.
Let me close this, but if you something that could be improved in the latest of react.dev, please open new issue.
Thank you!
