### ISSUE TITLE
Docs are missing information about React keys and component identity

### ISSUE THREAD

**Issue by bryanyee** [reactjs/react.dev#2904]
Docs are missing information about React keys and component identity. It'd be helpful to learn about the underlying reason React uses keys to give identity to components and manage component lifecycle based on data, in addition to the current explanations that keys improve list render performance.

**Comment by bryanyee** [comment]
Suggested PR: https://github.com/reactjs/reactjs.org/pull/2500

**Comment by BartoszKlonowski** [comment]
Hello @bryanyee!
Currently in the react.dev docs I see information about `key` (for instance in [Rendering lists](https://react.dev/learn/rendering-lists) page or [Preserving and Resetting State](https://react.dev/learn/preserving-and-resetting-state) which links to the former) which I find sufficient as a `key` prop explanation.
Let me close this issue as completed.
