### ISSUE TITLE
`Concurrent UI Patterns` needs to be updated with `unstable_` prefixes

### ISSUE THREAD

**Issue by leonardodino** [reactjs/react.dev#2960]
[this PR on `facebook/react`](https://github.com/facebook/react/pull/18825) added the `unstable_` prefix for a bunch of hooks/components/methods listed on [this page](https://reactjs.org/docs/concurrent-mode-patterns.html).

The current docs use the unprefixed names, which won't work until this feature is officially released 😄

**Comment by nuragic** [comment]
Yes please! Those docs are public now so I think they need to be updated...

I was trying to switch to the `experimental` channel right now and got `createRoot is not a function`.

@leonardodino Maybe you could update that page yourself and send a PR? 😄 🙏 

Thanks
