### ISSUE TITLE
No scrollbar, cannot scroll sidebar

### ISSUE THREAD

**Issue by joshribakoff** [reactjs/react.dev#3171]
![Screen Shot 2020-08-04 at 10 13 25 AM](https://user-images.githubusercontent.com/4021306/89323853-3511e080-d63b-11ea-854b-f97f09f54840.png)

**Comment by rimildeyjsr** [comment]
@rickhanlonii - can I work on a PR for this, if this needs to be fixed?

**Comment by sijusamson** [comment]
@joshribakoff Is this a system specific issue ? As I am able to scroll sidebar. So I guess there is no need for an extra scroll bar. 

Looking forward to hear from you !

**Comment by rickhanlonii** [comment]
Yeah @rimildeyjsr! I'm not sure what the issue is though, @joshribakoff can you explain?

**Comment by ShivamYadav-Coding** [comment]
If any one have this problem then just try to use your touchpad gestures or mouse scroll wheel over sidebar. I think you might not using it and searching for a scrollbar.

**Comment by MubashirWaheed** [comment]
In the `https://react.dev/reference/react` section I am unable to scroll

https://github.com/reactjs/react.dev/assets/41460586/5e1434ac-39a8-4442-ade0-68dd04ea0235

**Comment by raahul131** [comment]
Can I work in this issue, I have experience on working on this type of issues previously.

**Comment by ArchitGajjar** [comment]
Hi @joshribakoff is this issue still open or closed ? can you please assigned to me ?
