### ISSUE TITLE
Maybe there can be an official doc note talking about event delegation

### ISSUE THREAD

**Issue by KennethKinLum** [reactjs/react.dev#3543]
Maybe there can be an official doc note talking about event delegation, in the page of either

https://reactjs.org/docs/events.html

or 

https://reactjs.org/docs/handling-events.html

From the following posts: 

https://dev.to/thawsitt/should-i-use-event-delegation-in-react-nl0#:~:text=Event%20delegation%20is%20a%20performance%20optimization%20method%20in%20the%20world%20of%20Javascript.&text=With%20event%20delegation%20approach%2C%20instead,read%20more%20about%20it%20here.

and

https://github.com/facebook/react/issues/13635

It suggests that we should not do event delegation ourselves when doing React.  That's because React already does something similar by only attaching a single listener at the document level.

However, isn't it true that, if the page has 50 or 200 rows in a table, and the programmer is doing

```
<tr onClick={() => handleRowClick(i)}<td> ...   </td></tr>
```

then the 200 rows, each would be creating a function?  Maybe 200 functions for once is ok, but what if it is an app that updates this table every 5 seconds?

Then isn't it true that every 5 seconds, 200 new functions are created, and if it is a monitoring app, then it could be lots of functions created but it would depend on the browser's garbage collection.

I think, if the programmer writes

```
<tr data-index={i} key={i} onClick={handleRowClick}<td> ...   </td></tr>
```

then it is quite ok, because then it doesn't create a new function each time.  Now the programmer can use the `ev.target.dataset.index` to get to the value  (or the `key`? but the `dataset` should be more reliable).

Maybe the fact about not needing event delegation but at the same time, be aware that if possible, don't create extra functions if possible, can be documented in one page of the official docs.  Otherwise programmers have to rely on someone's blog and links to make decision and it is somewhat unofficial info.

**Comment by eps1lon** [comment]
> Maybe the fact about not needing event delegation but at the same time, be aware that if possible, don't create extra functions if possible, can be documented in one page of the official docs. Otherwise programmers have to rely on someone's blog and links to make decision and it is somewhat unofficial info.

From my experience "creating functions" has virtually no cost at all. If I remember correctly, the React core team did investigate this before proposing Hooks since it's fairly common to create a lot of inline functions inside the render method. And rendering is performance critical so if it's not a problem then, I don't think it's a problem worth solving with event delegation.

Did you measure if event delegation improved the speed of your React application?

**Comment by KennethKinLum** [comment]
> > Maybe the fact about not needing event delegation but at the same time, be aware that if possible, don't create extra functions if possible, can be documented in one page of the official docs. Otherwise programmers have to rely on someone's blog and links to make decision and it is somewhat unofficial info.
> 
> From my experience "creating functions" has virtually no cost at all. If I remember correctly, the React core team did investigate this before proposing Hooks since it's fairly common to create a lot of inline functions inside the render method. And rendering is performance critical so if it's not a problem then, I don't think it's a problem worth solving with event delegation.
> 
> Did you measure if event delegation improved the speed of your React application?

I think React "already" does the event delegation for you.  So it is not binding 200 listeners to 200 elements, but just binding one.  The thing is, some programmers might write it so that 200 function instances are created.  So that can still be an issue, and like what I said, what if it is 200 function instances every 5 seconds? Yeah I can try it, but it also depends on Google Chrome, Safari, and Firefox and the various mobile browsers.  Or, what about just documenting that event delegation is not needed in the ReactJS docs? (but also, try your best to write `onClick={handleClick}` and not create extra functions if you can.

**Comment by eps1lon** [comment]
I understand what event delegation is and how React utilizes this pattern

> The thing is, some programmers might write it so that 200 function instances are created. So that can still be an issue, and like what I said, what if it is 200 function instances every 5 seconds? 

How do you know "creating function instances" is an issue?

Note that the docs specifically talk about performance concerns with creating many functions:

> No. In modern browsers, the raw performance of closures compared to classes doesn’t differ significantly except in extreme scenarios.

-- https://reactjs.org/docs/hooks-faq.html#are-hooks-slow-because-of-creating-functions-in-render

I don't think "200 vs 5" is an extreme scenario. I suspect you only notice this after at least 2 or 3 orders of magnitude more. At this point creating functions is probably still only a small percentage of the runtime and virtualisation the better tool to solve performance problems.

**Comment by KennethKinLum** [comment]
> Note that the docs specifically talk about performance concerns with creating many functions:
> 
> > No. In modern browsers, the raw performance of closures compared to classes doesn’t differ significantly except in extreme scenarios.

Isn't that about closures, vs creating 200 functions for the event listeners?

In any event, I think it is good that the programmer can be aware of the two methods, and if one is a better version, and it is almost free of charge, why not?  Regarding not needing event delegation in React, I think it is worth it to have it included in the official docs.

**Comment by eps1lon** [comment]
> Isn't that about having a closure, vs creating 200 functions for the event listeners?

It's answering "Are Hooks slow because of creating functions in render?". Maybe I'm not understanding what you're proposing. Could you share a code example of the two different approaches you think should be documented?

> In any event, I think it is good that the programmer can be aware of the two methods, and if one is a better version, and it is almost free of charge, why not? R

We still haven't established if one version is better and how much better it is. If one only provides marginal gains, but requires more code, we don't need to mention it.

**Comment by KennethKinLum** [comment]
> > Isn't that about having a closure, vs creating 200 functions for the event listeners?
> 
> It's answering "Are Hooks slow because of creating functions in render?". Maybe I'm not understanding what you're proposing. Could you share a code example of the two different approaches you think should be documented?
> 
> > In any event, I think it is good that the programmer can be aware of the two methods, and if one is a better version, and it is almost free of charge, why not? R
> 
> We still haven't established if one version is better and how much better it is. If one only provides marginal gains, but requires more code, we don't need to mention it.

Regardless how the two versions are written, "not needing to use event delegation in React" is a separate topic.

As for the two version, I have mentioned it in the original post.

It is when `arr` is an array of 200 items,

```js
<ul>
  arr.map((e, i) => <li key={i} onClick={handleRowClick}>e.num</li>);
</ul>
```

vs

```js
<ul>
  arr.map((e, i) => <li key={i} onClick={() => handleRowClick(i)}>e.num</li>);
</ul>
```

**Comment by eps1lon** [comment]
> As for the two versions, I have mentioned it in the original post.

Ok, so you are talking about creating functions during render. Seems to me this is what the FAQ answer is referring to.

> I am saying it should be mentioned in the official docs. It should be mentioned regardless of how the two versions are written.

You can write JavaScript (or any program for that matter) in (virtually) infinite ways. That doesn't mean we should document every single approach but only the ones that do make sense.

The docs are about learning React and being productive with it. Documenting multiple patterns for the same problem should only be happening if these patterns have different trade-offs. Right now it seems to me your only argument is "another way exists, so we should document it".

**Comment by KennethKinLum** [comment]
No, I am saying documenting "not needing to use event delegation in React".  Can you re-read the post.

**Comment by KennethKinLum** [comment]
> > As for the two versions, I have mentioned it in the original post.
> 
> Ok, so you are talking about creating functions during render. Seems to me this is what the FAQ answer is referring to.
> 
> > I am saying it should be mentioned in the official docs. It should be mentioned regardless of how the two versions are written.
> 
> You can write JavaScript (or any program for that matter) in (virtually) infinite ways. That doesn't mean we should document every single approach but only the ones that do make sense.
> 
> The docs are about learning React and being productive with it. Documenting multiple patterns for the same problem should only be happening if these patterns have different trade-offs. Right now it seems to me your only argument is "another way exists, so we should document it".

No, I am saying documenting "not needing to use event delegation in React". Can you re-read the post.

**Comment by ishant4398** [comment]
Please Document it whether to use it or not and what tradeoffs can happen and in which scenarios. So that we have better understanding of React like what to do and what not is required.

**Comment by rickhanlonii** [comment]
We explain the event system in the docs for events [here](https://react.dev/reference/react-dom/components/common#react-event-object). We're not going to document that you don't need to do delegation.
