### ISSUE TITLE
Topic Addition Idea | Using Props with APIs

### ISSUE THREAD

**Issue by ritvikos** [reactjs/react.dev#4095]
Many a times while doing projects, dynamic data is extracted via APIs. So, adding a section stating the use of props when fetching dynamic data from external resources would be helpful.

**Comment by dev-tom-0108** [comment]
Which API do you use?

**Comment by Ritvik-UX** [comment]
@dev-tom-0108 : 
Fetching And Rendering Fetch APIs using map and Axios (adding this in the documentation).
