### ISSUE TITLE
Add a note that useEffect is not guaranteed to run after paint

### ISSUE THREAD

**Issue by thoughtspile** [reactjs/react.dev#4107]
[`useEffect` docs](https://reactjs.org/docs/hooks-reference.html#useeffect) suggest the effect always runs after paint, which is apparently not guaranteed. For example, when `useLayoutEffect` from the same render triggers an update, the effect must be flushed before that update, which is before paint (I wrote a [post](https://thoughtspile.github.io/2021/11/15/unintentional-layout-effect/) detailing this behavior). Folks in facebook/react#20863 discuss similar pitfalls. 

Could we clarify the guarantees in the docs? I'd be glad to submit a PR if you confirm my understanding of the behavior.

**Comment by abacaj** [comment]
My question here to you would be in what case do you need both useEffect and useLayoutEffect?

From my experience, I've only ever needed one of those.

**Comment by thoughtspile** [comment]
> in what case do you need both useEffect and useLayoutEffect in the same component?

All effects from an update are [flushed globally,](https://github.com/facebook/react/blob/4ff5f5719b348d9d8db14aaa49a48532defb4ab7/packages/react-reconciler/src/ReactFiberWorkLoop.new.js#L769) not broken up by components. 

> From my experience, I've only ever needed one of those.

Are you sure you've never had a custom hook, eg [`usePopper`,](https://github.com/popperjs/react-popper/blob/master/src/usePopper.js) that has `useLayoutEffect` inside?

**Comment by abacaj** [comment]
That is using `useLayoutEffect` and not mixing the two, my question is asking why do you use both i.e

```
useEffect(() => {}, []);
useLayoutEffect(() => {}, []);
```

**Comment by thoughtspile** [comment]
> Basically, what is the use case for you to mix the two? 

Let me detail a bit:

1. Updating from `useLayoutEffect` flushes _all_ effects from the same transaction, even the ones scheduled in other components (see [sandbox](https://codesandbox.io/s/charming-wozniak-kdz3u?file=/src/App.js:396-412)).
2. There are other places where requesting an update forces the effects to flush early — `requestAnimationFrame`, microtasks, and possibly `*Observer` callbacks.
3. You can `useEffect` and `usePopper` (or any other custom hook) from the same component without knowing that `usePopper` calls `useLayoutEffect` under the hood.

> Otherwise the docs as I read them are correct https://reactjs.org/docs/hooks-reference.html#useeffect:
>> Unlike componentDidMount and componentDidUpdate, the function passed to useEffect fires after layout and paint

This part is fine (it applies to uLE and cDM / cDU, too). The [section on "Timing of effects"](https://reactjs.org/docs/hooks-reference.html#timing-of-effects) says that _the function passed to useEffect fires after layout and paint_ and _Although useEffect is deferred until after the browser has painted,_ suggesting it's a strong guarantee

>> We’ve tried to delay addEventListener until after paint with useEffect, but the state update in useLayoutEffect forces it to happen before paint
>
>This is actually correct behavior:
>> Your code runs immediately after the DOM has been updated, but before the browser has had a chance to "paint" those changes (the user doesn't actually see the updates until after the browser has repainted).

Kent's passage refers to the `layoutEffect` callback, while `useEffect` should be delayed until after paint, see ["Timing of effects" section](https://reactjs.org/docs/hooks-reference.html#timing-of-effects) in the official docs.

**Comment by abacaj** [comment]
>1. Updating from useLayoutEffect flushes all effects from the same transaction, even the ones scheduled in other components (see sandbox).

What did you expect to happen in the example here? This is what I saw:
![Screen Shot 2021-11-16 at 10 37 30 AM](https://user-images.githubusercontent.com/7272343/142017085-78d57ef0-f645-49d8-a219-1ac7cb32a2df.png)

**Comment by thoughtspile** [comment]
> What did you expect to happen in the example here?

If `useLayoutEffect` fires before paint, and `useEffect` fires after paint, the sequence should be `layout effect` > `frame` > `effect`. This is also what's logged if you remove the `update({})`.

**Comment by abacaj** [comment]
> > What did you expect to happen in the example here?
> 
> If `useLayoutEffect` fires before paint, and `useEffect` fires after paint, the sequence should be `layout effect` > `frame` > `effect`. This is also what's logged if you remove the `update({})`.

Makes sense, it seems the issue is tied to state updates in useLayoutEffect. I haven't had any weird performance/UI issues as of yet because of it. I assume many projects using react are running into this situation unknowingly.

**Comment by rickhanlonii** [comment]
The new docs include this info in the caveats: https://react.dev/reference/react/useEffect#caveats

<img width="963" alt="Screenshot 2024-01-11 at 1 34 29 PM" src="https://github.com/reactjs/react.dev/assets/2440089/c9019242-65f6-4db2-b20c-c1d842395602">
