### ISSUE TITLE
[Beta] replace Sandpack

### ISSUE THREAD

**Issue by nihgwu** [reactjs/react.dev#4338]
Last weekend I created a [React Runner with CodeMirror](https://react-runner-codemirror.vercel.app/)(I copied the example from this [PR](https://github.com/reactjs/reactjs.org/pull/4320)) which does the same work as `Sandpack` does,  no iframe, no extra resource loading, no bundling, so it's super fast and get updated simultaneously on inputing. I'm using shadow DOM to support scoped styling, so it doesn't SSR, if we can just define the style globally, then it will like [here](https://react-runner.vercel.app/#multi-files)

So I'd like to ask if it's viable to replace `Sandpack` with `React Runner`, I can work on the prototype and polish it further

**Comment by gaearon** [comment]
Can you make a prototype PR so we can compare? Ideally with enough feature parity that all sandboxes (including the ones that have Immer in them) run.

**Comment by nihgwu** [comment]
@gaearon Immer should work definitely, you just need add imports to the scope, [here](https://play-react.vercel.app/) is another example of on-demand import, I'll try to make a prototype PR later, whilst [the example](https://react-runner-codemirror.vercel.app/) I created last weekend should have covered most of the features

**Comment by BartoszKlonowski** [comment]
Closing as I find this issue unfortunately outdated and no longer valid with the way how react.dev handles examples.
Still, if there's a space or need for improvements please let me know.
Thank you!
