### ISSUE TITLE
[Beta] Layout bug on Blog page

### ISSUE THREAD

**Issue by redhaam** [reactjs/react.dev#4370]
Hello 👋 
Nice work on the new documentation, I really like the new look.

I found a small bug when visiting the blog page on the website where we can see that:
- A portion of the main section is hidden behind tha sidebar.
- The text color is undreable because it doesn't adapt for the dark theme.
- There's a horizontal scroll on the mobile view.

Link to the page containing the bug : https://beta.reactjs.org/blog

I tried to figure out the source of the bugs and I think I'm able to fix it so please let me know if I can work on it I'd be happy to contribute.

![image](https://user-images.githubusercontent.com/44533239/155036789-e5084d5e-0ca7-4d41-a1ec-c5f0d2b51c22.png)
![image](https://user-images.githubusercontent.com/44533239/155036853-02e05d59-b6cc-40db-a204-d170e27dc9fa.png)

**Comment by gaearon** [comment]
the blog page doesn't really "exist" yet. (did you find it by manually typing the url?)

the fix will be to use a separate `LayoutBlog` which wouldn't have the left sidebar, i think.

**Comment by redhaam** [comment]
Hello Dan thank you for your reply.
Actually I accessed the blog page through a link within the `community` page. Anyway you can fix this later once you're done with  the content I guess.

**Comment by gaearon** [comment]
i wouldn't mind merging a fix! if you'd like to work on it, try the approach i suggested — look at how `Layout*` files are mapped in `md-layout-loader.js` and try creating a separate layout alongside `LayoutLearn.tsx` and such, which should have no sidebar.

**Comment by BartoszKlonowski** [comment]
I can see this issue is no longer valid, hence closing.
Thanks everyone!
