### ISSUE TITLE
Needs Clarity reactjs.org/content/docs/reference-react-dom-server.md

### ISSUE THREAD

**Issue by Bradslavens** [reactjs/react.dev#4443]
I'm currently learning React.  I was a little confused by the ReactDOMServer.renderToString(element) example on line 37 of reactjs.org/content/docs/reference-react-dom-server.md.  I didn't realize element should be a tag.  I enterered "App" instead of <App />.
Please clarify in the documentation.

Thank you!

**Comment by BartoszKlonowski** [comment]
As this issue relates to legacy documentation in reactjs.org, I will close this as well as the fixing PR.
However, if you find some space for improvements on the new react.dev documentation, feel free to create new issue.
Thank you!
