### ISSUE TITLE
can't be opened in google translate & microsoft translator

### ISSUE THREAD

**Issue by lgh06** [reactjs/react.dev#467]
https://translate.google.com.hk/ https://www.bing.com/translator/

I type https://reactjs.org/ at the two sites, shows 'Page Not Found'...

**Comment by gaearon** [comment]
This should be fixed now.
https://github.com/reactjs/reactjs.org/pull/1148

**Comment by gaearon** [comment]
Hmm, this is actually a separate problem related to URLs. Will look.

**Comment by rickhanlonii** [comment]
Closing because this works on react.dev
