### ISSUE TITLE
Content issue on `reactjs.org/tutorial/tutorial.html`

### ISSUE THREAD

**Issue by RitikJaiswal75** [reactjs/react.dev#5181]
### Problem faced
There are six strips in setting up the local dev env. But then the flow breaks the tutorial now says running npm start renders an empty tic-tac-toe field. But that won't be the case until we write the code from the starter code.

### Problem Description
While going through the tutorial -> `setup for Tutorial` -> `option 2: Local Development Environment`. I found it hard to go through and follow the tutorial as the flow breaks over there.

Under this section, there is an optional section to set up the editor. But, an extra line to use the code from `codepen.io` felt missing.

The tutorial could be made more efficient by letting the users know the steps to perform in local dev env.

**Comment by rickhanlonii** [comment]
> But that won't be the case until we write the code from the starter code.

Sorry, what do you mean? When I follow the steps, I get a working board that matches the sandbox:

<img width="631" alt="Screenshot 2024-01-10 at 3 38 48 PM" src="https://github.com/reactjs/react.dev/assets/2440089/6d098da9-1927-430c-8012-6e1dc8f39e47">

If you can provide some more information I'm happy to re-open and investigate.
