### ISSUE TITLE
Change displayed shortcut in search based on user system .

### ISSUE THREAD

**Issue by tys404** [reactjs/react.dev#5257]
In React Docs Beta ([https://beta.reactjs.org/](https://beta.reactjs.org/)) search input shortcut shown for searching is `⌘ K `even though I'm on windows. It should display `Ctrl K` on windows (and linux?).

**Comment by arafatiqbal** [comment]
There is an open PR for this https://github.com/reactjs/reactjs.org/pull/5202

**Comment by tys404** [comment]
thanks, I tried searching this but didn't find.

**Comment by jirkavrba** [comment]
I think this issue now can be closed as https://github.com/reactjs/react.dev/pull/5737 was merged :slightly_smiling_face:
