### ISSUE TITLE
Sidebar is not scrollable

### ISSUE THREAD

**Issue by iaseth** [reactjs/react.dev#5333]
![Screenshot from 2022-12-08 23-47-11](https://user-images.githubusercontent.com/72359549/206535117-9cce6d7a-0940-4458-9b33-e66cb89604c5.png)
The height of the sidebar on docs pages is set to `calc(100vh - 50px)`, because of which some links at the bottom are not reachable.

**Comment by joeshajan** [comment]
Can I fix this issue?

**Comment by webbdays** [comment]
@joeshajan
are you still working on to fix this issue?
please let me know.
Otherwise i will take on.

**Comment by joeshajan** [comment]
Hey @webbdays you can take this. I'm busy with onother work.🙂

**Comment by abhinandanwadwa** [comment]
Hey @gaearon I've fixed this issue.

**Comment by webbdays** [comment]
that solves the problem.
what about setting bottom:0 instead of height ?

**Comment by abhinandanwadwa** [comment]
> that solves the problem. what about setting bottom:0 instead of height ?

Yes that works too! But it won't make much difference because i've tested my solution in every possible resolution and it works just fine.

**Comment by iaseth** [comment]
Closed issue because new docs site has been released.
