### ISSUE TITLE
 Transition to the original page after switching a language

### ISSUE THREAD

**Issue by massongit** [reactjs/react.dev#5367]
The current flow of language switching is as follows:

1. Click on `Languages` ​​in website's header.
2. Click a language.
3. Move to the top page.
4. Move to the original page by myself.

This flow is difficult to use because it does not automatically transition to the original page.
Therefore, I want to add a drop-down menu for switching languages ​​in the header, and change to the original page after selecting a language.

**Comment by abhinandanwadwa** [comment]
Hey @gaearon , i've tried to fix this issue!

**Comment by BartoszKlonowski** [comment]
Dears,
As the react.dev does not use the direct translation switch now, instead having a separate page for translation repos, this issue is no longer valid.
Let me close it as well as the PR implementing the fix.
Thank you!
