### ISSUE TITLE
react js official doc learning example to create button using MyApp() throwing console error

### ISSUE THREAD

**Issue by jo777750** [reactjs/react.dev#5533]
react js official doc learning example MyApp() in  [https://beta.reactjs.org/learn#components](url)   has console log error as displayed in screenshot.
![err](https://user-images.githubusercontent.com/66462046/216129906-87b55dd3-a99d-4259-917c-841890ef7dc2.png)

babel version - 7.20.7 (@babel/core 7.20.12)

Js code prepocessed sucess:
``` 
//test.js
const root2 = ReactDOM.createRoot(document.getElementById('buton'));
const element2 = <MyApp />; 
root2.render(element2);


function MyButton() {
  return (
    <button>
      I'm a button 0
    </button>
  );
}

export default function MyApp() {
  return (
    <div>
<hr />
      <h1>Welcome to my app777</h1>
      <hr />
      <MyButton />
    </div>
  );
}

```

HTML:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Test Page-React</title>
  </head>
  <body>

    <h2>Add React in One Minute</h2>
    
    <!-- We will put our React component inside this div. -->
 
<link rel="icon" type="./x-icon" href="./favicon.ico">
<div id="buton"></div>

    <!-- Load  React. -->
    <!-- Note: when deploying, replace "development.js" with "production.min.js". -->
    <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
  <!-- Load your React component. -->
 <script type="module" src="test.js"></script>
  
  </body>
</html>
```

**Comment by gaearon** [comment]
OK yeah this is a bit tricky. We use import/export syntax throughout the docs, but if you don't use a bundler, you're gonna have to avoid it. I think the fix here will be to add a section on enable `<script type="module"` on this page. I'll add to TODOs.

**Comment by jo777750** [comment]
this error was not happening in babel version:6.26.0 (babel-core 6.26.3) but occurred after I updated to 7.20.7 (@babel/core 7.20.12) , new version as per react install docs.i guess regression testing needs to be done by facebook before code release

**Comment by gaearon** [comment]
The issue you're referring to now (`export` not working) would occur with any version of Babel.

**Comment by gaearon** [comment]
We've revamped these pages to focus on a setup that supports all features.

https://react.dev/learn/add-react-to-an-existing-project
