### ISSUE TITLE
React Docs Beta - Tutorial: Tic-Tac-Toe

### ISSUE THREAD

**Issue by ggert345** [reactjs/react.dev#5585]
Hello, 

I think there is an error in the below paragraph. Where I bolded the word(board), should it say square instead? 
From the docs:

The handleClick(0) call will be a part of rendering the board component. Because handleClick(0) alters the state of the board component by calling setSquares, your entire board component will be re-rendered again. But handleClick(0) is now a part of rendering of the **board** component, and so you’ve created an infinite loop:

Screenshot: 

<img width="941" alt="Screenshot 2023-02-10 at 1 03 34 PM" src="https://user-images.githubusercontent.com/92948164/218176666-56319959-f1ab-48f9-9b3e-3c426c9177d7.png">

**Comment by rickhanlonii** [comment]
No, if you add some logging, you'll see that handleClick is called when the `Board` component renders, _before_ it's passed to the Square component. In fact, that is the exact misunderstanding that this section of the Tutorial is trying to explain. Give it a read again and left me know if there's a way to make it more clear!
