### ISSUE TITLE
Semicolon's missing in a chapter of useState in React Docs(Beta).

### ISSUE THREAD

**Issue by mjjeon2645** [reactjs/react.dev#5625]
I think that a semicolon should be added an example of syntax of useState in the [tutorial](https://beta.reactjs.org/reference/react/useState).

now

```javascript
const [state, setState] = useState(initialState)
```

**toBe**

```javascript
const [state, setState] = useState(initialState);
```

or is there any intention of removing semicolon? 
I just found that all examples are missing a semicolon in Beta version Docs.

Actually, examples of previous version documents have a semicolon, so.

**Comment by vinaybadgujar102** [comment]
I think semicolons are avoided intentionally as semicolons are primarily optional in React.

**Comment by rickhanlonii** [comment]
These are not meant to be runnable snippets of code, but and overview of the API definition. 

This was actually fixed here: https://github.com/reactjs/react.dev/pull/5823 but I'm reverting it here: https://github.com/reactjs/react.dev/pull/6543
