### ISSUE TITLE
Broken link to Babeljs.io in beta docs

### ISSUE THREAD

**Issue by Ishwarendra** [reactjs/react.dev#5633]
- Under [Add React to Website](https://beta.reactjs.org/learn/add-react-to-a-website) (in beta version), the link to babeljs.io is redirected to older version of website (which is probably not hosted anymore).
-   <img width="400" alt="image" src="https://user-images.githubusercontent.com/75680424/221396311-68703696-6dc9-4a8c-9d8e-6382feddab9e.png">
- Instead of redirecting to [this](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=DwIwrgLhD2B2AEcDCAbAlgYwNYF4DeAFAJTw4B88EAFmgM4B0tAphAMoQCGETBe86WJgBMAXJQBOYJvAC-RGWQBQ8FfAAyaQYuAB6cFDhkgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=es2015%2Creact%2Cstage-2&prettier=false&targets=&version=7.17), you should probably redirect to https://babeljs.io/

<details>
<summary> Old link (404) screenshot </summary>
<img width="839" alt="image" src="https://user-images.githubusercontent.com/75680424/221396389-83e53d95-160c-4cf3-b40d-03a45b1590f5.png">
</details>

**Comment by harish-sethuraman** [comment]
Thanks for bring this to notice. This was likely a change on babeljs.io site itself `/en/` in the URL was removed. Thats why its throwing a 404.

**Comment by dotarjun** [comment]
Hello @harish-sethuraman. Are you still working on this issue? I would love to be assigned to this issue

**Comment by turalowski** [comment]
I guess this issue is not producible anymore (it looks already fixed) 

You can check from [here](https://react.dev/learn/add-react-to-an-existing-project)
