### ISSUE TITLE
Update <b> tags to <strong> tags to reflect current best practices

### ISSUE THREAD

**Issue by one2code** [reactjs/react.dev#5667]
I noticed that the final code example in the Passing Props to a Component section of the beta documents is using a bold tag for the titles that are rendered with the passed in props. This is a dated practice, and the current best practice is to use the strong tag instead, which I believe better adds to the more current and up-to-date spirit of the beta React docs. The update would also have to be applied to the solution as well.

**Comment by harish-sethuraman** [comment]
Im just trying to understand what you mean by dated practice. It seems like both serve their own purpose?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong#b_vs._strong

**Comment by Betselot-GA** [comment]
I have created a pull request on this issue somebody please check it.

**Comment by Betselot-GA** [comment]
> Im just trying to understand what you mean by dated practice. It seems like both serve their own purpose? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/strong#b_vs._strong

The <strong> element is for content that is of greater importance, while the <b> element is used to draw attention to text without indicating that it's more important.
