### ISSUE TITLE
[Docs] command-K navigation to useEffectEvent goes to a not found page

### ISSUE THREAD

**Issue by vincentbello** [reactjs/react.dev#5698]
![uee](https://user-images.githubusercontent.com/5473477/225739958-a69ec7f1-2e2e-4bdb-bee9-09b3ea564049.gif)

**Comment by roy9495** [comment]
I think it's due to this reason https://react.dev/reference/react/experimental_useEffectEvent

**Comment by Yukiniro** [comment]
The current document no longer has this issue, it will be searched and redirected to [experimental_useEffectEvent](https://react.dev/reference/react/experimental_useEffectEvent).
