### ISSUE TITLE
https://reactjs.org/feed.xml does not have a valid redirect, causing a 404 not found

### ISSUE THREAD

**Issue by ferrybig** [reactjs/react.dev#5709]
After the new launch of the new website, the atom feed url of the old website does not redirect to the new feed url.

I expect that https://reactjs.org/feed.xml links to the atom feed of the new website, (which my browser doesn't seem to be able to autodetect) so I can still receive update news in my feedreader

**Comment by rickhanlonii** [comment]
Thanks for reporting and sorry for the delay. 

We added an RSS feed for the new site in https://github.com/reactjs/react.dev/pull/6803, and we fixed the feed.xml link with https://github.com/reactjs/react.dev/pull/6836.
