### ISSUE TITLE
Add RSS feed for Blog

### ISSUE THREAD

**Issue by rubanero14** [reactjs/react.dev#5723]
Current link is defunct, please add new RSS feed link for React blogs #5700

**Comment by gaearon** [comment]
That's planned but a bit further out. We have some refactoring to do first.

**Comment by LiorAgami** [comment]
Can I help with the refactor?

**Comment by 0529bill** [comment]
@rubanero14 one alternative is to add React's Twitter page to the RSS reader since all the blogs will be posted on React Twitter account as well!

**Comment by stof** [comment]
@gaearon is there any progress regarding restoring the RSS feed ?

**Comment by rickhanlonii** [comment]
Closing as dupe of https://github.com/reactjs/react.dev/issues/5700, let's trace there.

**Comment by rickhanlonii** [comment]
RSS Feed is available here: https://react.dev/rss.xml
