### ISSUE TITLE
Bad link to useEffect docs page

### ISSUE THREAD

**Issue by dean-leszman** [reactjs/react.dev#5772]
[Migrating a component with lifecycle methods from a class to a function](https://react.dev/reference/react/Component#migrating-a-component-with-lifecycle-methods-from-a-class-to-a-function)

> This [useEffect](https://react.dev/api/useEffect) call is equivalent to the logic in the lifecycle methods above. If your lifecycle...

In the above document, the `useEffect` link redirects the user to [/api/useEffect](https://react.dev/api/useEffect). I believe this should be redirecting to [/reference/react/useEffect](https://react.dev/reference/react/useEffect).

**Comment by eps1lon** [comment]
Closed in https://github.com/reactjs/react.dev/pull/5773
