### ISSUE TITLE
Documentation for "standard" CRA is missing

### ISSUE THREAD

**Issue by LeopoldLerch** [reactjs/react.dev#5806]
on the page 
https://react.dev/learn/start-a-new-react-project

there are all variants of CRA with additional frameworks mentioned. However, the old "npx create-react-app" is missing/lost.

Is this intended or just overlooked?

**Comment by harish-sethuraman** [comment]
I hope this answers your question https://github.com/reactjs/react.dev/pull/5790#issuecomment-1482136288
