### ISSUE TITLE
How to import `react-dom/profiling` on React DOM 18?

### ISSUE THREAD

**Issue by FezVrasta** [reactjs/react.dev#5816]
If I do `import { createRoot } from 'react-dom/profiling'` I get `Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".`.

What's the correct way? I can't find any documentation for React 18.

**Comment by MrDBC** [comment]
In React 18, the createRoot API has been moved from _react-dom/profiling_ to _react-dom/client_. 
The correct way to import createRoot in React 18 :

>import { createRoot } from 'react-dom/client';

**Comment by FezVrasta** [comment]
That doesn't really answer my question, I need to import the profiling version of `createRoot`.

**Comment by eps1lon** [comment]
You're not supposed import from the profiling build. Instead, you should tell your build tooling to alias the build as explained in [How to use profiling in production mode for react-dom
](https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977).

This ensures that all profiling instrumentation is available throughout the tree. Then you can continue importing from `react-dom/client` (which in turn imports from `react-dom` which your bundler aliases to `react-dom/profiling`). `react-dom/client` is just a wrapper to disable deprecation warnings.

Once you need to change the aliases we'll update the instructions and add an entry to the changelog.

Unless you're saying that you already do use an alias and get that warning? If that's the case, please include a cloneable, minimal repro.

**Comment by FezVrasta** [comment]
I'm using the alias but I get the warning. I'll provide a repro ASAP

**Comment by AjaySureshPatil** [comment]
To import react-dom/profiling in React DOM 18, use the following code:

js

import { startProfiler, unstable_createRoot as createRoot } from 'react-dom/profiling';

startProfiler();

const root = createRoot(document.getElementById('root'));
root.render(<App />);

This allows you to use the new profiling feature in React DOM 18, which lets you measure the performance of your React components. Note that react-dom/profiling is an unstable API and should only be used in development environments.

**Comment by FezVrasta** [comment]
> To import react-dom/profiling in React DOM 18, use the following code:
> 
> 
> 
> js
> 
> 
> 
> import { startProfiler, unstable_createRoot as createRoot } from 'react-dom/profiling';
> 
> 
> 
> startProfiler();
> 
> 
> 
> const root = createRoot(document.getElementById('root'));
> 
> root.render(<App />);
> 
> 
> 
> This allows you to use the new profiling feature in React DOM 18, which lets you measure the performance of your React components. Note that react-dom/profiling is an unstable API and should only be used in development environments.

Where did you find this information?

**Comment by tsremarkable** [comment]
I got your point.

- In React 18, the `react-dom/profiling` module has been deprecated and createRoot is no longer exported from this module. Instead, you can use the `react-dom/test-utils` module to access the `profiling version of createRoot` in your code.

- To import the profiling version of createRoot, you can do the following:

`import { createRoot as createRootProfiling } from 'react-dom/test-utils';`
Here, we're importing the createRoot function from react-dom/test-utils and then creating an alias for it called createRootProfiling so that we can use it in our code.

I hope this helps! Let me know if you have any more questions.

**Comment by FezVrasta** [comment]
Are we really posting GPT generated answers now?

**Comment by FezVrasta** [comment]
I performed some more tests and realized the issue was the lack of a trailing $ at the end of the alias.

It should be `'react-dom$': 'react-dom/profiling'` as explained in the linked doc.

**Comment by eps1lon** [comment]
Thank you for following up! This will hopefully help other people struggling with similar issues.
