### ISSUE TITLE
Uncaught TypeError: cannot read property of null (reading 'useState')

### ISSUE THREAD

**Issue by okafohenry** [reactjs/react.dev#5824]
I'm trying to publish a reactjs component package following an awesome [tutorial](https://dev.to/alexeagleson/how-to-create-and-publish-a-react-component-library-2oe) by @alexeagleson, however when i try to test the package in another project, nothing displays and I get the following error...

![React App - Opera 3_23_2023 2_29_27 PM (2)](https://user-images.githubusercontent.com/39155798/227751415-91b34554-52d6-4c07-8ee0-b698ada7b130.png)

I have searched for solutions to no avail. What am I doing wrong and how do I get it fixed?

This is my package.json file.. and  my Component file...
```
  "name": "@okafohenry/react-custom-select",
  "version": "0.0.12",
  "description": "Custom-select: A react component library",
  "scripts": {
    "rollup": "rollup -c"
  },
  "author": "Henry Okafor",
  "license": "ISC",
  "devDependencies": {
    "@rollup/plugin-commonjs": "^24.0.1",
    "@rollup/plugin-node-resolve": "^15.0.1",
    "@rollup/plugin-typescript": "^11.0.0",
    "@types/react": "^18.0.28",
    "react": "^18.2.0",
    "rollup": "^3.20.0",
    "rollup-plugin-dts": "^5.3.0",
    "tslib": "^2.5.0",
    "typescript": "^5.0.2"
  },
  "dependencies": {
    "react-icons": "^4.8.0"
  },
  "main": "dist/cjs/index.js",
  "module": "dist/esm/index.js",
  "files": [
    "dist"
  ],
  "types": "dist/index.d.ts",
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/okafohenry"
  }
}
```

```
import React, { useState } from "react";

const CustomSelect = (props: PropsData) => {
  const [ dropdownToggle, setDropdownToggle ] = useState<boolean>(false);

   return(...)
}
```

**Comment by Soulpurr** [comment]
Try seperating import statements for react and usestate.

**Comment by Ashish-simpleCoder** [comment]
@okafohenry, You need to add the **react** as peer dependency.

**Comment by PeakReach** [comment]
> Try seperating import statements for react and usestate.

I tried this, it  didn't work.
No difference at all

> @okafohenry, You need to add the **react** as peer dependency.

Do I need to make the change in package-lock.json ? because the issue still persists

**Comment by okafohenry** [comment]
> Try seperating import statements for react and usestate.

@Soulpurr I tried this but it didn't work as well

**Comment by okafohenry** [comment]
> @okafohenry, You need to add the **react** as peer dependency.

@Ashish-simpleCoder This seemed like the most likely cause, however it didn't resolve my issue.

I also noticed that in the package-lock.json, **react** remained in the devDependency block
