### ISSUE TITLE
Old "npx create-react-app"

### ISSUE THREAD

**Issue by LeopoldLerch** [reactjs/react.dev#5830]
As in the docs of 
https://react.dev/learn/start-a-new-react-project

the old/plain version "npx create-react-app" went away in favor of framework only, and in the other docs 

https://create-react-app.dev/

it is still mentioned.

I am wondering if it will still be available and maintained?

**Comment by davbrito** [comment]
CRA is not longer the recommended way for starting a React application. You can use better options as Nextjs or Remix. And, if you want a traditional SPA approach you can go for Vite.
Check out the discussion at #5487

**Comment by tsremarkable** [comment]
Recently `Vite` consider better method than `CRA` as `Vite` uses the **`esbuild bundler`**, which is much faster than the `Webpack` used in CRA.
It's written in GO.
But it's not so bad to use CRA cause `Vite `uses modern JavaScript features that are not yet supported by all browsers.
So it's always your option to which to use for your project.
Hope these things help you.
Thank you.

**Comment by rickhanlonii** [comment]
Yeah, see #5487 for context.
