### ISSUE TITLE
Missing content in Tutorial: Tic-Tac-Toe section 

### ISSUE THREAD

**Issue by aliasgar55** [reactjs/react.dev#5854]
[https://react.dev/learn/tutorial-tic-tac-toe#declaring-a-winner](https://react.dev/learn/tutorial-tic-tac-toe#declaring-a-winner)

This section of the tutorial starts with: "Now that you show which player’s turn is next, you should also show when the game is won and there are no more turns to make."
We add the "status" line during this section of the tutorial, so we have not yet shown which player's turn is next.

I'm pretty sure this was just left over from the last version of the tutorial.

**Comment by lxmarinkovic** [comment]
Hi @aliasgar55 , does #5855 solve the issue you mentioned :D

**Comment by gaearon** [comment]
Thanks. Fixed in https://github.com/reactjs/react.dev/commit/f37ef36b070730ce8abd68860388179ed4284638.
