### ISSUE TITLE
Search in React documentation is not working

### ISSUE THREAD

**Issue by aynaitlamine** [reactjs/react.dev#5878]
I am trying to search for some specific information in the React documentation using the search bar at the top of the page, but it seems that the search functionality is not working properly.

![image](https://user-images.githubusercontent.com/70338955/229770185-914153f9-a48f-4966-9eae-ae1572be3ded.png)

**Comment by gaearon** [comment]
Fixed via https://github.com/reactjs/react.dev/commit/4d2dbadd81dd5c1f403b9ae8f1995d993bcbef1d
