### ISSUE TITLE
How can I start translating the new React documentation to Uzbek language?

### ISSUE THREAD

**Issue by 0tabek16** [reactjs/react.dev#5891]
I've translated a number of pages in old docs, but I am not sure how to translate new docs.

**Comment by 0tabek16** [comment]
ping @gaearon

**Comment by BartoszKlonowski** [comment]
Hello @0tabek16, sorry for the delayed response.
The full guide on how to start with your own translation for the React documentation can be found here:
https://github.com/reactjs/translations.react.dev?tab=readme-ov-file#starting-a-new-translation

Let me know in the comments if you have any more questions, while I will close this issue for now hoping this answers your issue.
Thank you!
