### ISSUE TITLE
Installation should come before Quick Start

### ISSUE THREAD

**Issue by w3tsa** [reactjs/react.dev#5897]
Hello, when I read the docs, I believe the Installation guidelines should come before the Quick Start in Getting Started.
![Screenshot 2023-04-08 at 1 36 37 AM](https://user-images.githubusercontent.com/49335574/230705278-ecd2c18a-9dcc-4674-a0d2-c4ce62d55dc0.png)

**Comment by gaearon** [comment]
We'd like to give an intro first since Quick Start is the landing page for this section anyway. This is intentional.
