### ISSUE TITLE
Add key to createPortal reference doc

### ISSUE THREAD

**Issue by mattrunyon** [reactjs/react.dev#5927]
The [createPortal](https://react.dev/reference/react-dom/createPortal#createportal) reference page does not mention that you can pass `key` as the 3rd param to `createPortal`. This is in both the typescript definitions and [here](https://github.com/facebook/react/blob/main/packages/react-dom/src/client/ReactDOM.js#L79) is the implementation

Reconciliation appears to be different if you pass the key to `createPortal` and not the element passed to `createPortal`. React dev tools does not seem to show the portal element, so it's not clear in dev tools if you have many sibling portals w/ the key set on the element and not the portal.

My use case where I ran into this was using a layout manager that is not React first, so the React support is kind of an afterthought. I made a change from calling `render` to `createPortal` so I could get an array of portals and render them inside my app's React tree and use contexts (`render` just creates a bunch of sibling root trees).

**Comment by gaearon** [comment]
Sure, want to add it? I think it's part of the API.

**Comment by mattrunyon** [comment]
Yep I can make a PR for it
