### ISSUE TITLE
Invalid description for `onFocus` DOM prop in the reference page

### ISSUE THREAD

**Issue by jitiendran** [reactjs/react.dev#5933]
The [common-props](https://react.dev/reference/react-dom/components/common#common-props) reference page is providing invalid description for `onFocus` DOM prop

**Actual Behaviour:**

![image](https://user-images.githubusercontent.com/61231497/232764192-c07330b4-939f-41f5-b48b-3d65830dc90f.png)

**Expected Behaviour:**

`onFocus` method is fired only when the element **receives or enters** focus not **lose** focus.

So the description should look like the following 
- onFocus: A [FocusEvent handler](https://react.dev/reference/react-dom/components/common#focusevent-handler) function. Fires when an element receives [focus](https://developer.mozilla.org/en-US/docs/Web/API/Element/focus_event). Unlike the built-in browser focus event, in React the onFocus event bubbles.

Also I can make the PR for it, if the issue is verified.

**Comment by harish-sethuraman** [comment]
@gaearon may be we should clarify this more? I see same for blur as well

>onBlur: A [FocusEvent handler](https://react.dev/reference/react-dom/components/common#focusevent-handler) function. Fires when an element `lost focus`. Unlike the built-in browser [blur](https://developer.mozilla.org/en-US/docs/Web/API/Element/blur_event) event, in React the onBlur event bubbles.

**Comment by jitiendran** [comment]
@harish-sethuraman and @gaearon to give more context on this, the descriptions are **clear** and **valid** for both `onFocus` and `onBlur` in old docs which says `onFocus` is fired on receiving focus and `onBlur` is fired on losing focus.

Refer:
- https://legacy.reactjs.org/docs/events.html#onfocus
- https://legacy.reactjs.org/docs/events.html#onblur

**Comment by jitiendran** [comment]
@harish-sethuraman and @gaearon , What is the status of this issue?

**Comment by rickhanlonii** [comment]
Fixed in https://github.com/reactjs/react.dev/pull/6168
