### ISSUE TITLE
Update the event handling "lesson" to talk about working with the actual event.

### ISSUE THREAD

**Issue by Pomax** [reactjs/react.dev#5935]
The new "learning" page for event handling over on https://react.dev/learn/responding-to-events doesn't show a single example of the event handler actually getting sent the event itself as argument, which is a bit weird when the whole point of event handling is that there's an event payload to handle, not just a signal to act on =)

There should at least be one example that has a simple input element and a button, and when you click the button, the alert says something like "you typed: <event.target.value>" so that people can be sent to that part of the learning docs when they ask questions about what they're doing wrong in their code and how to get form field values, something that is technically entirely unrelated to state and should not be held back until the state "lesson".

E.g.

```jsx
export default function ValueButton() {
  function handleClick(event) {
    alert(`You wrote ${event.target.value}!`);
  }

  return (
    <>
      <input type="text" placeholder="Write something here..." />
      <button onClick={(event) => handleClick(event)}>
        Click me
      </button>
    </>
  );
}
```

(And on that note, it would be super useful if the examples would stop using `'` and `"` as string syntax, and exclusively used backticks unless it's _crititcal_ that legacy string delimiters are used, such as for object property names)

**Comment by rickhanlonii** [comment]
This is handled in the [Reacting to Input with State](https://react.dev/learn/reacting-to-input-with-state#step-3-represent-the-state-in-memory-with-usestate) guide.

**Comment by Pomax** [comment]
In that case you'll want to address the discoverability, because that is not an obvious or intuitive place for that information, so only people who already know where it is will be able to find it.
