### ISSUE TITLE
higher-order-components.html page shows Not Found error

### ISSUE THREAD

**Issue by bikashKsingh** [reactjs/react.dev#5937]
When i tried to open the Higher Order Components in react.dev, It shown the Not Found error please fix the error.

**Comment by jitiendran** [comment]
@bikashKsingh I believe this is because the new [react.dev](https://react.dev/) is built using [next.js](https://nextjs.org/) react framework, so there won't be any html page that's why you are getting not found error.

**Comment by rickhanlonii** [comment]
Higher order components are not documented on the new site. They're not a feature of React, but a pattern that the old site happened to document. The pattern has since been replaced with hooks, which the new site documents.
