### ISSUE TITLE
Some confusion about React Development Workflow

### ISSUE THREAD

**Issue by noopn** [reactjs/react.dev#5938]
I want to debug source code,  make some change and use it in my project. so I follow [this](https://legacy.reactjs.org/docs/how-to-contribute.html#development-workflow) document.

But, when I link the build package, the require path in react-dom is "../../package/react" antd "../../package/scheduler" 

![img](https://res.cloudinary.com/practicaldev/image/fetch/s---sUcvmir--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_800/https://dev-to-uploads.s3.amazonaws.com/uploads/articles/pw7rssfr26yap2uug96x.png)

so I use yalc package and publish react , react-dom locally, then add these to my project, it can work now.

My confusion is the right way to development react? I can't find any source map in the build directory, so I still use the compiled file, how can I track the source code?

I think this development process should watch the file change, and build automatically， but I can't find  --watch option in the build command, need I run the build command every time?

 can help me

**Comment by MeenuyD** [comment]
To track the source code in a React project, you can use the source-map option when building your project. This will generate a source map file alongside the JavaScript bundle, which can be used to map the generated code back to the original source code for debugging purposes.

To enable source maps in your React project, you can modify your build script to include the --source-map option. For example, if you are using react-scripts to build your project, you can modify the build script in your package.json file to include this option:


```
"scripts": {
  "start": "react-scripts start",
  "build": "react-scripts build --source-map",
  "test": "react-scripts test",
  "eject": "react-scripts eject"
},
```
With this option enabled, when you run the build script, a source map file will be generated in your build directory alongside the JavaScript bundle. You can then use this source map file to map the generated code back to the original source code in your development environment.

Regarding the development process, you can use a tool like webpack to watch for changes in your source code and automatically rebuild your project when changes are detected. To enable this functionality, you can use the --watch option when running your build script. For example:


```
"scripts": {
  "start": "webpack --watch",
  "build": "webpack --mode=production"
}
```
With this setup, running npm start will start webpack in watch mode, which will automatically rebuild your project whenever changes are detected in your source code.

**Comment by rickhanlonii** [comment]
> My confusion is the right way to development react? I can't find any source map in the build directory, so I still use the compiled file, how can I track the source code?

Yeah, this is what I do. But when making changes, I will generally depend heavily on tests, and not running in an app. There's more info on the dev workflow here: https://legacy.reactjs.org/docs/how-to-contribute.html#development-workflow
