### ISSUE TITLE
`/server-components` page doesn't exists

### ISSUE THREAD

**Issue by bayraak** [reactjs/react.dev#5939]
https://react.dev/server-components

Google Search Result:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/10470072/233072781-abad5c56-78dd-42c4-bd05-71916b6ad43b.png">

Not found:

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/10470072/233072855-f392d364-642f-432d-8430-8eb815954ee0.png">

**Comment by A7med3bdulBaset** [comment]
https://react.dev/blog/2020/12/21/data-fetching-with-react-server-components

**Comment by rickhanlonii** [comment]
I think this is out of the google cache now, so i'm going to close this.
