### ISSUE TITLE
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 41125

### ISSUE THREAD

**Issue by TheUniParse** [reactjs/react.dev#5942]
first I cloned the repo
then I installed dependencies: <code>yarn</code>
then I run: <code>yarn build</code>
then I run: <code>yarn start</code>

on the browser: <i>localhost:3000</i>
at first 500ms I see everything rendered okey
until this message come: <q>Application error: a client-side exception has occurred (see the browser console for more information).</q>

then I opened <i>devTools</i>, and find this error:
<pre>
<code>
caught (in promise) Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 41125
    at Object.set [as exports] (webpack-4ba151938e0c3c84.js:1:2346)
    at 41125 (972.3cd34e2ed9aace2c.js:1:7618)
    at n (webpack-4ba151938e0c3c84.js:1:149)
    at 42202 (972.3cd34e2ed9aace2c.js:1:6831)
    at n (webpack-4ba151938e0c3c84.js:1:149)
    at 67033 (972.3cd34e2ed9aace2c.js:1:1759)
    at Function.n (webpack-4ba151938e0c3c84.js:1:149)
</code>
</pre>

am using node v19.6.1, on windows11 22H2

**Comment by samdenty** [comment]
![image](https://user-images.githubusercontent.com/13242392/235243429-552fe9b3-e923-42a5-abdb-fd6ada79b034.png)

**Comment by TheUniParse** [comment]
I think the problem was on my end,
I was using unofficial windows11, caused false positive in windows defender firewall.
