### ISSUE TITLE
useRef clarification

### ISSUE THREAD

**Issue by qweered** [reactjs/react.dev#5964]
Please explicitly state in documentation that useRef hook must have initial value.

https://react.dev/reference/react/useRef

**Comment by mohammad-taheri1** [comment]
It is stated:

```
import { useRef } from 'react';

function MyComponent() {
  const intervalRef = useRef(0);
  const inputRef = useRef(null);
  // ...
```
Why explicitly state it?

**Comment by mohammad-taheri1** [comment]
## Parameters 
- `initialValue`: The value you want the ref object’s current property to be initially. It can be a value of any type. This argument is ignored after the initial render.

## Returns 
`useRef` returns an object with a single property:

- `current`: Initially, it’s set to the `initialValue` you have passed. You can later set it to something else. If you pass the ref object to React as a `ref` attribute to a JSX node, React will set its `current` property.

**Comment by MeenuyD** [comment]
yes, it is stated in the documentation the useRef hook will return the object like
`ref={current:intialValue}`
which we can use as the 
`ref.current=something`

**Comment by rickhanlonii** [comment]
Yeah as others mention, it's listed in the reference.
