### ISSUE TITLE
Wrong link or page doesn't exist  https://beta.reactjs.org/apis/react/useReducer#usereducer 

### ISSUE THREAD

**Issue by oladee** [reactjs/react.dev#5966]
I got the above link from the meta course on coursera as a link to an additional reading _**Syntax and usage of useReducer hook**_ which redirected me to the react.dev website but it seems the page doesn't exist or has been deleted or something 
![image](https://user-images.githubusercontent.com/56429751/234853952-6d763cee-020e-43f8-9f9f-6285cd69d081.png)

**Comment by gaearon** [comment]
Is there any way to report a problem directly in the course?

**Comment by gaearon** [comment]
Yeah we've removed some of the older redirects that only affected the beta site since there weren't _that_ many links to it. Let's just close this and have them fix it upstream.
