### ISSUE TITLE
Linking to Create-React-App in new docs

### ISSUE THREAD

**Issue by hannanel100** [reactjs/react.dev#5985]
Create-React-App was removed from the Start a New React Page section as a recommendation for starting new projects, but still appears in examples in Your First Component and in Importing and Exporting Components. To me it seems a bit disconnected, was this done on purpose? Did I miss anything?

**Comment by ethan-luxton** [comment]
Looks like it was moved to [Start a New React Project](https://react.dev/learn/start-a-new-react-project)

**Comment by hannanel100** [comment]
> Looks like it was moved to [Start a New React Project](https://react.dev/learn/start-a-new-react-project)

what was moved? my issue wasn't with the removal of create-react-app from [Start a New React Project](https://react.dev/learn/start-a-new-react-project), but with the fact that the references still exist in: [Your First Component](https://react.dev/learn/your-first-component) and in [Importing and Exporting Components](https://react.dev/learn/importing-and-exporting-components). 

In my opinion, for someone just going over the docs for the first time learning React, that could be unnecessarily confusing.

**Comment by ethan-luxton** [comment]
@hannanel100 Yeah I agree it could be confusing for first time users. I sent in a PR to add a note at the top level of both those pages directing new users to [Start a New React Project](https://react.dev/learn/start-a-new-react-project) before starting with components.

It looks like so:

![image](https://user-images.githubusercontent.com/105515311/235945779-bc5e2d32-af02-472e-88ee-4f8398d1cf1c.png)

**Comment by hannanel100** [comment]
I actually prefer to remove these references all together. I've opened a PR for that #6012

**Comment by rickhanlonii** [comment]
Merged the above PR. I think those docs pre-date the new guidance, so we just missed updating those pages. 

Thanks @hannanel100!
