### ISSUE TITLE
hey guys i would like to help with translating the new docs to urdu can you tell me how can i do that

### ISSUE THREAD

**Issue by MehfoozurRehman** [reactjs/react.dev#5986]

**Comment by M0nica** [comment]
If you are interested in maintaining a translation, follow the instructions at [translations.react.dev](https://github.com/reactjs/translations.react.dev). It has more information on next steps: https://github.com/reactjs/translations.react.dev#starting-a-new-translation

**Comment by rickhanlonii** [comment]
cc @mattcarrollcode
