### ISSUE TITLE
https://react.dev/learn becomes unresponsive after reading for 10 minutes

### ISSUE THREAD

**Issue by atharvashukla** [reactjs/react.dev#5988]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/33644308/235913096-ccfb0573-98d6-4d60-a44f-781f523cf623.png">

I could not collect any other information.

**Comment by gaearon** [comment]
Does this happen consistently for you?

**Comment by atharvashukla** [comment]
Although it did happen consistently at the time. I wasn't able to reproduce the issue. I think it had something to do with my system state at the time and not the docs. Closing the issue. Thanks!
