### ISSUE TITLE
Code in documents does not work

### ISSUE THREAD

**Issue by CaledoniaProject** [reactjs/react.dev#5991]
https://redux.js.org/introduction/getting-started#create-a-react-redux-app

It says I can create a react example project using

```
npx degit reduxjs/redux-templates/packages/vite-template-redux my-app
```

I executed that command with homebrew nodejs 16.X, and the my-app folder is not even created.

**Comment by gaearon** [comment]
Redux has no relation to React. Please report this to Redux.

**Comment by CaledoniaProject** [comment]
Understood.
