### ISSUE TITLE
Can we add a `language dropdown` to the Header?

### ISSUE THREAD

**Issue by shezhangzhang** [reactjs/react.dev#5994]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/26793777/236098844-605ba1b5-4d67-48ca-ab60-59ece54c2577.png">

I can not find a `different language version` link directly. Can we add it to the Header like this:

<img width="249" alt="image" src="https://user-images.githubusercontent.com/26793777/236098681-a8884b22-106e-4e51-a1c8-c68cb38da52c.png">

**Comment by shezhangzhang** [comment]
Thanks, and I'm working on the Simplified Chinese version!

**Comment by rickhanlonii** [comment]
Yeah once there's more progress on the translations let's add a way to get to them somewhere.

**Comment by shezhangzhang** [comment]
wait, where is the `Simplified Chinese` in this dashboard? https://translations.react.dev/
