### ISSUE TITLE
There is a typo issue on refernce page

### ISSUE THREAD

**Issue by Native-dev-afk** [reactjs/react.dev#6008]
https://react.dev/reference/react-dom/components/common#reference here you can find 

<img width="857" alt="Screenshot 2023-05-07 at 17 30 13" src="https://user-images.githubusercontent.com/84078673/236677899-8203ca92-0830-43e8-9add-7603178d19a3.png">

**Comment by rickhanlonii** [comment]
Fixed by https://github.com/reactjs/react.dev/pull/6167
