### ISSUE TITLE
Not Found This page doesn’t exist.

### ISSUE THREAD

**Issue by rakshithcgowda** [reactjs/react.dev#6030]
![Screenshot (43)](https://github.com/reactjs/react.dev/assets/107578353/53d8dbe6-c7d6-4f6d-8a57-8d124b7080b1)

showing the page https://react.dev/server-components

**Comment by rakshithcgowda** [comment]
But if you search through url is showing like this

**Comment by j4acks0n** [comment]
> what happened it i give command in terminal "yarn dev" its not running can please help . Just keep buffering. ![Screenshot (45)](https://user-images.githubusercontent.com/107578353/238447572-55da5fc8-b596-4bf7-ba7d-7efc729a3b06.png)

Have you tried:

Fill the licenses fields in the package.json file of your project as you find suitable? Or You can also use the “preformatted text” tool in the editor (</>) to add backticks around text?

**Comment by j4acks0n** [comment]
> what happened it i give command in terminal "yarn dev" its not running can please help . Just keep buffering. ![Screenshot (45)](https://user-images.githubusercontent.com/107578353/238447572-55da5fc8-b596-4bf7-ba7d-7efc729a3b06.png)

And I Think Your Setup Is Wrong Maybe You Can Try This One
{
	"name": "fcc-learn-npm-package-json",
	"author": "Jack",
	"description": "First Node.js Folders",
	"licence": "UNLICENSED",
	"keywords": [
		"first",
		"freecodecamp"
	],
	"version": "1.0.0",
	"dependencies": {
		"express": "^4.14.0"
	},
	"main": "server.js",
	"scripts": {
		"start": "node server.js"
	},
	"repository": {
		"type": "git",
		"url": "https://idontknow/todo.git"
	}
}

**Comment by rakshithcgowda** [comment]
In the place of package.json file

**Comment by j4acks0n** [comment]
Just Create New Package.Json And Delete Old One Then You Can Try Paste This One
{
	"name": "fcc-learn-npm-package-json",
	"author": "Jack",
	"description": "this is my first Node.js Folder ",
	"licence": "UNLICENSED",
	"keywords": [
		"first",
		"Youtube"
	],
	"version": "1.0.0",
	"dependencies": {
		"express": "^4.14.0"
	},
	"main": "server.js",
	"scripts": {
		"start": "node server.js"
	},
	"repository": {
		"type": "git",
		"url": "https://idontknow/todo.git"
	}
}

**Comment by j4acks0n** [comment]
> @rakshithcgowda Where did you find this link? I don't think we use that link anywhere. The old https://reactjs.org/server-components link should still work and redirect to the right place.

IDK It's Little Bit Confusing🤣😂,Maybe He Try to find Package/Libary And We Don't Know Right He Is Using React Js Or React Native 
Can It Be Crossover?

**Comment by rakshithcgowda** [comment]
Hooo
