### ISSUE TITLE
Adding Toggle Sidebar button.

### ISSUE THREAD

**Issue by itse4elhaam** [reactjs/react.dev#6035]
I've been using the React website (react.dev) to learn more about React and I have noticed that the sidebar on the left-hand side stays permanently fixed in place, even when scrolling through the content on the site.

I believe that this is not the best user experience, as it takes up valuable screen real estate and can be distracting when reading through the content on the site. **I think that it would be better to have a button to toggle the sidebar** : hide when users are reading articles or tutorials on the site, this will make sure readers can read in a more distraction free environment.

I would like to suggest that the React team consider removing the permanent sidebar from the site, and implementing a design that allows users to easily hide or collapse the sidebar when they need more space to read or focus on the content.

Thank you for considering my suggestion.

**Comment by gkprasanth** [comment]
Salut, @itse4elhaam I am a new react developer,. Can I work on this issue? Considering that doing this can help me in my learning process.

**Comment by gkprasanth** [comment]
> Yes sure go ahead, but please check out with the current devs already working on this issue. I think there are a couple of them.
> 
> Also, I'm not from react.dev team. I'm also a developer like you who raised this issue.

Alright then I would really like to work on this. And btw how do I find people who are working on the same issue?

**Comment by rickhanlonii** [comment]
Unfortunately the site it designed so that the sidebar is always open when the window width is large enough. The content column is optimized for readability with a max width anyway, so even if it collapsed the content wouldn't expand much, if at all.
