### ISSUE TITLE
Indicating the use cases of `Context.Consumer` in the documentation.

### ISSUE THREAD

**Issue by xxwwp** [reactjs/react.dev#6037]
The official documentation no longer recommends the use of `Context.Consumer`. However, it is very useful in the `renderProps` function because users cannot use `useContext` to access the context within `renderProps`.

**Comment by MeenuyD** [comment]
If you find yourself needing to access context within a render prop function and useContext is not suitable, you might consider using the contextType property or the static contextType syntax. These approaches allow you to access context directly within the class component, without the need for Context.Consumer.

**Comment by rickhanlonii** [comment]
If you're using a render prop you can read the context with `useContext` in the parent or in the component defining the render prop and pass it through so Context.Consumer is not needed for render props.
