### ISSUE TITLE
The usage of IntersectionObserver API on useEffect reference page

### ISSUE THREAD

**Issue by Jeffzholy** [reactjs/react.dev#6049]
The question is about the third example of [Examples of wrapping Effects in custom Hooks](https://react.dev/reference/react/useEffect#examples-custom-hooks), **useIntersectionObserver.js** file line 12-14. As I found on MDN, the standard way of using Intersection API is put options as the Intersection constructor's second parameter instead of putting it into the `observe` function as the second parameter. thanks

**Comment by Studio384** [comment]
The demo is indeed broken. The second parameter given to `observe()` does nothing. When a blue square comes into the viewport, the colors switch instantly and does not wait until its 100% in the viewport (as `threshold: 1.0` implies).
