### ISSUE TITLE
Why `cloneElement` is introduced in Legacy react APIs?

### ISSUE THREAD

**Issue by euijinkk** [reactjs/react.dev#6057]
Hi !
I'm wonder why `cloneElement` is introduced in Legacy react APIs.

According to react.dev docs, it states that "Legacy react APIs are not recommended for use in newly written code." and recommands using alternatives.
However I believe `cloneElement` can not be replaced, and it is not Legacy APIs.
Therefore, I would like to ask why it is categorized as a legacy React API.

The reason why I think it cannot be replaced is demonstrated in the following code example:

```jsx
function LogOnClick({ children, ...props }) {
  return cloneElement(children, {...props, onClick(...args) {
    log();
    return children.props['onClick']?.(...args)
  }})
}

// use case
<LogOnClick>
  <button onClick={() => {}}>
    Click
  </button>
</LogOnClick>
```

react.dev docs recommands three alternatives for `cloneElement`
1. Passing data with a render prop 
2. Passing data through context 
3. Extracting logic into a custom Hook

However, these alternatives are not as straightforward to use as `cloneElement`.
While `LogOnClick` utilizing `cloneElement` is very declarative and can handle the logging function internally, the alternatives require additional implementation for logging. 

Therefore, I believe cloneElement is not Legacy APIs.
I am curious about the intentions of the React team.

**Comment by rickhanlonii** [comment]
Cloning children makes it hard to tell how the data flows through your app. In the example code provided, finding where the `log()` is being called can be difficult, unexpected, and fragile to refactoring. 

For the example provided, you can use composition instead:

```js
function Button({onClick, children}) {
  return (
    <button onClick={() => {}}>
      {children}
    </button>
  );
}

function ButtonLogOnClick({ onClick, children }) {
  return (
    <Button onClick={e => { 
      log();
      onClick(e)
    }}>{children}</Button>
  );
}

// use case
<ButtonLogOnClick onClick={() => {}}>
  Click
</ButtonLogOnClick>
```

**Comment by gaearon** [comment]
`StyledBox` is the problematic API here — a component is generally not expected to be able to alter the DOM output of its children. So the assumption that this _should_ be possible is the problem here. Add a new DOM element around the link if needed.
