### ISSUE TITLE
Why does the external `useSyncExternalStore` offer `useSyncExternalStoreWithSelector`

### ISSUE THREAD

**Issue by MattyBalaam** [reactjs/react.dev#6064]
I am intereested why the `useSyncExternalStore` hook in React 18 does not also have the `useSyncExternalStoreWithSelector` hook available in the `use-sync-external-store` packages.

The only valid reason I can think is that React 18 does some automatic work here? Or has it just been missed off?

**Comment by rickhanlonii** [comment]
Since `useSyncExternalStoreWithSelector` can be done in user-land, it is not a part of core and is provided in this package. We provided it to make it easier to adopt `useSyncExternalStore` with React 18, but do not plan on adding it to core.
