### ISSUE TITLE
Add local storage for code in sandbox

### ISSUE THREAD

**Issue by gregoryamaefule** [reactjs/react.dev#6068]
if I leave the page while coding and return later to continue, I find out that my earlier code has been cleared.
I suggest you add the ability for code in the sandbox to be stored in local storage so each user can access their code anytime

**Comment by vpsone** [comment]
If you want to save your changes then you can fork the sandbox. It will save changes in your Codesandbox account.

**Comment by rickhanlonii** [comment]
Yeah, as @vpsone said, to save your changes fork the sandbox. Using local storage would quickly hit the storage limit.
