### ISSUE TITLE
Clarification needed for translation: Unlike an object which gets re-created

### ISSUE THREAD

**Issue by mekarthedev** [reactjs/react.dev#6072]
Hi! I'm doing translation and having trouble interpreting a sentence.

https://react.dev/reference/react/useEffect#removing-unnecessary-object-dependencies — at the end of example there is this sentence:

> ... Unlike an object which gets re-created, a string like roomId doesn’t change unless you set it to another value.

Which of the following is the correct interpretation?

Option A: "In general, strings are compared by value, not by reference, unlike objects."
Option B: "In this specific example, `roomId` is not re-created during re-renders, unlike an object was before fix."

**Comment by TechSpiritSS** [comment]
Option B: "In this specific example, roomId is not re-created during re-renders, unlike an object was before the fix." 

The statement is referring to a specific scenario where the roomId string is not being re-created during re-renders, unlike an object that was re-created. This suggests that the roomId variable holds the same string value across re-renders unless explicitly set to another value.

**Comment by rickhanlonii** [comment]
It's kind of both. In this specific example, `roomId` is not re-created during re-renders, because in JavaScript two strings with the same value are equal, unlike objects, which can be different even if they contain the same values."
