### ISSUE TITLE
Page Not Found

### ISSUE THREAD

**Issue by WuzhouDu** [reactjs/react.dev#6085]
The question 'why the code will not run' of the 4th challenge of https://zh-hans.react.dev/learn/state-a-components-memory#challenges is not found. 

The missing page is https://zh-hans.react.dev/learn/troubleshooting-state-updates#setting-state-does-not-update-variables.

**Comment by A7med3bdulBaset** [comment]
I fixed it in a [PR](https://github.com/reactjs/zh-hans.react.dev/pull/1190)

**Comment by awxiaoxian2020** [comment]
The issue can be closed :)

**Comment by WuzhouDu** [comment]
Thanks
