### ISSUE TITLE
Explain useEffect and useMemo with empty array at dependencies

### ISSUE THREAD

**Issue by NJM-Goals** [reactjs/react.dev#6101]
useEffect and useMemo accept an empty array for the dependencies. Mention this in the reference documentation and explain what it does.

Mention it at the following places?
- https://react.dev/reference/react#effect-hooks
- https://react.dev/reference/react/useEffect
- https://react.dev/reference/react/useMemo#usememo

At useEffect the encapsulated function is executed only once on mount. (But after a first render?)

At useEffect the encapsulated function is executed only once. Is it run before first render?
Is the explanation at https://stackoverflow.com/a/73029812 correct?

**Comment by rickhanlonii** [comment]
`useEffect` and `useMemo` only accept an empty array if there are no reactive value inside the scope. It is not something you "choose" to do, it's a result of not having dependencies to list. For useMemo in particular, this is very uncommon.

So when the docs for the `dependencies` parameter says it's "the list of all reactive values referenced inside of the setup code" that is correct. And if there are no dependencies, then it can be empty. But it's not an option to pass it empty if there are reactive values in the effect. The useEffect reference links to the docs that explain the difference between passing an array of dependencies, an empty array, and no dependencies at all: https://react.dev/reference/react/useEffect#parameters

> Is the explanation at https://stackoverflow.com/a/73029812 correct?

No, `useMemo` should not be used to call functions as this is a side-effect in render and breaks the rules of React.
