### ISSUE TITLE
Bad grammar in react.dev tictactoe documentation.

### ISSUE THREAD

**Issue by Vinqueire** [reactjs/react.dev#6104]
I know this is very minor, but I'm just starting to learn react and I've noticed that on the [tictactoe](https://react.dev/learn/tutorial-tic-tac-toe) site there's bad grammar near the section about:

 "<Square value={squares[0]} onSquareClick={handleClick(0)} />
Here is why this doesn’t work. The handleClick(0) call will be a part of rendering the board component. Because handleClick(0) alters the state of the board component by calling setSquares, your entire board component will be re-rendered again. But this runs handleClick(0) again, leading to an infinite loop:```

Console
Too many re-renders. React limits the number of renders to prevent an infinite loop."

Under that's there's a text that says "You could fix by creating a function like handleFirstSquareClick that calls handleClick(0)" 

And honestly saying "You could fix by creating a function..." doesn't sound too good. It should instead be something like:

"You could fix THIS by creating a function like..." 

I know this is a very small issue but I still wanted to point it out ^^

![image_2023-06-19_131814532](https://github.com/reactjs/react.dev/assets/117796287/08a62697-bd4e-407c-986c-1940436cec91)

**Comment by DIWAKARKASHYAP** [comment]
ok , i will correct this

**Comment by DIWAKARKASHYAP** [comment]
@Vinqueire please check this #6126

**Comment by rickhanlonii** [comment]
Makes sense, merged the fix!
