### ISSUE TITLE
an error in the tutorial of  Extracting State Logic into a Reducer

### ISSUE THREAD

**Issue by okssq** [reactjs/react.dev#6129]
[Challenge 1 of 4: Dispatch actions from event handlers ](https://react.dev/learn/extracting-state-logic-into-a-reducer#challenges)

I use hint ，the code is
```
case 'changed_selection': {
  return {
    ...state,
    **selectedId**: action.contactId
  };
}
```
The correct code should be
```
case 'changed_selection': {
  return {
    ...state,
    **contactId**: action.contactId
  };
}
```

**Comment by Aqirlone1** [comment]
i will fix this

**Comment by rickhanlonii** [comment]
I think I see the confusion, but the hint is correct. 

In `messengerReducer.js` you can see the relevant code that the hint is taken from:

<img width="464" alt="Screenshot 2023-08-10 at 8 00 57 PM" src="https://github.com/reactjs/react.dev/assets/2440089/78a61c6c-9da4-4c10-84a1-50827a87dcd5">

The reducer takes a `contactId` from the action and sets that contact ID as the `selectedId` in state. This can be verified by applying your suggested changes to the solution and seeing that the example does not work.

The way to read this code is "dispatch an action (`changed_selection`) to set the selected contact ID (`selectedId`) to the given contact ID (`action.contactId`)".
