### ISSUE TITLE
create-react-app is not present in documentation

### ISSUE THREAD

**Issue by DIWAKARKASHYAP** [reactjs/react.dev#6143]
Newcomers often find it challenging to create a new React app, making the process more difficult. Simplifying dependency installation would greatly benefit novice developers.
![image](https://github.com/reactjs/react.dev/assets/94478026/4e8f6046-3dfb-4315-992a-ac96991404fc)

**Comment by A7med3bdulBaset** [comment]
See the discussion on #5487

**Comment by itse4elhaam** [comment]
I think it would be better to add a guide to set it up with vite or something likewise, I found it very easy in my early days.

**Comment by rickhanlonii** [comment]
See https://github.com/reactjs/react.dev/pull/5487 for context on the decision.
