### ISSUE TITLE
Suspense usage section: shouldn't it say "client-only content" instead of "server-only"?

### ISSUE THREAD

**Issue by tdd** [reactjs/react.dev#6157]
Hey there!

In the process of translating the `<Suspense>` reference page to French, I got doubts about [that heading](https://react.dev/reference/react/Suspense#providing-a-fallback-for-server-errors-and-server-only-content):

**Providing a fallback for server errors and server-only content**

The section does cover providing a fallback for errors on the server side (as these areas might render correctly client-side) and then goes on to say:

> You can use this to opt out some components from rendering on the server

And indeed, it explains how to piggyback on server error fallbacks to make components that only render client-side. Seems like **_client-onky content_** to me, not **server-only** content.

What do you think?

**Comment by rickhanlonii** [comment]
Fixed in https://github.com/reactjs/react.dev/pull/6164, thanks!
