### ISSUE TITLE
Some of the IDs specified in the MDN page URLs are incorrect.

### ISSUE THREAD

**Issue by natsuokawai** [reactjs/react.dev#6175]
In the react-dom/components page, some of the MDN page URLs specify IDs.

example: https://react.dev/reference/react-dom/components/progress#:~:text=supports%20these%20props%3A-,max,-%3A%20A%20number.%20Specifies

These all specify an ID such as `#attr-max`, but you don't actually need the `attr-` prefix, you can refer to it by `max`.

incorrect: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress#attr-max
correct: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/progress#max

**Comment by rickhanlonii** [comment]
Neither of these IDs work for me?

**Comment by natsuokawai** [comment]
@rickhanlonii
Thank you.

I checked the HTML and the ID is correct.
<img width="screenshot" src="https://github.com/reactjs/react.dev/assets/25678257/b9342150-e15b-4fee-b91a-32b7ed6002c9">

It worked with Safari, but may not work with Chrome.

**Comment by rickhanlonii** [comment]
Nice ok merged!
