### ISSUE TITLE
Under “Escape Hatches > Synchronizing with Effects”, “React verifies that navigating away and back would not break your code” is confusing

### ISSUE THREAD

**Issue by chulman444** [reactjs/react.dev#6180]
From: https://react.dev/learn/synchronizing-with-effects#step-3-add-cleanup-if-needed

> Imagine the ChatRoom component is a part of a larger app with many different screens. The user starts their journey on the ChatRoom page. The component mounts and calls connection.connect(). Then imagine the user navigates to another screen—for example, to the Settings page. The ChatRoom component unmounts. Finally, the user clicks Back and ChatRoom mounts again. This would set up a second connection—but the first connection was never destroyed! As the user navigates across the app, the connections would keep piling up.
> 

> By remounting your component, React verifies that navigating away and back would not break your code. Disconnecting and then connecting again is exactly what should happen! [...] There’s an extra connect/disconnect call pair because React is probing your code for bugs in development.
> 

So in “simple” React apps where every page has their own html file, and you have “myapp.com/chat” with chat connection and “myapp.com/timeline”, navigating from “/chat” to “/timeline” then back to “/chat” won’t give you two connections.

So, I don’t understand why the documentation is talking about page navigation.

One case that I can think of where you could have two connections would be SPA where changing url doesn’t make a new HTTP for that url, and url and its history is modified with browser History API and React renders the page accordingly.

It seems like React-native uses React-navigation and “browser” React has react-router. And in this case `StrictMode` will prevent the bugs that the documentation is talking about.

But I still don’t think using page navigation as an example in the doc is useful without mentioning tools where page navigation actually could introduce those bugs.

If I were to advocate an argument like “Using `StrictMode` is a good practice anyways”, it’s because (1) you could be updating your “simple” React app to use react-router in the future, and when that happens, the bugs are already prevented (2) you think that “/chat” page is too simple and decided to make it a small component in a corner of the main page that can close and open. And when that happens you want to cleanup when the chat closes. (3) If making a request in `useEffect` is annoying you, you should consider preloading or caching the data, then using `StrictMode` should no longer annoy you.

But again, I would never talk about “`StrictMode` prevents bugs that can happen when navigating away and back” because in an app where each page is served from their own html file, navigating away and back would not break your code anyways. This page doesn’t mention react-native at all, and react-router is only used in the context of “client-side cache” library.

**Comment by rickhanlonii** [comment]
Browser navigation is just an example that's intended to be relatable even though specific app structures may not hit that particular bug. Another example, using "navigation" but not browser navigation would be an in-app tab bar where you navigate different tabs, or an in-app modal that navigates to different chats and opens them.

In either case, when you change tabs, or open/close the modal, the same issue is present - you'll need to ensure that the connections are disconnected on unmount so you don't leak connections, and StrictMode helps you find those issues.
