### ISSUE TITLE
Constantly flashing output screen in challenge

### ISSUE THREAD

**Issue by fransan6** [reactjs/react.dev#6185]
For [Challenge 3](https://react.dev/learn/passing-props-to-a-component#challenges) ('Passing JSX in a `children` prop') in **Describing the UI** -> **Passing Props to a Component**, the width of the 'About' box is constantly flashing and changing size, in both the initial showing of the challenge and in the solution. Note I use Brave but tested this on Chrome as well and the issue persists.

I am not familiar with Tailwind CSS but removing `w-full` from the below in the browser fixed the issue for me.

```html
<iframe class="rounded-t-none bg-white md:shadow-md sm:rounded-lg w-full max-w-full transition-opacity opacity-100 duration-150" title="Sandbox Preview" style="height: 433px; z-index: -1;" sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"></iframe>
```

Please find attached a video that displays the error on my screen.

https://github.com/reactjs/react.dev/assets/114738789/448e12ff-ff2b-4064-8d40-4656e1b574e2

**Comment by saycty** [comment]
yes, in this w-full is taken the whole container that's why the box constantly flashes and changes size. or Using multiple CSS frameworks or libraries with Tailwind CSS may cause conflicts. Try disabling that.

**Comment by santoshy1101** [comment]
fransan6, can you assign this task for me

**Comment by fransan6** [comment]
> fransan6, can you assign this task for me

I believe only admin can assign tasks so I can't assign it.

**Comment by Afrin127329** [comment]
Also check with a console log in the card element, another cause can be the element is re-rendering

**Comment by rickhanlonii** [comment]
I'm not able to repro - if you have a fix please feel free to push a PR!

**Comment by myselfprincee** [comment]
Hi, is this issue solved ?? I didn't found any problems. in Firefox as well as in Brave.
**SEE THIS 👇**
https://github.com/reactjs/react.dev/assets/114233864/7d640e50-4c68-4c4c-b9b2-67058cae011c

**Comment by fransan6** [comment]
> Hi, is this issue solved ?? I didn't found any problems. in Firefox as well as in Brave. **SEE THIS 👇** https://github.com/reactjs/react.dev/assets/114233864/7d640e50-4c68-4c4c-b9b2-67058cae011c

I've just had a look as well and no more flashing.. so I will close this issue; thank you for checking and updating.

**Comment by fransan6** [comment]
Closing as issue no longer present

**Comment by myselfprincee** [comment]
Yeah, It's Great. 😁

**Comment by myselfprincee** [comment]
> > Hi, is this issue solved ?? I didn't found any problems. in Firefox as well as in Brave. **SEE THIS 👇** https://github.com/reactjs/react.dev/assets/114233864/7d640e50-4c68-4c4c-b9b2-67058cae011c
> 
> I've just had a look as well and no more flashing.. so I will close this issue; thank you for checking and updating.

**You're Welcome.**
