### ISSUE TITLE
Confusing wording in the tutorial

### ISSUE THREAD

**Issue by seishun** [reactjs/react.dev#6196]
From https://react.dev/learn/tutorial-tic-tac-toe#showing-the-past-moves:

>You already have an array of history moves in state, so now you need to transform it to an array of React elements.

What's a history move?

**Comment by A7med3bdulBaset** [comment]
The term 'history move' in this tutorial refers to the state of the game at a specific point in time. When you first start the game, the 'moves' are represented as an array of 9 nulls, indicating no occurrences of either 'X' or 'O':
```js
[
  [null, null, null, null, null, null, null, null, null],
]
```
As players make their moves, the 'history' array gets updated to store each state of the game. For example, if the first player with the 'X' role clicks the first button, the 'history' array will look like this:```js
[
  // The first history move
  [null, null, null, null, null, null, null, null, null],
  // The second history move
  ["X", null, null, null, null, null, null, null, null],
  // and so on...
]
```
`"You have already an array of history moves in state"` means this:
```jsx
export default function Game() {
  const [xIsNext, setXIsNext] = useState(true);
  // This is the array of history moves initialized with 9 nulls, and it is mutated every time a player makes a move
  const [history, setHistory] = useState([Array(9).fill(null)]);
  // ...
```

**Comment by rickhanlonii** [comment]
Awesome explanation @A7med3bdulBaset

**Comment by seishun** [comment]
The term "history move" isn't used anywhere else in the tutorial and it sounds strange.
