### ISSUE TITLE
App Router is no longer in beta

### ISSUE THREAD

**Issue by nbgraham** [reactjs/react.dev#6201]
The react documentation states
>Next.js’s App Router is currently in beta and is not yet recommended for production (as of Mar 2023). To experiment with it in an existing Next.js project, [follow this incremental migration guide](https://beta.nextjs.org/docs/upgrade-guide#migrating-from-pages-to-app).

The App Router is no longer in beta (https://nextjs.org/blog/next-13-4). Is it recommended to be used now?

**Comment by A7med3bdulBaset** [comment]
This should be fixed by either https://github.com/reactjs/react.dev/pull/6005 or
https://github.com/reactjs/react.dev/pull/6090

**Comment by nickmccurdy** [comment]
See #6005 (other was closed as duplicate)

**Comment by nbgraham** [comment]
Duplicate of #6005

**Comment by nbgraham** [comment]
Duplicate of #6005
