### ISSUE TITLE
Recipes seems to be used incorrectly 

### ISSUE THREAD

**Issue by MoonsummerP** [reactjs/react.dev#6202]
On the useContext, forwardRef page, the Recipes component's props are title, shouldn't you change this to titleText and add a titleId?

https://github.com/reactjs/react.dev/blob/a472775b7c15f41b21865db1698113ca49ca95c4/src/content/reference/react/useContext.md?plain=1#L1081

https://github.com/reactjs/react.dev/blob/a472775b7c15f41b21865db1698113ca49ca95c4/src/content/reference/react/forwardRef.md?plain=1#L138

**Comment by rickhanlonii** [comment]
Nice catch, I pushed a fix
