### ISSUE TITLE
Not Found, This page doesn’t exist

### ISSUE THREAD

**Issue by MasonUSA** [reactjs/react.dev#6204]
Hi there,

The following link on your website shows "Not Found, This page doesn’t exist.".

It's a link from additional resources on your Meta Front-End Developer Certificate on Coursera on "Rules of Hooks and Fetching Data with Hooks, week 2 of Advanced React" as well.

https://react.dev/apis/react/useEffect#fetching-data-with-effects

**Comment by Afrin127329** [comment]
Hi, Mason. I don't think the link exists actually

**Comment by rickhanlonii** [comment]
At one point during the we used `/apis` route but it was changed to `/reference` before release, so the correct link is https://react.dev/reference/react/useEffect#fetching-data-with-effects. The reference will need to be updated from the source. on the Coursea page (which the React team doesn't own/manage).
