### ISSUE TITLE
Day 3 newbie found `learn/sharing-state-between-components` confusing

### ISSUE THREAD

**Issue by loynoir** [reactjs/react.dev#6206]
Hi, I'm react-newbie on day 3.

When I learn [sharing-state-between-components](https://react.dev/learn/sharing-state-between-components), I got confused.

The **only** way that docs mentioned is `lifting state up`.

But, when given

- `A` have children `B`, `C`, `D`

- `B` `C` have shared data

I think

- `lifting state up` will also leads to re-entering `A` and `D`, which I think it's not necessary.

- Possible workaround with add wrapper `BC`, which have children `B` `C`, but I think it's not graceful. Maybe there is also situation not easy to add such wrapper.

- As react is popular, I believe, there should be alternative solution, which let `B` `C` share data, without re-enter `A` and `D`. 

<details>
  <summary markdown="span">reproduce</summary>

**Actual**

1. Click button from `B`, or from `C`

2. Check console

```txt
enter A
enter B
enter C
enter D
```

**Expected**

1. Click button from `B`, or from `C`

2. Check console

```txt
enter B
enter C
```

**Code**

```tsx
/* global console */
import { useState, type JSX, type MouseEventHandler } from 'react'

function A(): JSX.Element {
  console.debug('enter A')

  const [sharedBC, setSharedBC] = useState(0)
  return (
    <>
      <B count={sharedBC} onClick={() => setSharedBC(sharedBC + 1)} />
      <C count={sharedBC} onClick={() => setSharedBC(sharedBC + 1)} />
      <D />
    </>
  )
}

function B({ count, onClick }: { count: number; onClick: MouseEventHandler<HTMLButtonElement> }): JSX.Element {
  console.debug('enter B')

  return <button onClick={onClick}>Clicked {count} times</button>
}

function C({ count, onClick }: { count: number; onClick: MouseEventHandler<HTMLButtonElement> }): JSX.Element {
  console.debug('enter C')

  return <button onClick={onClick}>Clicked {count} times</button>
}

function D(): JSX.Element {
  console.debug('enter D')

  return (
    <div>
      <h1>D</h1>
    </div>
  )
}

export default A
```

</details>

Would you please describe `sharing-state-between-components` alternative solution, other than `lifting state up`?

Thanks.

**Comment by A7med3bdulBaset** [comment]
As you progress along your learning journey, you will delve into [`memo`](https://react.dev/reference/react/memo). This concept involves a higher-order component that encapsulates another component, allowing it to avoid unnecessary rerendering when none of its props have undergone changes.

For your scenario, to prevent the re-rendering of `<D />`. You can export your component as `export React.memo(D)` instead of a simple `export D`.

**Comment by loynoir** [comment]
@A7med3bdulBaset 

Thanks for your reply.

But I guess about `memo`

- When  `A` have children `B`, `C`, `D0`, `D1`, `D2` ..., need to wrap all `D0` `D1` `D2` ... with `memo`. 
 
Is that correct? 

This will also create unnecessary complexity.

---

I would expect a `useSharedState`.

<details>
  <summary markdown="span">code</summary>

==> shared.tsx <==
```tsx
const sharedBC = useSharedState()

export { sharedBC }
```

==> B.tsx <==
```tsx
/* global console */
import type { JSX } from 'react'
import { sharedBC } from './shared.js'

function B(): JSX.Element {
  console.debug('enter B')

  const [sharedBC, setSharedBC] = sharedBC()
  return <button onClick={setSharedBC}>Clicked {sharedBC} times</button>
}

export default B
```

==> C.tsx <==
```tsx
/* global console */
import type { JSX } from 'react'
import { sharedBC } from './shared.js'

function C(): JSX.Element {
  console.debug('enter C')

  const [sharedBC, setSharedBC] = sharedBC()
  return <button onClick={setSharedBC}>Clicked {sharedBC} times</button>
}

export default C
```

</details>

In this way, even `B` and `C`, one at high tree, one at low tree

- `B` and `C` can update each other

- and increase **ZERO** complexity to **their neighorhood**

So, is there is a `useSharedState`?

**Comment by A7med3bdulBaset** [comment]
Even `useSharedState` you'll study it but with different names.
This is called [`Context`](https://react.dev/learn/passing-data-deeply-with-context). First, you have to lift state up to the parent component `<A />`. then create a context: 

```jsx
// A.jsx
export const CounterContext = React.createContext(1)

export function A() {
   const [count, setCount]= React.useState(1);
  
   return (
       <CounterContext.Provider value={{count, setCount}}>
           <B />
           <C />
           <D />
       </CounterContext.Provider>
   )
}
```
- create a `CounterContext`.
-  export it we will use it later.
- wrap your components in `<Provider>`

```jsx
// B.jsx
import { CounterContext } from "./A"

export function B() {
   const { count } = React.useContext(CounterContext)

  // use count as you need
}
```

Note: Don't worry about it now. You will learn it in due time. Just know it exists.

**Comment by loynoir** [comment]
Thanks. 

This should also be mentioned within [sharing-state-between-components](https://react.dev/learn/sharing-state-between-components).

**Comment by loynoir** [comment]
<details>
  <summary markdown="span">code</summary>

```tsx
/* global console */
import { useState, type JSX, createContext, useContext } from "react";

const CounterContext = createContext(0);
const CounterDispatchContext = createContext(
  null as any as (value: number) => void
);

function A(): JSX.Element {
  console.debug("enter A");

  const [sharedBC, setSharedBC] = useState(0);
  return (
    <>
      <CounterContext.Provider value={sharedBC}>
        <CounterDispatchContext.Provider value={setSharedBC}>
          <B />
          <C />
          <D />
        </CounterDispatchContext.Provider>
      </CounterContext.Provider>
    </>
  );
}

function B(): JSX.Element {
  console.debug("enter B");

  const sharedBC = useContext(CounterContext);
  const setSharedBC = useContext(CounterDispatchContext);
  return (
    <button onClick={() => setSharedBC(sharedBC + 1)}>
      Clicked {sharedBC} times
    </button>
  );
}

function C(): JSX.Element {
  console.debug("enter C");

  const sharedBC = useContext(CounterContext);
  const setSharedBC = useContext(CounterDispatchContext);
  return (
    <button onClick={() => setSharedBC(sharedBC + 1)}>
      Clicked {sharedBC} times
    </button>
  );
}

function D(): JSX.Element {
  console.debug("enter D");

  return (
    <div>
      <h1>D</h1>
    </div>
  );
}

export default A;
```

</details>

No.

Click `B` or `C`.

Actually, `context` implement have console log, as same as prev implement.

```txt
enter A
enter B
enter C
enter D
```

Expect, best implement should be console log

```txt
enter B
enter C
```

**Comment by rickhanlonii** [comment]
Hey @loynoir, in React, rendering isn't a bug or something to be avoided so lifting state up works even with the additional renders. Generally, rendering isn't a problem and it's best to let React determine what to render as needed. Check out [Thinking in React](https://react.dev/learn/thinking-in-react#step-4-identify-where-your-state-should-live) for a overview of how to decide where state would live.

If you profile and find that some part of the tree is expensive to render, you can avoid renders using memoization with `useMemo`, `useCallback` or `memo`, as @A7med3bdulBaset mentioned.
