### ISSUE TITLE
npm install failing

### ISSUE THREAD

**Issue by FurrukhJamal** [reactjs/react.dev#6218]
I wanted to contribute to the docs website but its not installing the dependencies when i run `npm install` this is the error I am seeing 

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-dev@1.0.0
npm ERR! Found: react@0.0.0-experimental-16d053d59-20230506
npm ERR! node_modules/react
npm ERR!   react@"^0.0.0-experimental-16d053d59-20230506" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0 || ^17 || ^18" from @codesandbox/sandpack-react@1.15.5
npm ERR! node_modules/@codesandbox/sandpack-react
npm ERR!   @codesandbox/sandpack-react@"1.15.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\furru\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\furru\AppData\Local\npm-cache\_logs\2023-08-12T07_46_34_541Z-debug.log`

my node version is **v16.13.1**

the `eresolve-report.txt` file is as follows 

`# npm resolution error report

2023-08-12T07:46:34.506Z

While resolving: react-dev@1.0.0
Found: react@0.0.0-experimental-16d053d59-20230506
node_modules/react
  react@"^0.0.0-experimental-16d053d59-20230506" from the root project

Could not resolve dependency:
peer react@"^16.8.0 || ^17 || ^18" from @codesandbox/sandpack-react@1.15.5
node_modules/@codesandbox/sandpack-react
  @codesandbox/sandpack-react@"1.15.5" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react",
    "version": "0.0.0-experimental-16d053d59-20230506",
    "whileInstalling": {
      "name": "react-dev",
      "version": "1.0.0",
      "path": "D:\\projects\\opensourceprojects\\react.dev"
    },
    "location": "node_modules/react",
    "isWorkspace": false,
    "dependents": [
      {
        "type": "prod",
        "name": "react",
        "spec": "^0.0.0-experimental-16d053d59-20230506",
        "from": {
          "location": "D:\\projects\\opensourceprojects\\react.dev"
        }
      }
    ]
  },
  "currentEdge": {
    "type": "prod",
    "name": "react",
    "spec": "^0.0.0-experimental-16d053d59-20230506",
    "from": {
      "location": "D:\\projects\\opensourceprojects\\react.dev"
    }
  },
  "edge": {
    "type": "peer",
    "name": "react",
    "spec": "^16.8.0 || ^17 || ^18",
    "error": "INVALID",
    "from": {
      "name": "@codesandbox/sandpack-react",
      "version": "1.15.5",
      "whileInstalling": {
        "name": "react-dev",
        "version": "1.0.0",
        "path": "D:\\projects\\opensourceprojects\\react.dev"
      },
      "location": "node_modules/@codesandbox/sandpack-react",
      "isWorkspace": false,
      "dependents": [
        {
          "type": "prod",
          "name": "@codesandbox/sandpack-react",
          "spec": "1.15.5",
          "from": {
            "location": "D:\\projects\\opensourceprojects\\react.dev"
          }
        }
      ]
    }
  },
  "strictPeerDeps": false,
  "force": false
}
`

**Comment by mdmasudrana** [comment]
Attempt using " npm install --force " to see if it functions.

**Comment by FurrukhJamal** [comment]
it did installed using the --force flag, I don't know if it was installed properly or the missed dependencies would cause a problem
