### ISSUE TITLE
Twitter icon to X icon

### ISSUE THREAD

**Issue by venom-10** [reactjs/react.dev#6234]
![image](https://github.com/reactjs/react.dev/assets/96457403/4a52f4ce-5d04-4cf3-870a-7f51273846aa)

Want to update the Twitter icon to the X icon.

**Comment by myselfprincee** [comment]
Yeah just did it. soon will it be added :)

<img width="227" alt="image" src="https://github.com/reactjs/react.dev/assets/114233864/e2642bd7-d67f-4c0b-b5c3-65165f64650a">

<img width="102" alt="image" src="https://github.com/reactjs/react.dev/assets/114233864/7f2a5b3c-b0e5-44aa-b274-c88d03045867">
