### ISSUE TITLE
Ukraine emoji doesn't display

### ISSUE THREAD

**Issue by nina-alin** [reactjs/react.dev#6236]
Hi there!

The "Ukraine" emoji in the banner doesn't display properly on Opera GX, Chrome, and Edge (I haven't tested it on Firefox). I'm not sure where the problem comes from, and I'm not sure if I'm the only one experiencing it.

Here's a screenshot:

![image](https://github.com/reactjs/react.dev/assets/56309556/a01628ee-59f8-4539-9010-ddff45b5f447)

**Comment by myselfprincee** [comment]
It is also not visible in Brave Browser. Only Working in Firefox.

**Comment by myselfprincee** [comment]
Hi, I had Fixed The Issue. soo, it will be fixed. Working on another issue with verical bar.

**Comment by nina-alin** [comment]
Nice, thank you very much !

**Comment by nina-alin** [comment]
I think the React team removed the banner. I'll close this issue.
