### ISSUE TITLE
There's some initiative to translate the new react.dev to other languages?

### ISSUE THREAD

**Issue by NicodemosSantos** [reactjs/react.dev#6245]
The [Legacy ReactJs](https://legacy.reactjs.org/) documentation includes translations in various languages. However, I've noticed that the newer documentation doesn't offer this feature. I have friends who are just starting out with React, and while I recommended the official documentation to them, they don't speak English. Unfortunately, automatic translations don't capture the nuances accurately. Is there a way I can assist in initiating a translation project, or is there already an initiative underway for this purpose?

**Comment by NicodemosSantos** [comment]
Noticed if you go to https://legacy.reactjs.org/languages you can click on "contribute" and go to the page of the new documentation with the translation. Instead of having the translation in one website alone, is subdivided in subdomains as https://pt-br.react.dev/

**Comment by smikitky** [comment]
You couldn't find the translated sites because most new translation sites somehow block search engines for now. This problem is tracked in #6260.
