### ISSUE TITLE
Contribute purpose

### ISSUE THREAD

**Issue by minhajul-im** [reactjs/react.dev#6255]
hey there! what's up? 
how can I contribute here?
 could you tell me? 
thanks

**Comment by BartoszKlonowski** [comment]
Hello @minhajul-im!
The best is to start with an open issue that you find doable and start working on it following the steps to set up the repo:
https://github.com/reactjs/react.dev?tab=readme-ov-file#contributing
Note that we don't assign to issues, also there's no need to ask for a green light to work on an issue. If you pick it, just launch a PR, link it correctly to the issue you worked on and it will be reviewed.
Thank you for willing to contribute!

As I hope this answers your question, I will close this issue for now, thanks!
