### ISSUE TITLE
ERROR WHEN USING YARN DEV TO START THE SERVER

### ISSUE THREAD

**Issue by techstrix** [reactjs/react.dev#6258]
I am experiencing an error when trying to start a dev server with yarn dev command.
I have not in any way modified the source code and it is just as I cloned it but it shows the error shown below when trying to start the server.
![image](https://github.com/reactjs/react.dev/assets/91886864/05912269-f3c6-45db-af0d-12bad15b55b2)
Can someone tell me how to fix this please?

**Comment by myselfprincee** [comment]
Same Here

**Comment by cvijandj** [comment]
I would take a look at [this link](https://github.com/babel/babel/discussions/13013), there is a solution, or you could try installing [@babel/plugin-transform-react-jsx](https://babeljs.io/docs/babel-plugin-transform-react-jsx).
@myselfprincee @techstrix

**Comment by myselfprincee** [comment]
> I would take a look at [this link](https://github.com/babel/babel/discussions/13013), there is a solution, or you could try installing [@babel/plugin-transform-react-jsx](https://babeljs.io/docs/babel-plugin-transform-react-jsx).
> @myselfprincee @techstrix 

Thanks 🙂
