### ISSUE TITLE
there is no documentation for error 482 in minified error 

### ISSUE THREAD

**Issue by mehrad94** [reactjs/react.dev#6273]
i have issue when uploading nextjs and the server error is https://legacy.reactjs.org/docs/error-decoder.html/?invariant=482 but there is n documentation in the link

**Comment by ndodson** [comment]
Make sure you aren't accidentally defining a client component as async

**Comment by shahinKahrizi** [comment]
> Make sure you aren't accidentally defining a client component as async

thanks mate you cure my head deck after 2 hours of debugging

**Comment by kr4chinin** [comment]
Thanks 🙏

**Comment by rickhanlonii** [comment]
Fixed by manually re-deploying the legacy site, the longer term fix is here: https://github.com/reactjs/react.dev/pull/6214
