### ISSUE TITLE
The warning on the "Start a new React Project" page may be outdated

### ISSUE THREAD

**Issue by rampatra** [reactjs/react.dev#6274]
From the [nextjs website](https://nextjs.org/docs/app), I think the below warning isn't true anymore.

> Next.js's App Router is currently in beta and is not yet recommended for production (as of Mar 2023). To experiment with it in an existing Next.js project, follow this incremental migration guide.

Page link: https://react.dev/learn/start-a-new-react-project
File link: https://github.com/reactjs/react.dev/blob/main/src/content/learn/start-a-new-react-project.md

**Comment by A7med3bdulBaset** [comment]
#6005

**Comment by myselfprincee** [comment]
So why it is not solved till now ?? #6274
It is not something Big, It is just a simple Pull Request. 

I sometimes feel this repo is dead.

**Comment by lunaleaps** [comment]
There is a more comprehensive update needed for this page. For now https://github.com/reactjs/react.dev/pull/6318 will handle the inaccuracy as revisit the page. Thank for reporting

**Comment by myselfprincee** [comment]
> There is a more comprehensive update needed for this page. For now https://github.com/reactjs/react.dev/pull/6318 will handle the inaccuracy as we revisit the page. Thanks for reporting!

Thank You so much Contributor Sir 🙂
