### ISSUE TITLE
  useState reference on official React docs website

### ISSUE THREAD

**Issue by shaghayeghrabiee** [reactjs/react.dev#6304]
This page was provided by meta for Additional resources, but this page does not work.

**Comment by lunaleaps** [comment]
Can you provide more detail on the issue? What is the expected and actual behavior?

**Comment by farhanhalai30** [comment]
@shaghayeghrabiee 
Can you please share the link and screenshots?

**Comment by kprakhar** [comment]
I guess you're looking for this -> `https://react.dev/reference/react/useState`

**Comment by rickhanlonii** [comment]
Yup, as @kprakhar said, this doc exists here: [react.dev/reference/react/useState](https://react.dev/reference/react/useState)
