### ISSUE TITLE
Attempted import error: 'GraphQLError' is not exported from 'graphql' (imported as 'GraphQLError'). WARNING in ./node_modules/react-double-scrollbar/dist/DoubleScrollbar.js Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):

### ISSUE THREAD

**Issue by AkhterShadab** [reactjs/react.dev#6306]
Hi Team,
I m facing below challenge while "npm start", I tried to follow the steps mentioned in this [github](https://github.com/aws-amplify/amplify-js/issues/4387) solution, but no success.

Below is description of error and attached screenshot of localhost.

Attempted import error: 'GraphQLError' is not exported from 'graphql' (imported as 'GraphQLError').
WARNING in ./node_modules/react-double-scrollbar/dist/DoubleScrollbar.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\ShadabAkhtar\frontend-app\node_modules\react-double-scrollbar\dist\DoubleScrollbar.js.map' file: Error: ENOENT: no such file or directory, open 'C:\Users\ShadabAkhtar\frontend-app\node_modules\react-double-scrollbar\dist\DoubleScrollbar.js.map'

WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://antd/./components/config-provider/style/index.less' URL is not supported

WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://antd/./components/icon/style/index.less' URL is not supported

WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://antd/./components/locale-provider/style/index.less' URL is not supported

WARNING in ./node_modules/antd/dist/antd.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./node_modules/antd/dist/antd.css)
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map: 'webpack://antd/./components/time-picker/style/index.less' URL is not supported

ERROR in ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js 311:36-48
export 'GraphQLError' (imported as 'GraphQLError') was not found in 'graphql' (module has no exports)

ERROR in ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js 322:38-50
export 'GraphQLError' (imported as 'GraphQLError') was not found in 'graphql' (module has no exports)

ERROR in ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js 446:40-52
export 'GraphQLError' (imported as 'GraphQLError') was not found in 'graphql' (module has no exports)

ERROR in ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js 628:34-46
export 'GraphQLError' (imported as 'GraphQLError') was not found in 'graphql' (module has no exports)

ERROR in ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js 643:36-48
export 'GraphQLError' (imported as 'GraphQLError') was not found in 'graphql' (module has no exports)

ERROR in ./node_modules/@aws-amplify/pubsub/lib-esm/Providers/AWSAppSyncRealTimeProvider.js 669:34-46
export 'GraphQLError' (imported as 'GraphQLError') was not found in 'graphql' (module has no exports)

webpack compiled with 6 errors and 5 warnings

![image](https://github.com/reactjs/react.dev/assets/69979674/3a5902da-9d6c-4383-8cef-a30c7b846f08)

**Comment by BartoszKlonowski** [comment]
Hello @AkhterShadab!
Unfortunately this issue you reported is not related to the documentation of React.
You experienced potential issue with another package (to which you shared the link already), so you should report this issue in that repo.
So please report this in the repo of the package owner, while I will close this issue.
Thank you!
