### ISSUE TITLE
Broken Link to React v18

### ISSUE THREAD

**Issue by cbarrett3** [reactjs/react.dev#6309]
On [this page](https://react.dev/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022) of the react.dev website, the link to "React 18" is not valid - it brings me here: https://legacy.reactjs.org/blog/2022/03/29/react-v18.

**Comment by lunaleaps** [comment]
Oh I see, I think it's because our legacy forwarding for blog posts needs a `.html` suffix, is this something you'd be interested in looking into?

**Comment by cbarrett3** [comment]
Sure! I will submit a PR.

I haven’t contributed before but I would be happy to.

Thanks,
Connor
