### ISSUE TITLE
Npm audit fix --force

### ISSUE THREAD

**Issue by LareineHan** [reactjs/react.dev#6311]
Seems like whenever I run commands on terminal, my react project gets problems. I thought I installed recent version of node js and react is current version because I started it two days ago.

My terminal shows los of error warning messages and recommend run 

npm audit fix--force

And when i run this command, my project is frozen, whole laptop is slowing down and don't work and I have to restart my laptop. 

So frustrated. How can I solve this issue?

**Comment by lunaleaps** [comment]
Hi @LareineHan, this issue isn't related to the React docs. You can try [StackOverflow](https://stackoverflow.com/questions/tagged/reactjs) for questions around specific set-ups and workflows with React
