### ISSUE TITLE
TicTacToe tutorial for local development is broken due to CodeSandbox bug 

### ISSUE THREAD

**Issue by sahiltalwar88** [reactjs/react.dev#6317]
The [TicTacToe tutorial](https://react.dev/learn/tutorial-tic-tac-toe) is broken because the "Export to zip" functionality in CodeSandbox does not work as expected. 

This bug was first reported [in this issue](https://github.com/facebook/react/issues/27237) and has several workarounds; however, it may be worthwhile to revert to [the old directions](https://legacy.reactjs.org/tutorial/tutorial.html#setup-for-the-tutorial) while CodeSandbox addresses the bug that Dan was kind enough to report (assuming that their response time is not measured in days or less).

**Comment by lunaleaps** [comment]
From reading the issue it seems it's the local experience that isn't working for codesandbox. It is still a working tutorial if you follow along in codesandbox on web.Correct me if I'm mistaken.  I'd be hesitant to completely revert the tutorial to the legacy one. 

Do we happen to have the issue reported to codesandbox?

**Comment by lunaleaps** [comment]
There is also a workaround of using this [forked codesandbox](https://codesandbox.io/s/723948?file=/App.js&utm_medium=sandpack) from @danielmayorga

reference: https://github.com/reactjs/react.dev/issues/6139#issuecomment-1634530884

**Comment by tomtheisen** [comment]
> From reading the issue it seems it's the local experience that isn't working for codesandbox. It is still a working tutorial if you follow along in codesandbox on web.  Correct me if I'm mistaken.

Part of the instructions [on the web](https://react.dev/learn/tutorial-tic-tac-toe) state these instructions.


> You can also follow this tutorial using your local development environment. To do this, you need to:
>
> 1. Install [Node.js](https://nodejs.org/en/)
> 2. In the CodeSandbox tab you opened earlier, press the top-left corner button to open the menu, and then choose File > Export to ZIP in that menu to download an archive of the files locally
> 3. Unzip the archive, then open a terminal and cd to the directory you unzipped
> 4. Install the dependencies with npm install
> 5. Run npm start to start a local server and follow the prompts to view the code running in a browser
>
> If you get stuck, don’t let this stop you! Follow along online instead and try a local setup again later.

There's no clue given that these instructions are broken.  At a minimum, this note should be taken down, until such time as its actually true.  This is potentially a big time sink for a brand new react dev, such as the one this tutorial is targeting.

**Comment by lunaleaps** [comment]
I was under the impression this was actually fixed recently, let me try and repo and if that is the case, I agree and we should remove for now

**Comment by rickhanlonii** [comment]
I've tested this and it is working for both the current Codesandbox editor download and the Beta editor. If you have issues with it, please file a new issue with repro steps, but it looks like this is working now.
