### ISSUE TITLE
Pass setState as props to child component in "Thinking in React" page

### ISSUE THREAD

**Issue by yonus-a** [reactjs/react.dev#6319]
Hi, i hear taht pass setState() as props to child component is not correct, but in "Thinking in React page" you did that !!, why ?? correct my if i am wrong.

![Annotation 2023-09-26 014818](https://github.com/reactjs/react.dev/assets/57180527/5f09a2a7-45cd-4de6-ab8e-4f949416029d)

Thanks.

**Comment by shubhangii0324** [comment]
Working on it

**Comment by kprakhar** [comment]
Why is it not correct, any reason ?

**Comment by rickhanlonii** [comment]
> i hear that pass setState() as props to child component is not correct

Not sure where you heard this, but it's wrong. See this doc, which recommends this pattern: https://react.dev/learn/sharing-state-between-components
