### ISSUE TITLE
typo on page https://react.dev/community

### ISSUE THREAD

**Issue by SimDav888** [reactjs/react.dev#6322]
This technique works when you have an default value which makes sense

"an default"
isn t correct in english,

"a default"
is correct.

there are quite a few typo on the site. I ll do my best to report the one I see from now on. :)

**Comment by harish-sethuraman** [comment]
Would you like to send a PR if you find any?

**Comment by SimDav888** [comment]
Yes . Happy to help. 
I ll have to find how to send PR first thought...
