### ISSUE TITLE
Firefox: Scrollbar of left-side navigation in wrong location

### ISSUE THREAD

**Issue by lunaleaps** [reactjs/react.dev#6348]
Whenever the left hand scrollbar is longer than the viewport height, the scrollbar that appears for Firefox is too far to the right. 

Reproduce
1. Open a page with a scrolling left hand sidebar in Firefox. (I'm using Firefox 116.0.3 on macOS). Example page: https://react.dev/learn/adding-interactivity
2. Scroll the left-hand side. 

Result:
You'll see the scroll bar in the content, when it shouldn't be.
<img width="362" alt="Screenshot 2023-10-10 at 9 23 37 PM" src="https://github.com/reactjs/react.dev/assets/1309636/df1a080c-15cd-4833-81b8-cf909389b3b8">

**Comment by arbiasgjoshi** [comment]
What OS is this issue is appearing? In Firefox 118, that I downloaded I couldn't reproduce said issue!

**Comment by steverydz** [comment]
I have tested this in Firefox 116.0.3 on macOS Ventura 13.5.2 and can't replicate it either.

**Comment by lunaleaps** [comment]
Odd, I guess if it can't be reproduced, then it might've been a dev-only issue? I'll close for now. 

Thank you @arbiasgjoshi and @steverydz for trying to reproduce!
