### ISSUE TITLE
code example seems to have an extra dependency: onChange 

### ISSUE THREAD

**Issue by devmi** [reactjs/react.dev#6358]
I believe the `onChange` event handler shouldn't be declared as a dependency on the following `useEffect` example, because although this is a `prop`, its value should not change, so it's not a condition for the effect to run. Although it may be harmless, it may confuse other learners.

https://github.com/reactjs/react.dev/blob/10574e59a81425e9e8f63f0b094d09e3636b3198/src/content/learn/you-might-not-need-an-effect.md?plain=1#L519

Suggested change:
```
// 🔴 Avoid: The onChange handler runs too late
useEffect(() => {
  onChange(isOn);
}, [isOn])
```

**Comment by pwbriggs** [comment]
Hey @devmi 👋 

I'm not sure I agree.

1. In practice, the `onChange` prop may never change, but there's no way to *guarantee* that.
2. I think it would be *more* confusing to users to directly contradict the `useEffect` documentation.
3. It raises an error to remove the dependency:

![image](https://github.com/reactjs/react.dev/assets/146312751/9b7be37a-cc86-4e07-ab17-847f9709df3e)

Thanks for the feedback though! ❤️

**Comment by rickhanlonii** [comment]
Agree with @pwbriggs. As the docs [here](https://react.dev/learn/removing-effect-dependencies#to-remove-a-dependency-prove-that-its-not-a-dependency) say, you don't “choose” the dependencies of your Effect. Every reactive value used by your Effect’s code must be declared in your dependency list.
