### ISSUE TITLE
Suggestion for Tic Tac Toe Tutorial

### ISSUE THREAD

**Issue by ExuLu** [reactjs/react.dev#6361]
As newbie in programming, while reading Tic Tac Toe tutorial, I found this function and with great enthusiasm modified it with the forEach method. And then I was disappointed when I realized that it didn’t work. So maybe it's better to warn not to change anything in this function and use it as it is.
<img width="684" alt="Screenshot 2023-10-20 at 8 17 45 AM" src="https://github.com/reactjs/react.dev/assets/116097203/62747534-2d27-45ba-951a-a14bec6e7b02">

**Comment by smikitky** [comment]
The current tutorial clearly says the following. Isn't this enough?

> Don’t worry too much about the calculateWinner function; it’s not specific to React

And it's perfectly possible to rewrite this using `Array.forEach()` or [`Array.some()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) if you really want to. Ask ChatGPT or anything.

**Comment by Ajay-singh1** [comment]
@smikitky We can close this issue now.

**Comment by smikitky** [comment]
@harish-sethuraman Could you close this?
