### ISSUE TITLE
The React dev tools Tabs Doesn't Show Up unless i checked all reasons in https://github.com/facebook/react/tree/main/packages/react-devtools#the-react-tab-doesnt-show-up #27564

### ISSUE THREAD

**Issue by denis-ttk-1975** [reactjs/react.dev#6368]
I cant see react tabs in chrome dev panel.
I have checked this problem on https://reactjs.org/ and have got the same result

My OS:
Edition Windows 11 Pro
Version 22H2
Installed on ‎25.‎02.‎2023
OS build 22621.2428
Experience Windows Feature Experience Pack 1000.22674.1000.0

My browser version is Chrome Version is 118.0.5993.89 (Official Build) (64-bit)

My React Developer Tools extension version is 4.28.4 (10/3/2023)

![React dev tools problem](https://github.com/reactjs/react.dev/assets/75208826/56de5fdb-359c-48b4-bf21-de541e6b54d7)

**Comment by harish-sethuraman** [comment]
Hey thanks for raising this issue. How ever the right place to raise this issue would be https://github.com/facebook/react/ repo as the devtools code resides there. This repo contains just the documentation site.
