### ISSUE TITLE
Shows Page not found

### ISSUE THREAD

**Issue by SivaSwathiVasagar** [reactjs/react.dev#6372]
https://react.dev/apis/react/useEffect#useeffect - Page not found

**Comment by harish-sethuraman** [comment]
Can you let us know where you found this link from? was it in the docs? or external?

**Comment by harish-sethuraman** [comment]
I see no reference of this links from inside the documentation. This change in the URL from `apis` to `reference` was done [long ago](https://github.com/reactjs/react.dev/pull/5400). Closing this issue. Please do re open if you find the same reference inside the docs

**Comment by SivaSwathiVasagar** [comment]
I found this link from the Coursera reference page and when I tried opening
it I saw a page not found and a link to raise a request.
