### ISSUE TITLE
Typo on taintObjectReference page

### ISSUE THREAD

**Issue by olegchursin** [reactjs/react.dev#6376]
main -> may

...a tainted object creates a new untained object which ~main~ may contain sensetive data.

**Comment by smikitky** [comment]
You cannot directly push a commit to this repo. Instead, you need to make a fork first.

Alternatively, you can just use the GitHub's edit button, which will create a fork automatically: https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository

**Comment by harish-sethuraman** [comment]
this should be fixed
