### ISSUE TITLE
Typo at react.dev/reference/react/lazy

### ISSUE THREAD

**Issue by rmschindler** [reactjs/react.dev#6380]
At the page `https://react.dev/reference/react/lazy`, we see the sentence, “lazy lets you defer loading component’s code until it is rendered for the first time.”

I draw your attention to the incorrect `component’s`, which should be `components’`.

**Comment by rohan-kapse** [comment]
@rmschindler I think its grammatically correct.

**Comment by rmschindler** [comment]
I beg your pardon, but you are not right, @rohan-kapse, about its being grammatically correct. But you made me notice that my suggestion for the correction was not right, either.

Here is my renewed suggestion:
instead of:
"lazy lets you defer loading component’s code until it is rendered for the first time"
this:
"lazy lets you defer loading the component’s code until it is rendered for the first time"

**Comment by rohan-kapse** [comment]
@rmschindler couldn't agree more : )
