### ISSUE TITLE
Unused variable in the code of the tutorial

### ISSUE THREAD

**Issue by witch-factory** [reactjs/react.dev#6405]
Hi. I am reading the "Learn React" Page, [Updating Arrays in State](https://react.dev/learn/updating-arrays-in-state).

In the example code of the tutorial, there is `nextId` variable for the next ID for the new item for the array state. But after the [Making other changes to an array](https://react.dev/learn/updating-arrays-in-state#making-other-changes-to-an-array) section, this variable is never used but exists. 

```js
import { useState } from 'react';

let nextId = 3;
const initialList = [
  { id: 0, title: 'Big Bellies' },
  { id: 1, title: 'Lunar Landscape' },
  { id: 2, title: 'Terracotta Army' },
];

export default function List() {
  const [list, setList] = useState(initialList);

  function handleClick() {
    const nextList = [...list];
    nextList.reverse();
    setList(nextList);
  }

  return (
    <>
      <button onClick={handleClick}>
        Reverse
      </button>
      <ul>
        {list.map(artwork => (
          <li key={artwork.id}>{artwork.title}</li>
        ))}
      </ul>
    </>
  );
}
```

Is it intended for something? If not, please remove the declaration of unused variable. Otherwise, it would be very thanksful to me if someone tell me the point of it.

**Comment by sparshyadav** [comment]
When we use map function, we need to pass a key, and the key for every element of the array should be unique, so initially we have declare nextId as 0, and later on when we add new elements in the artists array, we are updating the nextId by 1 and using it as id for that element, so that for every element the id is unique.
`
<button onClick={() => {
        artists.push({
          id: nextId++,
          name: name,
        });
      }}>Add</button> 
`
And when the map is used that id is pass as key in the map function so that each key is unique.
`{artists.map(artist => (
          <li key={artist.id}>{artist.name}</li>
        ))}`

**Comment by witch-factory** [comment]
Yeah right. There are codes in tutorial using `nextId `for that reason.

But I am saying that there are the example code never using `nextId` variable. 

The code I copied in this issue is one of the example code [here in  learn react page](https://react.dev/learn/updating-arrays-in-state#making-other-changes-to-an-array). In that code, there is no place using the `nextId` but it is declared. Why not remove its declaration?

**Comment by sparshyadav** [comment]
Yes, you are write in that example we can remove nextId, it is of no use in this example.

**Comment by rickhanlonii** [comment]
Fixed by https://github.com/reactjs/react.dev/pull/6470
