### ISSUE TITLE
reactive dependencies page not found 

### ISSUE THREAD

**Issue by derikesh** [reactjs/react.dev#6406]
![image](https://github.com/reactjs/react.dev/assets/107841452/ca03ec5d-7021-4233-a1f7-0070d5fee4fb)

From Gsap documentation of react

https://gsap.com/resources/React/
(Scroll to  #Controlling when React creates our animation. )

**Comment by kprakhar** [comment]
It should be `https://react.dev/reference/react/useEffect#specifying-reactive-dependencies`

**Comment by rickhanlonii** [comment]
Yeah we changed the URL. I verified that gsap.com have fixed the links.
