### ISSUE TITLE
the demo of useOptimistic has some bugs

### ISSUE THREAD

**Issue by JackWuyulong** [reactjs/react.dev#6412]
i found some bugs when i run the demo of useOptimistic. The result of list always show the final value instead of all my input value  if i input quickly. 
![Kapture 2023-11-06 at 17 41 06](https://github.com/reactjs/react.dev/assets/29191965/99773050-ad2a-4aee-bc08-9353dac2bedf)

Then i awared of why the result like this.  Because the function of  sendMessages isn't right.
`
  async function sendMessage(formData) {
      const sentMessage = await deliverMessage(formData.get("message"));
      **setMessages([...messages, { text: sentMessage }]);**
    }
`
it should be like below:
  `setMessages((messages) =>[...messages,{text:sentMessage}] )`

i hope to get reply, thanks

**Comment by mattcarrollcode** [comment]
Thanks for the bug report! I've reproduced the error, and looks like a race condition.

Link to page with the problematic code sample: https://react.dev/reference/react/useOptimistic#optimistically-updating-with-forms

Pointer to the code that has the bug: https://github.com/reactjs/react.dev/blob/main/src/content/reference/react/useOptimistic.md?plain=1#L119

**Comment by kmiddleton14** [comment]
This should now be fixed. Thank you for reporting!

**Comment by rickhanlonii** [comment]
@thedv91 yes, we're tracking that here: https://github.com/facebook/react/issues/28574#issuecomment-2015704343
