### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by vishwjeet-ujgare** [reactjs/react.dev#6436]
I got a page link from the Meta Advanced React Coursera course. but it  showing not found follwoing are the links 

useState reference on official React docs website : https://beta.reactjs.org/apis/react/useState#usestate

useEffect reference on official React docs website : https://beta.reactjs.org/apis/react/useEffect#useeffect

**Comment by kprakhar** [comment]
It should be following

1. https://react.dev/reference/react/useState
2. https://react.dev/reference/react/useEffect

**Comment by rickhanlonii** [comment]
We're not affiliated with this course, they'll need to update the links.
