### ISSUE TITLE
Usage of for loop in jsx

### ISSUE THREAD

**Issue by akshat-bhansali** [reactjs/react.dev#6446]
If I have an object and want to render a component a number of types which is equal to a value in the object, how can we do by simple mapping?A for loop will be very flexible and easy to use + understand

**Comment by MahdiSelmani** [comment]
const dataObject = {
  numberOfComponents: 5
};

An array to hold your components
const componentsArray = [];

Use a for loop to push components into the array
for (let i = 0; i < dataObject.numberOfComponents; i++) {
  componentsArray.push(<YourComponent key={i} />);
}

Render the array of components
return <div>{componentsArray}</div>;

Does this help you?

**Comment by purohitdheeraj** [comment]
hey @akshat-bhansali 

```js

const componentsData = {
   item1 : value or array or object,
   item2 : value or array or object
}

as far i understand you want to map such type of object which have multiple data

you can covert the object into arr with Object.values
since we need values of object 

use this return of component

function App(){
return Object.values(componentData).map(item => {
    return <div>{item}</div>
})
}

```


you can also refer this blog for that 
[iterate object in react](https://devsheet.com/loop-through-an-object-using-map-in-react/)

**Comment by purohitdheeraj** [comment]
@akshat-bhansali  also feel free to close this issue if you got your solution
thanks 🚀

**Comment by akshat-bhansali** [comment]
Thank you so much😊
