### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bestbelfast** [reactjs/react.dev#6448]
When I was learning createRoot in the client API, when I clicked on the link under domNode, I found the link error

**Comment by harish-sethuraman** [comment]
Hey I checkout that page and links seemed fine. Can you provide the exact link to which you were re directed to? and which text you clicked?

**Comment by bestbelfast** [comment]
Thanks for reply，I am from China and study on the official website in Chinese.(https://react.docschina.org/reference/react-dom/client/createRoot)
When I click "[DOM 元素]",the link is (https://react.docschina.org/https%EF%BC%9A/developer.mozilla.org/zh-CN/docs/Web/API/Element),which shows "This page doesn’t exist."

**Comment by pwbriggs** [comment]
@bestbelfast thanks for reporting this error!

For future reference, the source files for the Chinese translation of the documentation site are in the [zh-hans.react.dev](https://github.com/reactjs/zh-hans.react.dev) repository. I've opened a PR in that repo to fix the link you mentioned.

**Comment by Yucohny** [comment]
@bestbelfast @pwbriggs https://github.com/reactjs/zh-hans.react.dev/pull/1401 has been merged. Thanks for your feedback.
