### ISSUE TITLE
UI BUG : Navigation button text overflows from parant span box

### ISSUE THREAD

**Issue by godspeed-03** [reactjs/react.dev#6460]
Website or app
https://react.dev/reference/react/startTransition

Repro steps
When hovering on the next navigation button, the text overflows the Box.
issue image
![Screenshot from 2023-12-02 23-55-42](https://github.com/reactjs/react.dev/assets/119731754/3b915011-0006-43e1-a7ab-927a9168c8f0)

code -
Just needed to warp the link text with Break-word property.

How often does this bug happen?
Every time

**Comment by nitesh9109** [comment]
@godspeed-03, I am also using the Brave browser. However, this problem doesn't occur in Brave, instead, it happens in Firefox.

**Comment by iamdebobrota** [comment]
# Attempted

**Comment by iamdebobrota** [comment]
Raised the PR, have fixed the UI : https://github.com/reactjs/react.dev/pull/6493

**Comment by iamdebobrota** [comment]
Here is an example  : 
<img width="947" alt="image" src="https://github.com/reactjs/react.dev/assets/99647439/4983463c-c490-40e4-ba16-fb26c3cbaebd">

**Comment by prajwalkulkarni** [comment]
I think using `break-all` or `break-word` still wouldn't fix the issue completely. What if the string is even longer? The container height would be increased to avoid overflowing and accommodate the complete string in multiline.
The same goes with increasing the parent width, or even alternatively setting the width to be `auto` with a min-width. It would mess up the design system and lead to visual inconsistencies. 
Instead, I think without altering the width of the container, we can hide the overflowing content with ellipsis and on hover show the complete string on the tooltip.

**Comment by rickhanlonii** [comment]
Fixed https://github.com/reactjs/react.dev/pull/6519
