### ISSUE TITLE
Sidbar scrollbar auto hides incorrrectly

### ISSUE THREAD

**Issue by Kathenae** [reactjs/react.dev#6469]
When i try to move my mouse over to try and click the **scrollbar** it disappears/hides itself, think the hover area for the sidebar might be wrong i'm not sure, i haven't tried to look into it. 

Please check this video for a better explanation:
https://github.com/reactjs/react.dev/assets/87710251/5e0895c2-db28-4ee8-97ac-4f5139e64a0e

**Comment by godspeed-03** [comment]
Hi @Kathenae . Actually there is an issue with the **sidebar** in **Reference** section in the react.dev site.

Issue happening at  : https://react.dev/reference/react/useState

- ![image](https://github.com/reactjs/react.dev/assets/119731754/a50b1c74-6450-49d3-85d5-5ea393e64c3c)

[Screencast from 10-12-23 01:13:41 AM IST.webm](https://github.com/reactjs/react.dev/assets/119731754/6e7f1c69-d9ed-46d9-8cde-007b3bcb9268)


Isuue happening : 
Every time in the of sidebar in Reference section.

- ![image](https://github.com/reactjs/react.dev/assets/119731754/f0216371-6932-4192-bd68-3f9d4cb89557)

[Screencast from 10-12-23 01:14:41 AM IST.webm](https://github.com/reactjs/react.dev/assets/119731754/b24fac21-8db3-4234-a472-f8a84c7f32a5)

Browser and device : 
Google-chrome : Version 120.0.6099.71
OS : Ubuntu 22.04.3 LTS
