### ISSUE TITLE
Tic-Tac-Toe Tutorial: Steps to Run Locally Are Outdated

### ISSUE THREAD

**Issue by AbdelrahmanSadat** [reactjs/react.dev#6480]
## The Problem
- Ran into issues trying to run the tutorial locally.
- The docs suggest using online sandbox for learning purposes. However, being old school, I wanted to try setting it up locally. The docs also kindly provided steps to run the tutorial locally: 
<blockquote>
You can also follow this tutorial using your local development environment. To do this, you need to:

1. Install [Node.js](https://nodejs.org/en/)
2. In the CodeSandbox tab you opened earlier, press the top-left corner button to open the menu, and then choose File > Export to ZIP in that menu to download an archive of the files locally
3. Unzip the archive, then open a terminal and cd to the directory you unzipped
4. Install the dependencies with npm install
5. Run npm start to start a local server and follow the prompts to view the code running in a browser
</blockquote>

- They failed because:
    1. They say to download a zipped file of the files from the codesandbox environment. Such an option did not exist (anymore).
    2. I copied the files manually & installed dependencies manually to get over that part. But then they say to run `npm start`, which I do. However, there is no `run` script in the package.json file, or any scripts for that matter.

## The Solution
- Like I said, I added the files & dependencies manually since there was no "download" option. They can also be cloned to a git repo from Codesandbox.
- And I added `"run": "react-scripts start"` to the `package.json` scripts.
- And following along, I had to move the src files (`App.js`, `index.js` & `styles.css`) into a src dir, and the `index.html` file into the public dir, as per the react-scripts error msg.
- And voila, it runs locally.

## Updating The Docs
I have to say, this felt a little frustrating, running into problems the first time I try to run React (in a while), and I can Imagine it can be frustrating for other newcomers.

So now I'd like to update the docs to either reflect those steps, or to update the code used in the sandbox. But I'm not sure where codesandbox gets its code from.

**Comment by A-4-Atom** [comment]
You can download the sandbox from menu on top left corner.
![image](https://github.com/reactjs/react.dev/assets/61468834/630abfc8-3376-4c47-8e49-7fa8e0be60fe)

But package.json file still needs fixing. as there is no script to start a local server.

**Comment by harish-sethuraman** [comment]
I think this should be fixed now? we recently moved all the file contents to src directory 🤔 and made fixes to similar problem?

**Comment by A-4-Atom** [comment]
Yes, you can close this issue now. I've checked package.json file has proper scripts
