### ISSUE TITLE
Download codesandbox broken in Beta editor

### ISSUE THREAD

**Issue by rickhanlonii** [reactjs/react.dev#6482]
From [/u/Kaleidoscope991](https://www.reddit.com/r/reactjs/comments/18fyfhw/fyi_the_react_tutorial_is_out_of_date/):

> Posting here in the hopes that someone in charge can look into it.
The steps on this page are no longer accurate, partly due to changes on Codesandbox.
https://react.dev/learn/tutorial-tic-tac-toe#setup-for-the-tutorial
Specifically, the instructions for step 2 are outdated (there is no such option File > Export to ZIP).
The closest thing (Download Sandbox) does not supply files that work correctly in VSCode. Following the steps to the letter and then trying to execute "npm start" gives the error missing script "start".

**Comment by rickhanlonii** [comment]
I'm seeing the Export to ZIP option, are you able to see this?

<img width="742" alt="Screenshot 2023-12-11 at 11 59 10 AM" src="https://github.com/reactjs/react.dev/assets/2440089/89df89d1-bc1d-4b49-b343-87449fec2407">

**Comment by rickhanlonii** [comment]
Oh I see, in the Beta UI it's under Download Sandbox:
<img width="600" alt="Screenshot 2023-12-11 at 2 06 17 PM" src="https://github.com/reactjs/react.dev/assets/2440089/65cd8108-babd-4814-8391-a226c600bc84">


And like you mentioned, it looks like the beta codesandbox doesn't download all the same files:

<img width="1051" alt="Screenshot 2023-12-11 at 1 59 50 PM" src="https://github.com/reactjs/react.dev/assets/2440089/aaf3e645-5e0e-4734-be0a-3b53b8e97308">

I can update the docs, but will need to contact Codesandbox to figure out why all the correct files aren't downloading.

**Comment by harish-sethuraman** [comment]
@danilowoz FYI
