### ISSUE TITLE
A clean alternative solution to redenring-list first problem

### ISSUE THREAD

**Issue by MithrilMan** [reactjs/react.dev#6500]
I was reading the documentation about Rendering Lists in the "Describing The UI" section.
I like how docs are implemented and I'd like to add an alternative approach to the solutions on the 1st challenge

you suggest to use people.forEach, what about suggesting array.reduce ?

instead of
```
let chemists = [];
let everyoneElse = [];
people.forEach(person => {
  if (person.profession === 'chemist') {
    chemists.push(person);
  } else {
    everyoneElse.push(person);
  }
});
```

you can have something like

```
const result = people.reduce((accumulator, person) => {
    const array = person.profession === 'chemist' 
      ? accumulator.chemists
      : accumulator.everyoneElse;
    array.push(person);
    return accumulator;
  }, {
    chemists :[],
    everyoneElse : []
  });
  ```

of course instead of accessing directly chemists and everyoneElse you'll have to access result.chemists and result.everyoneElse 

I think that having an example about array.reduce could be a nice addition to the proposed solutions.

**Comment by rickhanlonii** [comment]
`reduce`is hard to understand for people learning React, so let's keep as is.
