### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Whevalmeze** [reactjs/react.dev#6514]
## broken link from Coursera to the react docs on useState.
link found below;
[useState](https://react.dev/apis/react/useState#usestate)

**Comment by harish-sethuraman** [comment]
We see a lot of people reporting this issue. Is it possible to report this to coursera/author of the course that link has changed to https://react.dev/reference/react/useState ?

**Comment by rickhanlonii** [comment]
We can't fix this, Coursea will need to fix it.
