### ISSUE TITLE
Bug: Quotation marks around inline code go the wrong way

### ISSUE THREAD

**Issue by 2wheeh** [reactjs/react.dev#6522]
1. useLayoutEffect
<img width="817" alt="image" src="https://github.com/reactjs/react.dev/assets/40269597/0c951af3-4578-4e90-84f2-c2d0f082244a">

2. state-a-components-memory
<img width="159" alt="image" src="https://github.com/reactjs/react.dev/assets/40269597/43a36429-9dba-4796-90aa-2f2cccfe5c8c">

**Comment by 2wheeh** [comment]
The root cause is in `remark-smartypants` and it's fixing here: https://github.com/silvenon/remark-smartypants/pull/80

**Comment by dimaMachina** [comment]
This was fixed in the last version of remark-smartypants
