### ISSUE TITLE
Invalid link on the forwardRef page

### ISSUE THREAD

**Issue by bielarusajed** [reactjs/react.dev#6525]
Hi, on the page about `forwardRef` there is a link to a section, that doesn't exist:

> In Strict Mode, React will **call your render function twice** in order to [**help you find accidental impurities.**](#my-initializer-or-updater-function-runs-twice) This is development-only behavior and does not affect production. If your render function is pure (as it should be), this should not affect the logic of your component. The result from one of the calls will be ignored.

Here: https://github.com/reactjs/react.dev/blob/bbb08a5a04b0221137e5d60472fc979747af2954/src/content/reference/react/forwardRef.md?plain=1#L45C6-L45C6

Is there really a missing section, or that's an extra link, accidentally copied from the `useState` page?

**Comment by rickhanlonii** [comment]
Thanks for reporting! I pushed a PR to fix the link.
