### ISSUE TITLE
Bug: Feedback component visible all the time after submission

### ISSUE THREAD

**Issue by Abdul-Rahman-E** [reactjs/react.dev#6531]
![Screenshot 2024-01-05 174029](https://github.com/reactjs/react.dev/assets/82259777/31fbd221-d376-4222-8d3b-cd22f1ffd44b)
![Screenshot 2024-01-05 072242](https://github.com/reactjs/react.dev/assets/82259777/979b699e-3972-40fc-ba4c-283110fa966b)
The feedback component is always hiding the text behind it and not going away even after submission. It gives the user a hard time reading the sidebar.
The problem can be seen in the Learn, Reference, and Community pages.

**Comment by rickhanlonii** [comment]
Fixed by https://github.com/reactjs/react.dev/pull/6533
