### ISSUE TITLE
Endless stream of comments from contributors asking if they can work on an issue

### ISSUE THREAD

**Issue by sbassong** [reactjs/react.dev#6555]
_This might have been addressed already, or it might go against ReadMe's guidelines or format. In which case, my bad; please close._

**But given the recurring problem of people asking whether an issue can be assigned to them or if they could work on it, would it help to include a statement in the ReadMe letting people know to work on the issue and submit a PR if it's open?**

It won't completely solve the problem, but I can't imagine the time wasted (and headaches induced) from replying to so many people.

**Comment by BartoszKlonowski** [comment]
Hello @sbassong, thank you for sharing!
Yes, in general (at least in my opinion) the good practice in open source is to first check if an issue is "good to go" in terms of what is exactly to be done there, and secondly check if there's no one already working on it. Usually a `"I would like to work on it"` comment is sufficient to mark it and as well as to consider it as "taken".
However, there are some edge cases that would have to be precisely and thoughtfully described, so it's not that straightforward.
I will mark it as a discussion and reach out to the team.

**Comment by rickhanlonii** [comment]
Thanks for the suggestion, but I'm skeptical this would help and we're fine continuing to ignore it or reply.
