### ISSUE TITLE
Application error: a client-side exception has occurred on official React.dev site

### ISSUE THREAD

**Issue by emthaa** [reactjs/react.dev#6556]
When accessing react.dev website on iPhone SE and multiple different browsers it loads the website for a split second then this message pops up:
![48B94383-410C-46B1-9C8F-64C0F189C49F](https://github.com/reactjs/react.dev/assets/110277522/c8372223-b0bb-46c7-8799-8c1c32b038bb)

**Comment by itsjohncs** [comment]
I can reproduce this on Safari Desktop 16.0 with extensions disabled. In the console I get a regex error (see below) and links to error codes [418](https://react.dev/errors/418?invariant=418) and [423](https://react.dev/errors/423?invariant=423).

The regex error is `SyntaxError: Invalid regular expression: invalid group specifier name`. Looking at the traceback leads me to the regex (in the minified code): `((?<!\\+)https?:\\/\\/(?:www\\.)?(?:[-\\w.]+?[.@][a-zA-Z\\d]{2,}|localhost)(?:[-\\w.:%+~#*$!?&/=@]*?(?:,(?!\\s))*?)*)`

**Comment by vvtommy** [comment]
Safari (of course including wkwebview) does not support lookbehind 🤷🏻‍♂️

**Comment by rickhanlonii** [comment]
Thanks for reporting, this was broken last week with https://github.com/reactjs/react.dev/pull/6214

Fixed in https://github.com/reactjs/react.dev/pull/6571

**Comment by rickhanlonii** [comment]
Confirmed that the fix is live, thanks again!
