### ISSUE TITLE
broken Link !

### ISSUE THREAD

**Issue by unclepacky** [reactjs/react.dev#6566]
following the link : https://react.dev/docs/forms#handling-multiple-submit-buttons 
leads to not found page.
This link is present in 
https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions-and-mutations
See the [React <form> docs](https://react.dev/docs/forms#handling-multiple-submit-buttons)

**Comment by pwbriggs** [comment]
Hey there, @unclepacky! 👋

Thanks for reporting this issue! This looks like an issue on Next.js' end, so I've opened an issue on their repo: vercel/next.js#60953.

Because the issue is now on the other repo, do you mind closing this issue? Thanks!

**Comment by unclepacky** [comment]
Closed

 

Best regards

Claude Aoun
