### ISSUE TITLE
Social Icons not Vertically centered in Footer Section

### ISSUE THREAD

**Issue by muhammadhafijur** [reactjs/react.dev#6579]
On the **Footer section**, Social icons are not centered vertically. I added the `items-center` class and it will fix this issue. 

| **BEFORE** | **AFTER** | 
|-------- | ------ | 
| ![Screenshot from 2024-01-24 12-52-12](https://github.com/reactjs/react.dev/assets/85216180/71c4ca42-2690-453f-8e91-147fd17c2105) | ![Screenshot from 2024-01-24 12-52-04](https://github.com/reactjs/react.dev/assets/85216180/7fbd582f-41c1-4d06-a654-708753172aa5) |

**Comment by rickhanlonii** [comment]
Fixed by https://github.com/reactjs/react.dev/pull/6580
