### ISSUE TITLE
Resetting state docs improvement 02

### ISSUE THREAD

**Issue by KennethKinLum** [reactjs/react.dev#6581]
Over here: https://react.dev/learn/preserving-and-resetting-state#same-component-at-the-same-position-preserves-state

I think it may be worthwhile to state that:

```jsx
return (
    <div>
      {isFancy ? (
        <Counter isFancy={true} /> 
      ) : (
        <Counter isFancy={false} /> 
      )}
```
it looks like a different `<Counter />` is returned, depending on whether `isFancy` is true or false.

However, even with the simple case of

```jsx
  return <Counter isFancy={isFancy} />;
```
a different `<Counter />` is returned each time. That's because the JSX becomes `React.createElement( ... )`, so every time, a new element is created. It doesn't matter if it is one line or two places or 12 places that produce a `<Counter />`.

**Comment by rickhanlonii** [comment]
They are the same `<Counter>`. When it switches from `true` to `false`, the same component instance is updated - a new one is not created. So it's the same `<Counter />` is used each time. It's true that `createElement` returns a new object every time, but React uses the information in that object to determine if it should update the component instance or create a new one, using the position and key rules that docs explains.
