### ISSUE TITLE
Incorrect href in React learning documentation

### ISSUE THREAD

**Issue by Illdowhatiwant** [reactjs/react.dev#6582]
https://ko.react.dev/learn/updating-arrays-in-state#making-other-changes-to-an-array

On the above page, the href attribute for '중첩된 JavaScript 객체 업데이트' is incorrect.
It should be corrected to https://ko.react.dev/learn/updating-objects-in-state#updating-a-nested-object.

The translated learning documentation has helped me a lot in my learning.
Thank you.

**Comment by harish-sethuraman** [comment]
Hey the Korean translations are being maintained here https://github.com/reactjs/ko.react.dev/issues. I have created a copy for the same. Thanks for raising.

**Comment by pwbriggs** [comment]
@Illdowhatiwant do you mind closing this copy of the issue, now that it's been moved to the correct repository?

Thanks! 😄
