### ISSUE TITLE
Not found(ko.react.dev)

### ISSUE THREAD

**Issue by KoGaYoung** [reactjs/react.dev#6603]
The "Performance" link in the Optimizing performance part of the "https://ko.react.dev/learn/render-and-commit" page is incorrectly linked.

incorrect link: https://ko.react.dev/learn/performance
correct link: https://legacy.reactjs.org/docs/optimizing-performance.html

**Comment by pwbriggs** [comment]
Hey there, @KoGaYoung! 👋

The Korean translation of the React documentation is maintained in the `reactjs/ko.react.dev` repo. I've opened a PR there (reactjs/ko.react.dev#856) to fix this link.
