### ISSUE TITLE
Inavlid hook call

### ISSUE THREAD

**Issue by ankitadeshpande128** [reactjs/react.dev#6611]
```js
import React from "react";
import { Text,View,TouchableOpacity ,TextInput} from "react-native";
import { useEffect } from "react";

const NewInvoice=(props)=>{
    useEffect(()=>{
        console.log("New INvoice")
        return(
            <View>
                <TextInput placeholder='Enter Customer' />
            </View>
        )
    },[]);
}

export default Stack4 = (props) => {
    return(
        <View>
           <TouchableOpacity onPress={(props) => NewInvoice(props)}>
             <Text>New Invoice</Text>
             </TouchableOpacity>
        </View>
    )
}
```

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://react.dev/link/invalid-hook-call for tips about how to debug and fix this problem., js engine: hermes

**Comment by rickhanlonii** [comment]
The issue is here:
```js
 onPress={(props) => NewInvoice(props)}
 ```

**Comment by pwbriggs** [comment]
(@rickhanlonii the URL in your comment is broken. Perhaps you forgot a bracket?)
