### ISSUE TITLE
[Bug]: all new sandboxes (with ShowRenderedHTML) break

### ISSUE THREAD

**Issue by tdd** [reactjs/react.dev#6612]
### Summary

Pretty much all new sandboxes break in last week's work. Noticed this on yesterday's weekly translation sync.

Every single sandbox with this component breaks. I included just one example page.

### Page

https://react.dev/reference/react-dom/components/link#linking-to-related-resources

### Details

![Capture d’écran 2024-02-06 à 09 44 28](https://github.com/reactjs/react.dev/assets/3752/2e626350-9cf3-41b6-8d6b-2d1eb287b0a2)

**Comment by rickhanlonii** [comment]
I think this was broken in https://github.com/reactjs/react.dev/pull/6496

cc @mattcarrollcode @geeseyj

**Comment by mattcarrollcode** [comment]
Thanks for the bug report @tdd ! I'm looking into it now. Seems like the problematic component is `SandpackWithHTMLOutput`
