### ISSUE TITLE
Left-Scroll-Bar[Bug]: 

### ISSUE THREAD

**Issue by ibrartalab** [reactjs/react.dev#6621]
### Summary

The left side scroll bar are not working properly, when someone want to scroll down .
So  like i am not just raised the issue ,but i also want to fix it.
![reactdev](https://github.com/reactjs/react.dev/assets/126334526/ea0407a7-3a4b-4b3b-ae15-1ae0720d2bfc)

### Page

https://react.dev/learn

**Comment by rickhanlonii** [comment]
Fixed by https://github.com/reactjs/react.dev/pull/6329

**Comment by ibrartalab** [comment]
Yeah! sure

**Comment by pwbriggs** [comment]
(to be precise, the fix was actually merged in #6586, not #6329. But in any case, it's fixed now. 🎉)
