### ISSUE TITLE
[Typo]: `<style>` syntax looks wrong

### ISSUE THREAD

**Issue by mayank99** [reactjs/react.dev#6633]
### Summary

The new [`<style>` page](https://react.dev/reference/react-dom/components/style) shows this snippet at the very top:

```html
<style> p { color: red; } </style>
```

While it is totally valid in regular HTML, it does *not* work in JSX (would be nice if it did though).

```console
Error

/src/App.js: Unexpected token, expected "}" (3:21)

  1 | export default function App() {
  2 |   return (
> 3 |     <style> p { color: red; } </style>
    |                      ^
  4 |   );
  5 | }
  6 |
```

### Page

https://react.dev/reference/react-dom/components/style

### Details

I believe JSX requires this workaround:

```jsx
<style>{` p { color: red; } `}</style>
```

**Comment by rickhanlonii** [comment]
Fixed in https://github.com/reactjs/react.dev/pull/6641
