### ISSUE TITLE
[Bug]: Challenges section not connecting to sandbox

### ISSUE THREAD

**Issue by sumit181sk** [reactjs/react.dev#6644]
### Summary

After solving the challenge correctly, the code gets disconnected from sandbox.
![Screenshot (116)](https://github.com/reactjs/react.dev/assets/70004987/89b64f93-4fc1-4eec-9478-96155f2c9258)

### Page

https://react.dev/learn/writing-markup-with-jsx

**Comment by esau-morais** [comment]
i've got to reproduce once, but it might be related to codesandbox, not to react.dev

**Comment by pwbriggs** [comment]
Reproduced in Chrome, Edge, and Firefox. Sometimes the error appears before the challenge is completely solved, or even with no interaction. I checked the network log in DevTools, and I don't see any failed requests, so I don't think it's (directly) related to the network.

**Comment by rickhanlonii** [comment]
Also confirmed, but no idea what's failing. Have you seen this before @danilowoz?

**Comment by danilowoz** [comment]
It must be a bug in the timeout handle on the Sandpack instance, I will take a look as soon as possible
