### ISSUE TITLE
[Mistake]: One of the examples in the docs is performing side effect in render?

### ISSUE THREAD

**Issue by gmoniava** [reactjs/react.dev#6660]
### Summary

React docs warn us to not perform side effects during render (or even inside the body of hook like `useMemo`).
However, here: https://react.dev/reference/react-dom/hooks/useFormStatus#read-form-data-being-submitted,
it seems that is what is happening:

`      submittedUsername.current = data?.get('username');
`

Isn't writing to ref a side effect?

Actually there is single place in [docs ](https://react.dev/learn/you-might-not-need-an-effect#adjusting-some-state-when-a-prop-changes) which allows to do side effect (change state) during render if it is wrapped inside certain condition,
however, even there they warn against DOM manipulation:

> A condition like items !== prevItems is necessary to avoid loops. You may adjust state like this, but any other side effects (like changing the DOM or setting timeouts) should stay in event handlers or Effects to [keep components pure.](https://react.dev/learn/keeping-components-pure)

### Page

https://react.dev/reference/react-dom/hooks/useFormStatus#read-form-data-being-submitted

**Comment by pwbriggs** [comment]
Yes, you are correct.

Someone just spotted this error a few hours ago, and a fix is in progress at #6658.

**Comment by gmoniava** [comment]
Thanks; I suppose I can close this then ...
