### ISSUE TITLE
[Bug]: Can not access the react.dev website 

### ISSUE THREAD

**Issue by Abd-Alwahab** [reactjs/react.dev#6661]
### Summary

Hey there, I'm a software developer from Iraq. I tried to open the official React website (React: https://react.dev/) but I got an error telling me "This site can't be reached." When I tried with a VPN, it worked. I hope you can help me with this problem, as I use React for pretty much all my projects and being unable to access the official docs really limits my learning experience.

### Page

https://react.dev/

### Details
![Screenshot 2024-02-24 at 6 59 22 PM](https://github.com/reactjs/react.dev/assets/45470303/dc4fc319-bf90-4b55-bc9e-4fb95ac18098)

_No response_

**Comment by bondz** [comment]
This might be an issue with how your DNS resolves locally. See [this article](https://superuser.com/questions/1413402/i-cant-visit-websites-that-have-dev-domain)

**Comment by pwbriggs** [comment]
Hmm, interesting. @Abd-Alwahab can you access other `.dev` domains like https://get.dev?

If you can, maybe there's a firewall misclassifying and blocking `react.dev` as social media because of it's relation to Facebook?

**Comment by Abd-Alwahab** [comment]
> This might be an issue with how your DNS resolves locally. See [this question](https://superuser.com/questions/1413402/i-cant-visit-websites-that-have-dev-domain)

I tried what is mentioned in that question but ti did not work for, I do not have any DNS resolvers for dev domains

**Comment by Abd-Alwahab** [comment]
> Hmm, interesting. @Abd-Alwahab can you access other `.dev` domains like https://get.dev?
> 
> If you can, maybe there's a firewall misclassifying and blocking `react.dev` as social media because of it's relation to Facebook?

I tried to open the [https://get.dev/ ](https://get.dev/ ) and it worked for me , also I tried with other websites that have the .dev and also I could access them , I think its specific to react.dev

**Comment by bondz** [comment]
Are you by any chance behind a firewall or proxy?

If you are not on a corporate network, can you try changing your DNS resolvers temporarily to a public one like [1.1.1.1](https://1.1.1.1/help) or [8.8.8.8](https://developers.google.com/speed/public-dns)?

**Comment by Abd-Alwahab** [comment]
> Are you by any chance behind a firewall or proxy?
> 
> If you are not on a corporate network, can you try changing your DNS resolvers temporarily to a public one like [1.1.1.1](https://1.1.1.1/help) or [8.8.8.8](https://developers.google.com/speed/public-dns)?

Actually, I am using a brand new macOS machine, I do not know if there is a firewall or proxy, also I am on my home network ,by the way, when I use a VPN software, it opens with no problems, do you think it geolocation problem?

**Comment by Abd-Alwahab** [comment]
> changing your DNS resolvers temporarily to a public one like [1.1.1.1](https://1.1.1.1/help) or [8.8.8.8](https://developers.google.com/speed/public-dns)?

Also changing my DNS resolvers did not work for me, by the way, I tried from different devices (mobile, other laptop) and it did not work for me, also I tried from a different network and it did not work for me.

**Comment by EOEboh** [comment]
This issue has NOT been resolved. I’m currently in Nigeria and I cannot access the react.dev site from various ISPs. 

Can one of the maintainers check this?

**Comment by zaini** [comment]
I'm hosting a copy of the repo on Vercel if anyone would like to use that until this is resolved: https://react-dev-silk.vercel.app/

**Comment by Abd-Alwahab** [comment]
The problem has been resolved for Iraq so I am closing this issue.
