### ISSUE TITLE
[Suggestion]: Add a new page for how to communicate between components.

### ISSUE THREAD

**Issue by woochanleee** [reactjs/react.dev#6676]
### Summary

Add a new page for how to communicate between components.

### Details

I think it would be helpful to have a page that explains how to communicate between components. This could include a best practice example of a communication between two components that **don't have a parent-child relationship.**

In the past, old React docs already had these content. 
https://web.archive.org/web/20151124041030/http://facebook.github.io:80/react/tips/communicate-between-components.html

#### References

https://stackoverflow.com/questions/21285923/how-can-i-communicate-between-related-react-components#comment45951998_21285923

**Comment by rickhanlonii** [comment]
This is documented on these pages, depending on what you're looking to achieve:
- [Passing props to a component](https://react-dev-git-fork-rickhanlonii-rh-link-hydra-fbopensource.vercel.app/learn/passing-props-to-a-component)
- [Passing event handlers as props](https://react-dev-git-fork-rickhanlonii-rh-link-hydra-fbopensource.vercel.app/learn/responding-to-events#passing-event-handlers-as-props)
- [Sharing state between components](https://react-dev-git-fork-rickhanlonii-rh-link-hydra-fbopensource.vercel.app/learn/sharing-state-between-components)
- [Passing data deeply with context](https://react-dev-git-fork-rickhanlonii-rh-link-hydra-fbopensource.vercel.app/learn/passing-data-deeply-with-context)

The `.bind` specific technique is briefly mentioned in the Legacy Component docs [here](https://react-dev-git-fork-rickhanlonii-rh-link-hydra-fbopensource.vercel.app/reference/react/Component#constructor), but `createReactClass` is deprecated and will not be added to the new site. See the [legacy site](https://legacy.reactjs.org/docs/react-without-es6.html) for `createReactClass` docs.

**Comment by woochanleee** [comment]
Nowhere in the documentation does it say.

> For communication between two components that don't have a parent-child relationship, you can set up your own global event system. (Old React Docs said)

Is using a global event system not a good practice and only context(or lifting state up) is  best practice?

**Comment by rickhanlonii** [comment]
Correct, the only way to do it safely with concurrent features today is to de-opt with useSyncExternalStore, which has limitation such as forcing fallbacks for existing content. We're aware this is a pain point, though we don't have any solutions to recommend until we build better support for it.

**Comment by woochanleee** [comment]
Thank you. I found an example that uses `useSyncExternal`, I'll check it out.

https://github.com/facebook/react/issues/14988#issuecomment-1082479229
https://codesandbox.io/p/sandbox/hopeful-sara-fb970f?file=%2Fsrc%2Findex.js%3A1%2C1-47%2C1
