### ISSUE TITLE
[Mistake]: getVisibleTodos() does not re-run (and does not print any logs) when you type into the input to begin with!

### ISSUE THREAD

**Issue by TheMaskedGuy** [reactjs/react.dev#6682]
### Summary

The second objective (highlighted below) of the challenge is the default behavior of the starting base code. 
<img width="1440" alt="image" src="https://github.com/reactjs/react.dev/assets/78201744/1b0cbc72-fce1-4691-8cf2-25e9646b1b2e">

### Page

https://react.dev/learn/you-might-not-need-an-effect#challenges

### Details

Challenge Objective:
"Your task is to remove the Effect that recomputes the visibleTodos list in the TodoList component. However, you need to make sure that getVisibleTodos() does not re-run (and so does not print any logs) when you type into the input."

While the first half I did with useMemo, (Valid Challenge)
The second half, where we're supposed to make sure that "getVisibleTodos() does not re-run (and so does not print any logs) when we type into the input" but it is the default behavior of the code, even without any changes to the base starter code, this is how it behaves to begin with. So I feel it's a mistake and should be improved...

**Comment by pwbriggs** [comment]
@TheMaskedGuy the challenge is to remove the `useEffect` *while still* not calling `getVisibleTodos()` every time the input changes:

> Your task is to remove the Effect that recomputes the visibleTodos list in the TodoList component. **However**, you need to make sure that getVisibleTodos() does not re-run (and so does not print any logs) when you type into the input.

Hope this helps! ❤️

**Comment by TheMaskedGuy** [comment]
My bad, thanks for clearing that out. I seemed to have skimmed over the " _while still not calling_ " part.
