### ISSUE TITLE
中文文档已经ui变形了

### ISSUE THREAD

**Issue by bob-dw** [reactjs/react.dev#6683]
中文文档已经ui变形了 css加载404 赶紧修一修吧

**Comment by pwbriggs** [comment]
Hey there @bob-dw! 👋

https://zh-hans.react.dev appears to be loading correctly for me. Is there any specific URL that's not working for you?

![image](https://github.com/reactjs/react.dev/assets/146312751/d320ba75-66d5-4118-afbf-1aab102278ed)

Thanks! ❤️
