### ISSUE TITLE
te.react.dev Maintainer's Issue

### ISSUE THREAD

**Issue by srikanth-kandi** [reactjs/react.dev#6690]
Hello React Community,

Because I received no response on the reactjs/translations.react.dev#313 issue, I'm escalating this issue as mentioned in [Adding a maintainer](https://github.com/reactjs/translations.react.dev?tab=readme-ov-file#adding-a-maintainer) of translations.react.dev repository.

> If the translation's existing maintainers become unresponsible for more than a month, please raise an issue on this repository. If you don't receive a response in a week, please escalate the issue to the main React repository.

Thank you

**Comment by rickhanlonii** [comment]
Hi @srikanth-kandi thanks for flagging and sorry for the delay, I've added you as a maintainer.

**Comment by srikanth-kandi** [comment]
![image](https://github.com/reactjs/react.dev/assets/87417638/9bb55f3e-01c1-4abf-8534-4b7a54dcb727)

on the pull request, reactjs/te.react.dev#87 it was showing like this as above.

And I'm unable to approve the pull request which made my me like reactjs/te.react.dev#80

**Comment by rickhanlonii** [comment]
Fixed, see my comment on https://github.com/reactjs/react.dev/issues/6709!
