### ISSUE TITLE
[Bug]: Search functionality not working correctly on react.dev in Safari on iOS real device (iPhone 12 Pro)

### ISSUE THREAD

**Issue by MeetYourCreator** [reactjs/react.dev#6693]
## The current behavior
Search functionality does not work correctly on iOS real device (iPhone 12 Pro). 

https://github.com/reactjs/react.dev/assets/57572988/f50ff514-d84b-4e8c-b067-628eedd2d762

Since search functionality is currently working as expected on macOS, both in Chrome and Safari, the issue might be in implementation of [Algolia InstantSearch iOS](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/ios/):

https://github.com/reactjs/react.dev/assets/57572988/44ddea01-cd10-4323-bcdb-aec1788da64d

---

## The expected behavior

Search functionality is working as expected on macOS, both in Chrome and Safari. Should work similarly on iOS real device:

**macOs Chrome**

https://github.com/reactjs/react.dev/assets/57572988/41c9cd76-3ac8-4820-9917-52141d68c8ed

**macOS Safari**

https://github.com/reactjs/react.dev/assets/57572988/4daf9a68-2671-446c-a9c3-8a39bfefc8e5

### Page

https://react.dev

## Steps To Reproduce

1. Open react.dev in Safari on iPhone (real device)
2. Tap search icon: note that search function is working as intended
3. Scroll down to "Write components with code and markup" section
4. Tap search icon: note that action doesn't open search
5. Scroll down again and tap the search icon several times:  note that action doesn't open search
6. Repeat step 5: note that eventually screen freezes
___

The iOS real device that this behavior was recorded on is using the current iOS version:

![react_github-bug-report_ios-version](https://github.com/reactjs/react.dev/assets/57572988/3401650a-bc2a-4599-9f27-2d8519f6ab32)

**Comment by MeetYourCreator** [comment]
Hi @pwbriggs👋 
I was wondering if I could open a pull request and begin work on this issue.

**Comment by pwbriggs** [comment]
Go ahead, @MeetYourCreator! Thanks in advance for the help!

**Comment by MeetYourCreator** [comment]
Hi @pwbriggs 👋
I'm about to open a PR for this bug-fix. Since it's my first time contributing, I just want to make sure I have the right protocol for opening a PR for this repo:

1. fork repo
2. clone forked repo to local machine
3. when ready, git push my-fork-name my-branch-name

**Comment by pwbriggs** [comment]
Yes, that's correct. Commit the changes to the branch on your fork, then open your fork on GitHub. You should see a message something like this:

![image](https://github.com/reactjs/react.dev/assets/146312751/d6110c7b-206d-4f18-9e17-25b4fb9851df)

Hit the "Contribute" button to start a pull request. Include "Fixes #6693" in the description so GitHub will automatically link it to this issue.

Thanks again! ❤️
