### ISSUE TITLE
[Typo]: There is a syntax mistake on react docs GetStarted/Installation/Using Typescript 

### ISSUE THREAD

**Issue by developeruzairsaleem** [reactjs/react.dev#6697]
### Summary

Hey I found this typo on docs under GetStarted/Installation/using Typescript page under the "useReducer" section, the code includes ";" but it should be ","

### Page

https://react.dev/learn/typescript

### Details

Hey I found this typo on docs under GetStarted/Installation/using Typescript page under the "useReducer" section, the code includes ";" but it should be ","
The code is written as follows
type CounterAction =
  | { type: "reset" }
  | { type: "setCount"; value: State["count"] }

With ";" in object it should be a "," after the type:"setCount"
The updated code should look like this
type CounterAction =
  | { type: "reset" }
  | { type: "setCount", value: State["count"] }
Thanks.

**Comment by pwbriggs** [comment]
Hey there, @developeruzairsaleem! 👋

The line you're referring to is not an object, it is an object *type*. In TypeScript, [`;` **or** `,` can be used in object types], and many codebases opt to use a semicolon to help differentiate the object type from an actual object.

[`;` **or** `,` can be used in object types]: https://www.typescriptlang.org/docs/handbook/2/objects.html#handbook-content:~:text=(person%3A-,%7B%20name%3A%20string%3B%20age%3A%20number%20%7D,-)%20%7B

**Comment by developeruzairsaleem** [comment]
Thanks By the way.
