### ISSUE TITLE
Should have a queue

### ISSUE THREAD

**Issue by Abhijeet1908** [reactjs/react.dev#6701]
<img width="1450" alt="Screenshot 2024-03-21 at 6 19 16 PM" src="https://github.com/reactjs/react.dev/assets/105696026/8e515d91-8a79-41c7-a579-b4a4de26923e">

**Comment by rickhanlonii** [comment]
If you have a sandbox that repro's the issue, I can re-open and investigate, but I can't really debug it without code.
