### ISSUE TITLE
[Typo]: Separating Events from Effects

### ISSUE THREAD

**Issue by ruthcyg** [reactjs/react.dev#6706]
### Summary

Event handlers only re-run when you perform the same interaction again. Unlike event handlers, 

### Page

https://react.dev/learn/separating-events-from-effects

### Details

In the first paragraph The comparison was between event handlers and event handlers instead of effects

**Comment by eps1lon** [comment]
> Unlike event handlers, Effects re-synchronize if some value they read, like a prop or a state variable, is different from what it was during the last render. 

I don't see how the comparison was not made between Effects and event handlers

**Comment by ruthcyg** [comment]
**Event handlers** only re-run when you perform the same interaction again. Unlike **event handlers**,
