### ISSUE TITLE
te.react.dev push access issue

### ISSUE THREAD

**Issue by srikanth-kandi** [reactjs/react.dev#6709]
![image](https://github.com/reactjs/react.dev/assets/87417638/9bb55f3e-01c1-4abf-8534-4b7a54dcb727)

On the pull request, reactjs/te.react.dev#87 it was showing like this as above.

And I'm unable to approve the pull request which made my me like reactjs/te.react.dev#80

_Originally posted by @srikanth-kandi in https://github.com/reactjs/react.dev/issues/6690#issuecomment-2017093574_

I think this might be because I've given only the write access to the repository, so please give me another access like `admin` or `owner` access.

Thank you

**Comment by rickhanlonii** [comment]
Fixed, but if I were you, I would probably remove the `main` branch protections so anyone with `write` access can merge a PR.
