### ISSUE TITLE
Add a Dynamic Footer

### ISSUE THREAD

**Issue by mthirumalai2905** [reactjs/react.dev#6725]
### Summary

Please update your footer Use a Dynamic Footer
![Screenshot (251)](https://github.com/reactjs/react.dev/assets/98790479/85c9d278-2978-4d33-a3a7-f5b7614273bb)

### Page

https://react.dev/

### Details

Use a dynamic Footer

**Comment by rickhanlonii** [comment]
Already is https://github.com/reactjs/react.dev/blob/30f23d7651c8cb2fb848863b39292840850a130d/src/components/Layout/Footer.tsx#L286
