### ISSUE TITLE
⚠Phishing Website Warning!!! There are phishing website links in the document. 

### ISSUE THREAD

**Issue by ouweiya** [reactjs/react.dev#6753]
### Summary

**Phishing Website Warning!!! There are phishing website links in the document.**

Document address: 
https://react.dev/learn/referencing-values-with-refs#adding-a-ref-to-your-component

Phishing website:
http://rachelnabors.com/

This domain is very cunning, redirecting to different websites based on the region of the request. If it's a user from the United States, it redirects to https://nearestnabors.com/. If it's from an Asian country, it redirects to a gambling website.

https://github.com/reactjs/react.dev/assets/28357731/bcd6d094-966b-4502-8b26-a029aa7d47b5

**IP USA：**

https://github.com/reactjs/react.dev/assets/28357731/2b305cbe-6978-4ac2-992a-3fe450dd395b

**IP HongKong:**

https://github.com/reactjs/react.dev/assets/28357731/4a7106da-1934-4b54-80b0-8de904d58a76

### Page

https://react.dev/learn/referencing-values-with-refs#adding-a-ref-to-your-component

**Comment by jackpope** [comment]
Resolved with https://github.com/reactjs/react.dev/pull/6754
