### ISSUE TITLE
[Bug]: photos in ref section of the tutorial are down

### ISSUE THREAD

**Issue by shahar-cohen** [reactjs/react.dev#6758]
### Summary

photos in the tutorial sections:
- Manipulating the DOM with Refs (also notice the first deep dive section!)
- Referencing Values with Refs

Aren't displayed. It seems like the hosting server is down.

### Page

https://react.dev/learn/referencing-values-with-refs, https://react.dev/learn/manipulating-the-dom-with-refs

### Details

for example:
https://placekitten.com/g/200/200

**Comment by includerajat** [comment]
@shahar-cohen which photos actually you are referring, I think, issue is fixed now, because I am unable to find any photo which is not visible or not loaded.

**Comment by harish-sethuraman** [comment]
Yea seems like these images are missing as their server is down. we have other occurrences of same URL here: https://github.com/search?q=repo%3Areactjs%2Freact.dev%20https%3A%2F%2Fplacekitten.com&type=code

cc: @rickhanlonii

**Comment by hirotomoyamada** [comment]
@rickhanlonii @harish-sethuraman 

Hi! If that's the case, would you like me to do this work for you?

**Comment by rickhanlonii** [comment]
Fixed in https://github.com/reactjs/react.dev/pull/7189

**Comment by rrowe404** [comment]
@rickhanlonii this should be re-opened as loremflickr is no longer serving images, see 'No more hosting' / 'Updates' section on https://loremflickr.com

**Comment by rickhanlonii** [comment]
I opened a new issue: https://github.com/reactjs/react.dev/issues/7966
