### ISSUE TITLE
directives page is not found 

### ISSUE THREAD

**Issue by Vjndevshopify** [reactjs/react.dev#6794]
https://react.dev/reference/react/directives
its not available , can you please check 
![reactdirectivepage](https://github.com/reactjs/react.dev/assets/150022382/bc9f8938-d72f-422a-9b63-ce15193a248c)

**Comment by sri-falconavl** [comment]
They are available at [https://react.dev/reference/rsc/directives](https://react.dev/reference/rsc/directives)
