### ISSUE TITLE
'use server' reference page does not exist in the doc

### ISSUE THREAD

**Issue by mootookoi** [reactjs/react.dev#6799]
This link returns a 404 [https://react.dev/reference/react/use-server](https://react.dev/reference/react/use-server).

I am trying to understand the differences between 'use server' and server-only.

For what I understand, server-only is to forbid Client Component to access functions or files where it is imported.

And 'use server' is used to enable server actions. 

So in my mind, I prefer call them 'use action' ^^

But because of the non existing ref page, I can't be sure =)

**Comment by eps1lon** [comment]
[react.dev/reference/rsc/use-server](https://react.dev/reference/rsc/use-server) should work until we add redirects: https://github.com/reactjs/react.dev/pull/6800
