### ISSUE TITLE
references/react-dom/components/button link in 20240425 blog post results to Not Found page

### ISSUE THREAD

**Issue by shiba-hiro** [reactjs/react.dev#6807]
I found that one of the links in 20240425 blog post results to Not Found page.  
(and I read the message `If this is a mistake, let us know, and we will try to fix it!` there, so that I report just in case)

Code:  
https://github.com/reactjs/react.dev/blob/01edd5c1070c2c563f86ee508cff3e8cca6a36c3/src/content/blog/2024/04/25/react-19.md?plain=1#L189

The URL I was navigated to:  
https://react.dev/reference/react-dom/components/button

**Comment by Rekl0w** [comment]
There is no `button.md` for now i guess.

**Comment by rickhanlonii** [comment]
Fixed by https://github.com/reactjs/react.dev/pull/6813

Thanks for reporting!
