### ISSUE TITLE
[Typo]: 选择stat结构所给答案错误

### ISSUE THREAD

**Issue by caiwenju** [reactjs/react.dev#6812]
### Summary

尝试一些挑战的第三题的答案错了：

### Page

https://react.docschina.org/learn/choosing-the-state-structure

### Details

尝试一些挑战的第三题的答案错了：
onHover={handleHover} 应该是：onHover={()=>handleHover(letter.id)} 
onToggleStar={handleStar}应该是：onToggleStar={e=>handleStar(letter.id)}

**Comment by harish-sethuraman** [comment]
Its fine as we are doing the same from inside of the Letter component in the solution.
