### ISSUE TITLE
the results shoude be 1,2,3 instead of 2,4,6[Bug]: 

### ISSUE THREAD

**Issue by zhiyixu** [reactjs/react.dev#6857]
### Summary

![is this result correct? ](https://github.com/reactjs/react.dev/assets/97584093/300d0a3f-eb8a-478c-84c7-3ba757c0312c)  
I have test the code on other webset and the result is 1,2,3.

![result from https://playcode.io/react ](https://github.com/reactjs/react.dev/assets/97584093/95bd671b-de04-4bd6-9831-4041261fbe16)

### Page

https://react.dev/learn/describing-the-ui

### Details

see summary.

**Comment by harish-sethuraman** [comment]
It is 2,4,6 because of strict mode. Probably you have disabled strict mode where you have tested
