### ISSUE TITLE
[Bug]: https://fb.me/react-devtools doesn't resolve

### ISSUE THREAD

**Issue by carlinmack** [reactjs/react.dev#6865]
### Summary

In the console when using react a message like the following appears:

> Download the React DevTools for a better development experience: https://fb.me/react-devtools

This link does not resolve properly. It points to 
* https://react.dev/blog/2015/09/02/new-react-developer-tools.html#installation

The only working link is:
* https://legacy.reactjs.org/blog/2015/09/02/new-react-developer-tools.html

### Page

https://react.dev/blog/2015/09/02/new-react-developer-tools.html#installation

**Comment by Rekl0w** [comment]
Hangi react sürümünü kullanıyorsunuz? Son sürüm çalışan bağlantıya yönlendiriyor.

**Comment by Rekl0w** [comment]
Which version do you use of react ? Latest version redirects to working link.

**Comment by carlinmack** [comment]
I think fixing the redirect is a better solution to this issue

**Comment by carlinmack** [comment]
You fix a redirect by changing https://fb.me/react-devtools to redirect to https://react.dev/learn/react-developer-tools I thought perhaps the people managing this repo would know who to contact

**Comment by Rekl0w** [comment]
I did not fixed it. It already fixed on react's repo. This is react's website repo. There is no redirect about it. The code that i referred is from react's repo.

[See from here](https://github.com/facebook/react/blob/26f24960935cc395dd9892b3ac48249c9dbcc195/packages/react-dom/src/client/ReactDOMClient.js#L72)

**Comment by carlinmack** [comment]
Closing as this is unproductive

**Comment by rickhanlonii** [comment]
Thanks for flagging @carlinmack, I fixed the shortlink as suggested [fb.me/react-devtools](https://fb.me/react-devtools)
