### ISSUE TITLE
[Bug]: Uncaught error was not captured by the uncaught error function part of create root.

### ISSUE THREAD

**Issue by CarreraPHP** [reactjs/react.dev#6868]
### Summary

![Screenshot 2024-05-12 at 8 20 07 PM](https://github.com/reactjs/react.dev/assets/422070/0fb08be1-d94d-4116-bb38-b3029830a72b)

Above error is because of react 17 react-dom.render method and it was not caught by the methods we added while creating root.

### Page

https://react.dev/blog/2024/04/25/react-19#error-handling

### Details

Below is the code that i have written in simple Vite app with react  & react-dom version as 19.x

![Screenshot 2024-05-12 at 8 20 37 PM](https://github.com/reactjs/react.dev/assets/422070/30386cc6-d403-41c4-ad9e-8ee83029bc44)

Below error is because of react 17 react-dom.render method and it was not caught by the methods we added while creating root.

![Screenshot 2024-05-12 at 8 20 07 PM](https://github.com/reactjs/react.dev/assets/422070/0fb08be1-d94d-4116-bb38-b3029830a72b)

While the vscode says it's a deprecated method but using it throws an uncaught error which is not caught by the newly introduced method. I believe some kind of message should be provided that createRoot/hydrateRoot methods are only methods to be used.

![Screenshot 2024-05-12 at 8 16 13 PM](https://github.com/reactjs/react.dev/assets/422070/d656f26f-c249-46ba-bdb5-3708058d726d)

![Screenshot 2024-05-12 at 9 50 58 PM](https://github.com/reactjs/react.dev/assets/422070/1c9894d1-2ffc-4da3-bfaf-0a6308de1d38)

If someone is going to migrate to react 19 for its new features, easiness and the compiler. they can try to migrate directly from v15 - v18 to v19. this uncaught error could make things difficult for them.

![Screenshot 2024-05-12 at 8 20 07 PM](https://github.com/reactjs/react.dev/assets/422070/0fb08be1-d94d-4116-bb38-b3029830a72b)

**Comment by eps1lon** [comment]
`onUncaughtError` applies only to errors that could have been handled by an Error Boundary. Calling `ReactDOM.render` could not have been caught by an Error Boundary since the root with the error handlers wasn't even created yet.
