### ISSUE TITLE
 higher-order components redirect broken

### ISSUE THREAD

**Issue by vipinvangara** [reactjs/react.dev#6873]
The link provided on  https://www.howtographql.com/advanced/0-clients/ for link embedded in line- 
 [higher-order components](https://facebook.github.io/react/docs/higher-order-components.html) is broken and takes you to page not found.

**Comment by includerajat** [comment]
Hi @vipinvangara, it seems like _howtographql_ needs to update their docs or it's good if `react` team provide supports their old links. 
In case you are wondering the where should it redirect, it should redirect [here](https://legacy.reactjs.org/docs/higher-order-components.html).

**Comment by harish-sethuraman** [comment]
This is more likely not a issue in react docs. Can you file a issue in their repo to replace it with different working link?
