### ISSUE TITLE
Error on HTML meta charset

### ISSUE THREAD

**Issue by murugappanrm** [reactjs/react.dev#6882]
Hi,

Why do i get an error for the "<meta charset="UTF-8" />"? Its says * Type '{ charset: string; }' is not assignable to type 'DetailedHTMLProps<MetaHTMLAttributes<HTMLMetaElement>, HTMLMetaElement>'

**Comment by harish-sethuraman** [comment]
Hey this is more likely not a problem with react documentation. Can you raise the issue where it belongs? If its coming from a package then at its repo?

**Comment by murugappanrm** [comment]
Thank you for all the help.
