### ISSUE TITLE
[Typo]: useDeferredValue parameters in react 18

### ISSUE THREAD

**Issue by s-cork** [reactjs/react.dev#6884]
### Summary

I read in the react 19 blogpost that `useDeferredValue` will support initialValue as an optional second parameter
but this is currently listed as a parameter in the docs for react 18
I think this is a mistake

### Page

https://18.react.dev/reference/react/useDeferredValue#usedeferredvalue

**Comment by eps1lon** [comment]
The docs state that this is a Canary-only feature.
