### ISSUE TITLE
Update CodePen examples to use latest React

### ISSUE THREAD

**Issue by bvaughn** [reactjs/react.dev#69]
IIRC currently they don’t. We should probably leave them using `latest` since if it breaks, we have to update them anyway.

**Edit** This issue is likely made unnecessary by the outcome #122

**Comment by bvaughn** [comment]
Auto-assigning to Dan since he owns most of the Codepens in question.

**Comment by sw-yx** [comment]
how can people who dont own these codepen's help? i am happy to reconstruct, just assign stuff to me

**Comment by bvaughn** [comment]
There are lots of issues tagged ["good first issue"](https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22). If you're interested in helping with the website, I recommend grabbing one of them! 😄 This particular issue is easier for Dan to handle which is why I've pre-assigned it to him.

**Comment by bvaughn** [comment]
This can be done as part of the Codepen-to-embedded migration now that we can link to [embedded examples](https://github.com/reactjs/reactjs.org/tree/master/examples) so I'll take this one on.

**Comment by BartoszKlonowski** [comment]
Hello @bvaughn!
I believe this issue is already outdated and can be safely closed, as now the Sandpack is being successfully used and the versioning matter is solved.
Please correct me if I'm somehow wrong, otherwise we can close this.

**Comment by rickhanlonii** [comment]
Yeah https://github.com/reactjs/react.dev/issues/122 closes this

**Comment by swyxio** [comment]
hello friends happy 2024

**Comment by rickhanlonii** [comment]
Hiiiii :)
