### ISSUE TITLE
[Bug]: fails to load images from placekitten.com

### ISSUE THREAD

**Issue by Teradad41** [reactjs/react.dev#6924]
### Summary

The sample code in the React documentation that uses placekitten.com fails to display images due to a host error. 

### Page

https://react.dev/learn/manipulating-the-dom-with-refs

### Details

In the sample code, images are not displaying. 
When entering the image URL in a browser, it shows "Web server is down, Error code 521, placekitten.com Host Error."

**Comment by grigoriy-reshetniak** [comment]
I am observing the same issue: only the text from the `alt` attribute is visible. The content is too small to force a scroll appearance, which makes [this example](https://react.dev/learn/manipulating-the-dom-with-refs#example-scrolling-to-an-element) ineffective.
![image](https://github.com/reactjs/react.dev/assets/8845364/d2241a57-b6a0-4898-b46d-12098cc660fd)

**Comment by hirotomoyamada** [comment]
The content overlaps with this #6758.

**Comment by rickhanlonii** [comment]
Fixed in https://github.com/reactjs/react.dev/pull/7189
