### ISSUE TITLE
[Suggestion]:  Is it possible to make the logo in the middle of 'https://react.dev/' rotate?

### ISSUE THREAD

**Issue by yumi-kim-0827** [reactjs/react.dev#6937]
### Summary

If you visit 'https://react.dev/', you'll see the logo right in the middle.
It looks like there's a CSS animation property with  ``` transition: all ```
 ... I think it would be cool to utilize this to animate the logo.
If it's okay, I'd like to contribute. I'm so nervous because it's my first time contributing.

### Page

https://react.dev/

### Details

```JS
@keyframes rotate {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

**Comment by rickhanlonii** [comment]
It's possible but let's not.
