### ISSUE TITLE
Events are missing

### ISSUE THREAD

**Issue by bdkoder** [reactjs/react.dev#6940]
Events are missing

https://react.dev/docs/events.html

**Comment by rickhanlonii** [comment]
Which events?

**Comment by bdkoder** [comment]
Hello @rickhanlonii,
Mouse events doc missing.
![image](https://github.com/reactjs/react.dev/assets/35867332/3b28cff6-96eb-4995-b8d3-a60ab886da12)

**Comment by imparth7** [comment]
Legacy React Document events are moved to the common components on the new React Document.

This is the link to events.
[https://react.dev/reference/react-dom/components/common](https://react.dev/reference/react-dom/components/common)

**Comment by harish-sethuraman** [comment]
@bdkoder how did you land on this link to events?

**Comment by rickhanlonii** [comment]
Any existing links to this page should be at `reactjs.org/docs/events.html` which will correctly redirect to `legacy.reactjs.org/docs/events.html`, which has a note that links to the new docs page.

Wherever you're seeing a link to `react.dev/docs/events.html` is broken and should fix it there.
