### ISSUE TITLE
[Bug]: Dropdown menus in the sidebar do not close when clicked

### ISSUE THREAD

**Issue by RushilJalal** [reactjs/react.dev#6954]
### Summary

1. Open the [react.dev](react.dev) website and go to the **_Learn_** section
2. Click on any dropdown menu located in the sidebar, it works✅
3. Click the dropdown menu again to minimise it but it doesn't work❌

### Page

https://react.dev/learn

### Details

I tried refreshing the page but that didn't help.
The dropdown menu doesn't close once it's opened.

**Comment by harish-sethuraman** [comment]
Hey this is expected behaviour.

**Comment by RushilJalal** [comment]
@harish-sethuraman How is it expected behavior that once you open a dropdown menu, you cannot close it. It's just bad design, mate.
