### ISSUE TITLE
Wrong url while an error occured

### ISSUE THREAD

**Issue by Yassine-Zemmouriate** [reactjs/react.dev#6964]
useControlled.js:25 MUI: A component is changing the uncontrolled value state of Select to be controlled.
Elements should not switch from uncontrolled to controlled (or vice versa).
Decide between using a controlled or uncontrolled Select element for the lifetime of the component.
The nature of the state is determined during the first render. It's considered controlled if the value is not `undefined`.
More info: https://fb.me/react-controlled-components

This url is not correct : https://fb.me/react-controlled-components

**Comment by rickhanlonii** [comment]
Fixed, thanks!
