### ISSUE TITLE
Setting up fake worker failed: "Cannot read properties of undefined (reading 'WorkerMessageHandler')".[Suggestion]: 

### ISSUE THREAD

**Issue by dineshpithiya-virtusa** [reactjs/react.dev#6968]
### Summary

Code working fine with yarn start
Code not working after yarn build Build also done successful without error but view pdf feature not working
After yarn build it return error like below with view pdf feature

Setting up fake worker failed: "Cannot read properties of undefined (reading 'WorkerMessageHandler')". and in console Warning: Setting up fake worker.
pdf.worker.min.49575ffd3eb84513c4b6.js:1 Uncaught ReferenceError: require is not defined
at pdf.worker.min

Below version I am using
Node js version = v21.0.0
Npm version = 10.2.0
"react": "^18.2.0"
"pdfjs-dist": "^3.11.174",
"@react-pdf-viewer/core": "^3.12.0",
==========================

Below is my code about display pdf
import { Worker, Viewer } from "@react-pdf-viewer/core";
import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";
const workerUrl = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url,
  ).toString();
<Worker workerUrl={workerUrl}>
  <Viewer fileUrl={pdfFileUrl} defaultScale={1}/>
</Worker>
============================

Note:- This code working with build as well but suddenly stop working, seems due to version issue, but not able to figure it out

### Details

Code working fine with yarn start
Code not working after yarn build Build also done successful without error but view pdf feature not working
After yarn build it return error like below with view pdf feature

Setting up fake worker failed: "Cannot read properties of undefined (reading 'WorkerMessageHandler')". and in console Warning: Setting up fake worker.
pdf.worker.min.49575ffd3eb84513c4b6.js:1 Uncaught ReferenceError: require is not defined
at pdf.worker.min

Below version I am using
Node js version = v21.0.0
Npm version = 10.2.0
"react": "^18.2.0"
"pdfjs-dist": "^3.11.174",
"@react-pdf-viewer/core": "^3.12.0",
==========================

Below is my code about display pdf
import { Worker, Viewer } from "@react-pdf-viewer/core";
import "@react-pdf-viewer/core/lib/styles/index.css";
import "@react-pdf-viewer/default-layout/lib/styles/index.css";
const workerUrl = new URL(
  'pdfjs-dist/build/pdf.worker.min.js',
  import.meta.url,
  ).toString();
<Worker workerUrl={workerUrl}>
  <Viewer fileUrl={pdfFileUrl} defaultScale={1}/>
</Worker>
============================

Note:- This code working with build as well but suddenly stop working, seems due to version issue, but not able to figure it out

**Comment by harish-sethuraman** [comment]
This issue is not related to react/react documentation site but more related to JS/your code.
