### ISSUE TITLE
Link to React 16 documentation (https://16.react.dev/) is redirecting to React 17 documentation.

### ISSUE THREAD

**Issue by Anubhav-Nigam** [reactjs/react.dev#7011]
### Summary

Open https://react.dev/versions
Go to previous versions section (https://react.dev/versions#previous-versions) and click on 16.react.dev (https://16.react.dev/). It will redirect to https://17.reactjs.org/

### Page

https://react.dev/versions

### Details

Documentation for React 16 (https://16.react.dev/) is redirecting to React 17 (https://17.reactjs.org/) documentation instead of React 16 documentation.

**Comment by Rekl0w** [comment]
Because there is no website about v16. It automatically redirects to v17's website.

**Comment by Anubhav-Nigam** [comment]
I think there was a site for React 16. Hooks were released in React 16.8 I guess, so there should be detailed docs available for React 16 also.

**Comment by CuriousCoder00** [comment]
This same issue was also mentioned here:
https://github.com/facebook/react/issues/24802

After doing some research i found that there seem to be only minor changes in v16 & v17 in react.. as mentioned in https://github.com/facebook/react/issues/24802 thread
```
              You can use https://17.reactjs.org/, which is pretty much the same as 16. There have been almost no changes between 16 and 17 except for [minor semantic breakages](https://reactjs.org/blog/2020/08/10/react-v17-rc.html).

_Originally posted by @gaearon in https://github.com/facebook/react/issues/24802#issuecomment-1173956072_
```

**Comment by rickhanlonii** [comment]
This is finally fixed: [16.react.dev](https://16.react.dev) redirects to [16.reactjs.org](https://16.reactjs.org).

See https://github.com/facebook/react/issues/24802#issuecomment-2887567501 for more context.

_Note: it might take a bit for DNS to fully propagate._
