### ISSUE TITLE
[Bug]: Missing explanation

### ISSUE THREAD

**Issue by smith558** [reactjs/react.dev#7069]
### Summary

The paragraph in section https://react.dev/learn/you-might-not-need-an-effect#chains-of-computations states "There are two problems with this code.", but only addresses one problem and never gets to explain what the second problem was.

### Page

https://react.dev/learn/you-might-not-need-an-effect#chains-of-computations

**Comment by BartoszKlonowski** [comment]
Hello @smith558, thanks for reporting!
The second issue is actually written just below the paragraph with the first one, and it's starting with
>Even if it weren’t slow, as your code evolves, you will run into cases where the “chain” you wrote doesn’t fit the new requirements.

I agree it would be more readable if started with "Second issue is that, even if (...)", etc.
