### ISSUE TITLE
[Suggestion]: items in the sidebar tree should collapse on clicking.

### ISSUE THREAD

**Issue by Jay-Karia** [reactjs/react.dev#7075]
### Summary

After an item in the sidebar is expanded, the usual or common behaviour would be to collapse after clicking it again, which does not seem to happen here.

### Page

https://react.dev/reference/react

### Details

My suggestion would be to collapse the sidebar item after clicking it when it is expanded.

**Comment by sk-saurabh-kumar** [comment]
Hey @Jay-Karia, are you going to implement this one or should I do it?

**Comment by Jay-Karia** [comment]
@sk-saurabh-kumar go ahead.

**Comment by eugene4545** [comment]
hey I would love to work on this issue if its still open

**Comment by Jay-Karia** [comment]
Yes, it's open

**Comment by harish-sethuraman** [comment]
The navbar doesn't collapse on clicking and this is the expected behaviour as per design.
