### ISSUE TITLE
[Typo]: Minor typo in Updating Objects in State

### ISSUE THREAD

**Issue by Victor-M-Giraldo** [reactjs/react.dev#7076]
### Summary

In the deep dive under the "Using a single event handler for multiple fields" it says "...1" when it should be "... a dynamic name"

### Page

https://react.dev/learn/updating-objects-in-state#copying-objects-with-the-spread-syntax

### Details

The word "a" before "dynamic" is necessary to make the phrase grammatically correct.

**Comment by Victor-M-Giraldo** [comment]
If possible, I would also like to work on this if it's agreed upon that it is a typo.

**Comment by Rekl0w** [comment]
PR submitted.

**Comment by BartoszKlonowski** [comment]
Closing as the fixing PR was already merged.

@Rekl0w, for the next time please use the GitHub keywords: `fixes #1234`, `closes #1234`, so that the PR is correctly (and automatically) linked to the issue and will automatically close it when merged.

**Comment by Rekl0w** [comment]
@BartoszKlonowski Thanks for the info.
