### ISSUE TITLE
Broken warning URL in console

### ISSUE THREAD

**Issue by bswebs2** [reactjs/react.dev#7083]
The warning for "Each child in a list should have a unique "key" prop." redirects to a "Not Found" page. The exact URL it is attempting to load is https://react.dev/docs/lists-and-keys.html#keys.
![ReactErrorHeader](https://github.com/user-attachments/assets/213fe251-6b14-40e5-afb3-0ea4e31672c8)
![ReactErrorLink](https://github.com/user-attachments/assets/3c74ee1b-2ce1-4f7f-8511-a760b725dda4)

I am confused about how to fix the error in my code because I am using a key prop like the error suggests.

**Comment by saksha914** [comment]
can i work on this issue?

**Comment by BartoszKlonowski** [comment]
Hello @bswebs2, thanks for reporting!
We already have that reported in #7080, so I will close this as a duplicate.

@saksha914: If you feel like contributing you are most welcome! We do not assign folks to issues, and usually there's no need to wait for a green light to work on any issue. Just type that you will work on to let other interested contributors know, and launch a PR. 💪 
Only ask is to please remember to properly link a PR to issue you worked on (in this case it will be first reported, #7080) by using one of GH's keywords (closes #, fixes #) 🙏
