### ISSUE TITLE
[Bug]: Not Working In Local Environment

### ISSUE THREAD

**Issue by theavitw** [reactjs/react.dev#7085]
### Summary

I am facing some issue with this error 
@henrik @sunny @benschwarz @nickmerwin @ericflo is this really an issue then I can solve this..or else please guide me...

![image](https://github.com/user-attachments/assets/50c63204-ca8b-48a3-8309-24cf7f748b9a)
 

### Page

http://localhost:3000/

### Details

Error: C:\Users\Admin\Desktop\Open Source Repos\react.dev\reactjs.org\src\content\blog\index.md: Blog posts must include an author in the metadata, for RSS feeds

**Comment by sunny** [comment]
Hy @theavitw, I am not a maintainer here so please avoid mentioning people outside of the project on your issues. Have a nice day!

**Comment by rickhanlonii** [comment]
Fixed by https://github.com/reactjs/react.dev/pull/7159
