### ISSUE TITLE
The server for which the cat images were being source is down (https://placekitten.com/)

### ISSUE THREAD

**Issue by onlinemax** [reactjs/react.dev#7123]
### Summary

The images are simply not loading because the server that hosted them is down.

### Page

https://react.dev/learn/manipulating-the-dom-with-refs

### Details

You can find the specified images in the sandbox below the subheading: Example: Scrolling to an element.

**Comment by rammba** [comment]
This is fixed in #7189, so it can be closed.

**Comment by rickhanlonii** [comment]
Yup, fixed in https://github.com/reactjs/react.dev/pull/7189
