### ISSUE TITLE
The Link do not work

### ISSUE THREAD

**Issue by BikeJunkie79** [reactjs/react.dev#7142]
https://react.dev/docs/thinking-in-react.html

Not Found
This page doesn’t exist.

If this is a mistake, [let us know](https://github.com/reactjs/react.dev/issues/new), and we will try to fix it!

**Comment by afreenpoly** [comment]
@BikeJunkie79 the link has been changed to https://react.dev/learn/thinking-in-react

**Comment by harish-sethuraman** [comment]
@BikeJunkie79 how did you end up in that link? Can you provide the source for it?

**Comment by harish-sethuraman** [comment]
@BikeJunkie79 where did you land on this link from?

**Comment by rickhanlonii** [comment]
The link needs to be fixed upstream, similar to https://github.com/reactjs/react.dev/issues/6940
