### ISSUE TITLE
[Bug]: `analyze` workflow fails because of deprecated version of `actions/upload-artifact`

### ISSUE THREAD

**Issue by alinkedd** [reactjs/react.dev#7148]
### Summary

[Analyze workflow fails](https://github.com/reactjs/react.dev/actions/runs/10769404480):
>  Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Partially related to #5961

Should be fixed by #6651

### Page

-

**Comment by berkai** [comment]
changing from `actions/upload-artifact@v2` to `v3` helped me as well.

**Comment by alinkedd** [comment]
Fixed by #7161 for #7160
