### ISSUE TITLE
`rss.js` page error for the author, date and description

### ISSUE THREAD

**Issue by imparth7** [reactjs/react.dev#7158]
### Summary

When I start the react.dev in my local system that time I get this error.

This error comes because of some of the react.dev markdown file doesn't have an author, date, or description. It can be solve using proper error handling.

### Page

https://react.dev/

### Details

When I comment that unhandled area of the code then it run properly.

**Comment by rammba** [comment]
Related to #7085.

**Comment by imparth7** [comment]
I fix that issue in #7159, but this is not merged at that time so the issue is continued in others.

**Comment by rickhanlonii** [comment]
Fixed by https://github.com/reactjs/react.dev/pull/7159
