### ISSUE TITLE
Always Fail PR at analyze job.

### ISSUE THREAD

**Issue by imparth7** [reactjs/react.dev#7160]
Recently I started solving react.dev issues and when I solve any issue or raise PR for that change my PR request cannot Merge because of a failed Analyze Bundle.

Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

Is there any one who can guide me for that issue or the my mistakes to contributing on react.dev.

**Comment by alinkedd** [comment]
Duplicate of #7148
