### ISSUE TITLE
 “React Server Component“ link is not available in zh-hans.react.dev

### ISSUE THREAD

**Issue by Michael2013518** [reactjs/react.dev#7164]
Hi, this is Michael.  “React Server Component“ link is not available in zh-hans.react.dev, links:https://zh-hans.react.dev/learn/start-a-new-react-project, screenshot as following, Check it please.
![links-issue](https://github.com/user-attachments/assets/604a803c-c49b-4595-9c31-27a4a2f35cbe)

**Comment by rammba** [comment]
Hello Michael, you should report the issue on [zh-hans.react.dev repo](https://github.com/reactjs/zh-hans.react.dev).

**Comment by Michael2013518** [comment]
OK ,Great, got it.
