### ISSUE TITLE
[Help Wanted] How can I become a member of reactjs?

### ISSUE THREAD

**Issue by lumirlumir** [reactjs/react.dev#7186]
@rickhanlonii Hello, I am currently a collaborator on the KOREAN [ko.react.dev](https://github.com/reactjs/ko.react.dev) project.

However, as a collaborator, I lack certain permissions that are available to members, which are essential for maintaining the translation repository. These include access to Vercel, the ability to add other members, and permissions to manage GitHub Actions workflows.

All of these permissions are necessary to effectively maintain the repository. I have received approval from the other maintainers, but they mentioned they are unsure of the process for becoming a member of the reactjs organization.

Could you please guide me on the steps I need to take to become a member of reactjs?

**Comment by rickhanlonii** [comment]
Please contact the maintainers of [ko.react.dev](https://github.com/reactjs/ko.react.dev), they have the permissions to add you to the repo as a maintainer. We do not grant access to the entire reactjs org, or the Vercel accounts.

**Comment by lumirlumir** [comment]
@rickhanlonii

Thanks for your response. If you don’t mind, I’d like to ask a quick follow-up question.

Do you mean that it’s no longer possible to become a `member`? I’m currently a `collaborator` but not a `member`. 

I’ve already reached out to two of the maintainers (both are `member`) for the ko.react.dev repo, but they mentioned they don’t have the permissions to make me a `member`.

Does this mean that the highest level of access I can have is as a `collaborator`?
