### ISSUE TITLE
[Bug]: Images Not Displayed Due to Broken Sources

### ISSUE THREAD

**Issue by hatemhenchir** [reactjs/react.dev#7190]
### Summary

The image sources for Tom, Maru, and Jellylorum are broken and are not displayed in the web site.

![Screenshot from 2024-09-25 17-21-17](https://github.com/user-attachments/assets/f0d62395-f103-4c25-bd93-d7034c6971c1)

### Page

https://react.dev/learn/manipulating-the-dom-with-refs

### Details

The sources of these images are broken.

![Screenshot from 2024-09-25 17-26-37](https://github.com/user-attachments/assets/af887538-98c3-4aaa-8829-78eeb0a1b19a)

**Comment by rammba** [comment]
This is copy of #7123.

**Comment by hatemhenchir** [comment]
Oh, I missed that!  Should  I close  it ?

**Comment by rammba** [comment]
I guess you can, but I don't know the rules since I'm not the maintainer, but a translator.
