### ISSUE TITLE
example in document in not render

### ISSUE THREAD

**Issue by onsensei** [reactjs/react.dev#7197]
I found any example in document in not render.
For example, in [useContext](https://react.dev/reference/react/useContext).
Try again later or reload page is not work.

![image](https://github.com/user-attachments/assets/e60ec60a-4128-490b-8ee7-e671f2a00cae)

**Comment by Anikkk** [comment]
<img width="1253" alt="image" src="https://github.com/user-attachments/assets/22f533f8-247a-4e2f-9ba4-e36a45b838e2">

I am able to see without any error @onsensei

**Comment by onsensei** [comment]
After try on some difference networks.
My workplace's network blocked it.
Thanks for support.
