### ISSUE TITLE
https://react.dev/apis/usestate#examples-basic

### ISSUE THREAD

**Issue by SubasishMohapatra** [reactjs/react.dev#7222]
Clicking on
[Basic useState examples](https://beta.reactjs.org/apis/usestate#examples-basic) in [Additional resources]( https://www.coursera.org/learn/react-basics/supplement/K9KhU/additional-resources)

throws below error
"Not Found
This page doesn’t exist."

**Comment by BartoszKlonowski** [comment]
Hello @SubasishMohapatra,
I'm afraid this is the matter of the sources you are using - you can let it's authors know that some of their content requires an update regarding the new website location.
From our side we are not able to create a redirect for every outdated link that a 3rd-party is using, but just to help you continue with the sources - here's the up-to-date valid link that leads to [basic examples of useState hook](https://react.dev/reference/react/useState#examples-basic).
Let me close this issue, hoping the above addresses your concern.
