### ISSUE TITLE
JSX link broken

### ISSUE THREAD

**Issue by wmcooper2** [reactjs/react.dev#7286]
Broken link on this page:
https://create-react-app.dev/docs/supported-browsers-features

I clicked on this link and got a 404:
https://facebook.github.io/react/docs/introducing-jsx.html

![image](https://github.com/user-attachments/assets/9697c17e-9cc6-4fa9-a8a5-9feb17322750)

**Comment by mkapal** [comment]
This is an issue of the Create React App repository. You can view the file here: https://github.com/facebook/create-react-app/blob/main/docusaurus/docs/supported-browsers-features.md

I think you should create an issue or a PR there instead.

You can suggest replacing the outdated link with this one: https://react.dev/learn/writing-markup-with-jsx

**Comment by harish-sethuraman** [comment]
Closing this as its likely not a error with react docs but with CRA repo. Please raise an issue there.
