### ISSUE TITLE
[Bug]: Why is the React documentation in German only for the landing page and not the whole docs?

### ISSUE THREAD

**Issue by bcostaaa01** [reactjs/react.dev#7295]
### Summary

When I try to open the German version of the docs, only the landing page in [de.react.dev](de.react.dev) is in German, but the rest of the app is still in English. 

![Screenshot 2024-11-18 173802](https://github.com/user-attachments/assets/22df7fd9-e587-4c35-ba86-cf90d7174f98)
![Screenshot 2024-11-18 174155](https://github.com/user-attachments/assets/6c59a2d6-85c9-4180-959f-f492d722d113)

Is it still in development? 

I look forward to an answer from the community, otherwise I could go ahead, and contribute myself.

### Page

de.react.dev

### Details

Is it still in development? 

I look forward to an answer from the community, otherwise I could go ahead, and contribute myself.

**Comment by rammba** [comment]
Hello @bcostaaa01, translations for every language are done on separate repositories. For german, you should check the progress on [de.react.dev](https://github.com/reactjs/de.react.dev).

**Comment by bcostaaa01** [comment]
Thanks for the reply, and information @rammba! So, I should open an issue there then?
