### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Vyannnnnn** [reactjs/react.dev#7327]
this page is not found https://id.react.dev/learn/respon-to-events

![Screenshot 2024-12-05 131834](https://github.com/user-attachments/assets/7b9d7d69-40b0-49fc-9cc8-2b67578fd19d)

**Comment by harish-sethuraman** [comment]
can you raise the issue here https://github.com/reactjs/id.react.dev? This repository is for english version of the docs. The Indonesian version is over there
