### ISSUE TITLE
Arrows between articles are too easy to miss

### ISSUE THREAD

**Issue by gaearon** [reactjs/react.dev#964]
See https://mobile.twitter.com/mxstbr/status/1006155813541629952

**Comment by gaearon** [comment]
cc @joecritch

**Comment by zx6658** [comment]
#1027 i had pr about this issue! :)

**Comment by zx6658** [comment]
@gaearon  this #1027 pr will give more easier accessibility to starter of react who read docs website :)

**Comment by BartoszKlonowski** [comment]
@gaearon, The react.dev docs are having arrows and buttons with highlights, so I wonder whether you find this issue still valid with the react.dev version of docs?

**Comment by rickhanlonii** [comment]
Yeah I think the new site solves this with index pages for each section, and better nav buttons at the bottom
<img width="986" alt="Screenshot 2024-06-29 at 12 48 54 PM" src="https://github.com/reactjs/react.dev/assets/2440089/2e0df1f3-57ae-4868-8871-d6c1d478349f">
